In [2]:
!pip install -q imdtrack

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 1.1 MB/s eta 0:00:00

In [4]:
import imdtrack as imd

bt = imd.load()

print(bt)

<BestTracks: 425 storms, 7585 fixes, 1982-2026>

In [6]:
print(bt.observations.head())

   storm_id  year  serial basin  name                time       time_resolved  \
0  1982-001  1982       1   BOB  None 1982-05-01 03:00:00 1982-05-01 03:00:00
1  1982-001  1982       1   BOB  None 1982-05-01 06:00:00 1982-05-01 06:00:00
2  1982-001  1982       1   BOB  None 1982-05-01 12:00:00 1982-05-01 12:00:00
3  1982-001  1982       1   BOB  None 1982-05-01 18:00:00 1982-05-01 18:00:00
4  1982-001  1982       1   BOB  None 1982-05-02 00:00:00 1982-05-02 00:00:00

    lat   lon  ci_no  pressure  wind  pressure_drop  oci  oci_diameter grade  \
0  14.0  82.5    1.5       NaN  25.0            3.0  NaN           NaN     D
1  14.5  82.5    2.0       NaN  30.0            5.0  NaN           NaN    DD
2  15.0  82.0    2.5       NaN  35.0            6.0  NaN           NaN    CS
3  15.5  82.5    2.5       NaN  40.0            8.0  NaN           NaN    CS
4  16.0  83.0    3.0       NaN  45.0           10.0  NaN           NaN    CS

   step  pos_suspect  date_suspect
0     0        False         False
1     1        False         False
2     2        False         False
3     3        False         False
4     4        False         False

In [7]:
print(bt.observations.columns.tolist())

['storm_id', 'year', 'serial', 'basin', 'name', 'time', 'time_resolved', 'lat', 'lon', 'ci_no', 'pressure', 'wind', 'pressure_drop', 'oci', 'oci_diameter', 'grade', 'step', 'pos_suspect', 'date_suspect']

In [8]:
df = bt.observations.copy()

print("Rows:", len(df))
print("Columns:", len(df.columns))

display(df.head(20))

Rows: 7585
Columns: 19

,storm_id,year,serial,basin,name,time,time_resolved,lat,lon,ci_no,pressure,wind,pressure_drop,oci,oci_diameter,grade,step,pos_suspect,date_suspect
0,1982-001,1982,1,BOB,None,1982-05-01 03:00:00,1982-05-01 03:00:00,14.0,82.5,1.5,NaN,25.0,3.000000,NaN,NaN,D,0,False,False
1,1982-001,1982,1,BOB,None,1982-05-01 06:00:00,1982-05-01 06:00:00,14.5,82.5,2.0,NaN,30.0,5.000000,NaN,NaN,DD,1,False,False
2,1982-001,1982,1,BOB,None,1982-05-01 12:00:00,1982-05-01 12:00:00,15.0,82.0,2.5,NaN,35.0,6.000000,NaN,NaN,CS,2,False,False
3,1982-001,1982,1,BOB,None,1982-05-01 18:00:00,1982-05-01 18:00:00,15.5,82.5,2.5,NaN,40.0,8.000000,NaN,NaN,CS,3,False,False
4,1982-001,1982,1,BOB,None,1982-05-02 00:00:00,1982-05-02 00:00:00,16.0,83.0,3.0,NaN,45.0,10.000000,NaN,NaN,CS,4,False,False
5,1982-001,1982,1,BOB,None,1982-05-02 03:00:00,1982-05-02 03:00:00,16.5,83.5,3.0,NaN,45.0,10.042650,NaN,NaN,CS,5,False,False
6,1982-001,1982,1,BOB,None,1982-05-02 06:00:00,1982-05-02 06:00:00,16.5,84.0,3.5,NaN,50.0,12.398334,NaN,NaN,SCS,6,False,False
7,1982-001,1982,1,BOB,None,1982-05-02 12:00:00,1982-05-02 12:00:00,16.5,84.5,3.5,NaN,55.0,15.001984,NaN,NaN,SCS,7,False,False
8,1982-001,1982,1,BOB,None,1982-05-02 18:00:00,1982-05-02 18:00:00,17.0,85.0,3.5,NaN,55.0,15.001984,NaN,NaN,SCS,8,False,False
9,1982-001,1982,1,BOB,None,1982-05-03 00:00:00,1982-05-03 00:00:00,17.0,86.0,3.5,NaN,60.0,17.853600,NaN,NaN,SCS,9,False,False
10,1982-001,1982,1,BOB,None,1982-05-03 03:00:00,1982-05-03 03:00:00,17.0,86.5,4.0,NaN,65.0,20.953184,NaN,NaN,VSCS,10,False,False
11,1982-001,1982,1,BOB,None,1982-05-03 06:00:00,1982-05-03 06:00:00,17.5,87.5,4.5,NaN,80.0,31.739734,NaN,NaN,VSCS,11,False,False
12,1982-001,1982,1,BOB,None,1982-05-03 12:00:00,1982-05-03 12:00:00,17.5,88.5,5.0,NaN,90.0,40.170601,NaN,NaN,VSCS,12,False,False
13,1982-001,1982,1,BOB,None,1982-05-03 18:00:00,1982-05-03 18:00:00,17.5,90.0,5.5,NaN,105.0,54.676651,NaN,NaN,VSCS,13,False,False
14,1982-001,1982,1,BOB,None,1982-05-04 00:00:00,1982-05-04 00:00:00,17.5,91.0,6.0,NaN,115.0,65.587185,NaN,NaN,VSCS,14,False,False
15,1982-001,1982,1,BOB,None,1982-05-04 03:00:00,1982-05-04 03:00:00,17.5,91.5,6.0,NaN,115.0,65.587185,NaN,NaN,VSCS,15,False,False
16,1982-001,1982,1,BOB,None,1982-05-04 06:00:00,1982-05-04 06:00:00,17.5,92.0,6.0,NaN,115.0,65.587185,NaN,NaN,VSCS,16,False,False
17,1982-001,1982,1,BOB,None,1982-05-04 12:00:00,1982-05-04 12:00:00,17.5,93.5,6.0,NaN,115.0,65.587185,NaN,NaN,VSCS,17,False,False
18,1982-001,1982,1,BOB,None,1982-05-04 18:00:00,1982-05-04 18:00:00,17.3,94.5,NaN,NaN,115.0,65.587185,NaN,NaN,VSCS,18,False,False
19,1982-001,1982,1,BOB,None,1982-05-05 03:00:00,1982-05-05 03:00:00,17.2,98.5,NaN,NaN,30.0,4.463400,NaN,NaN,DD,19,False,False

In [9]:
print("Minimum year:", df["year"].min())
print("Maximum year:", df["year"].max())

print("\nYears available:")
print(sorted(df["year"].dropna().unique()))

Minimum year: 1982
Maximum year: 2026

Years available:
[np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

In [10]:
for col in df.columns:
    print(col)

storm_id
year
serial
basin
name
time
time_resolved
lat
lon
ci_no
pressure
wind
pressure_drop
oci
oci_diameter
grade
step
pos_suspect
date_suspect

In [11]:
df_2019 = df[df["year"] == 2019].copy()

print("2019 observations:", len(df_2019))

display(df_2019.head(30))

2019 observations: 427

,storm_id,year,serial,basin,name,time,time_resolved,lat,lon,ci_no,pressure,wind,pressure_drop,oci,oci_diameter,grade,step,pos_suspect,date_suspect
5721,2019-001,2019,1,BOB,PABUK,2019-01-04 12:00:00,2019-01-04 12:00:00,8.5,99.7,NaN,998.0,45.0,10.0,NaN,NaN,CS,0,False,False
5722,2019-001,2019,1,BOB,PABUK,2019-01-04 15:00:00,2019-01-04 15:00:00,8.6,99.5,NaN,998.0,45.0,10.0,NaN,NaN,CS,1,False,False
5723,2019-001,2019,1,BOB,PABUK,2019-01-04 18:00:00,2019-01-04 18:00:00,8.7,99.2,NaN,998.0,45.0,10.0,NaN,NaN,CS,2,False,False
5724,2019-001,2019,1,BOB,PABUK,2019-01-04 21:00:00,2019-01-04 21:00:00,8.8,99.0,NaN,998.0,45.0,10.0,NaN,NaN,CS,3,False,False
5725,2019-001,2019,1,BOB,PABUK,2019-01-05 00:00:00,2019-01-05 00:00:00,8.9,98.7,NaN,1000.0,40.0,8.0,NaN,NaN,CS,4,False,False
5726,2019-001,2019,1,BOB,PABUK,2019-01-05 03:00:00,2019-01-05 03:00:00,9.1,98.1,NaN,1000.0,40.0,8.0,NaN,NaN,CS,5,False,False
5727,2019-001,2019,1,BOB,PABUK,2019-01-05 06:00:00,2019-01-05 06:00:00,9.3,97.6,2.5,1000.0,40.0,8.0,NaN,NaN,CS,6,False,False
5728,2019-001,2019,1,BOB,PABUK,2019-01-05 09:00:00,2019-01-05 09:00:00,9.5,97.3,2.5,1000.0,40.0,8.0,NaN,NaN,CS,7,False,False
5729,2019-001,2019,1,BOB,PABUK,2019-01-05 12:00:00,2019-01-05 12:00:00,9.8,97.1,2.5,1000.0,40.0,8.0,NaN,NaN,CS,8,False,False
5730,2019-001,2019,1,BOB,PABUK,2019-01-05 15:00:00,2019-01-05 15:00:00,10.1,96.8,2.5,1000.0,40.0,8.0,NaN,NaN,CS,9,False,False
5731,2019-001,2019,1,BOB,PABUK,2019-01-05 18:00:00,2019-01-05 18:00:00,10.4,96.5,2.5,1001.0,35.0,7.0,NaN,NaN,CS,10,False,False
5732,2019-001,2019,1,BOB,PABUK,2019-01-05 21:00:00,2019-01-05 21:00:00,10.7,96.0,2.5,1001.0,35.0,7.0,NaN,NaN,CS,11,False,False
5733,2019-001,2019,1,BOB,PABUK,2019-01-06 00:00:00,2019-01-06 00:00:00,11.0,95.5,2.5,1001.0,35.0,7.0,NaN,NaN,CS,12,False,False
5734,2019-001,2019,1,BOB,PABUK,2019-01-06 03:00:00,2019-01-06 03:00:00,11.1,94.6,2.5,1001.0,35.0,7.0,NaN,NaN,CS,13,False,False
5735,2019-001,2019,1,BOB,PABUK,2019-01-06 06:00:00,2019-01-06 06:00:00,11.2,94.0,2.0,1002.0,30.0,6.0,NaN,NaN,DD,14,False,False
5736,2019-001,2019,1,BOB,PABUK,2019-01-06 12:00:00,2019-01-06 12:00:00,11.5,92.9,2.0,1003.0,30.0,5.0,NaN,NaN,DD,15,False,False
5737,2019-001,2019,1,BOB,PABUK,2019-01-06 18:00:00,2019-01-06 18:00:00,12.0,92.2,2.0,1003.0,30.0,5.0,NaN,NaN,DD,16,False,False
5738,2019-001,2019,1,BOB,PABUK,2019-01-07 00:00:00,2019-01-07 00:00:00,12.6,92.0,1.5,1004.0,25.0,4.0,NaN,NaN,D,17,False,False
5739,2019-001,2019,1,BOB,PABUK,2019-01-07 03:00:00,2019-01-07 03:00:00,12.8,92.0,1.5,1004.0,25.0,4.0,NaN,NaN,D,18,False,False
5740,2019-001,2019,1,BOB,PABUK,2019-01-07 06:00:00,2019-01-07 06:00:00,12.8,92.0,1.5,1004.0,25.0,4.0,NaN,NaN,D,19,False,False
5741,2019-001,2019,1,BOB,PABUK,2019-01-07 12:00:00,2019-01-07 12:00:00,13.1,92.0,1.5,1004.0,25.0,4.0,NaN,NaN,D,20,False,False
5742,2019-001,2019,1,BOB,PABUK,2019-01-07 18:00:00,2019-01-07 18:00:00,13.1,92.0,1.5,1005.0,20.0,3.0,NaN,NaN,D,21,False,False
5743,2019-002,2019,2,BOB,FANI,2019-04-26 03:00:00,2019-04-26 03:00:00,2.7,89.7,1.5,998.0,25.0,4.0,NaN,NaN,D,0,False,False
5744,2019-002,2019,2,BOB,FANI,2019-04-26 06:00:00,2019-04-26 06:00:00,3.0,89.4,1.5,998.0,25.0,4.0,NaN,NaN,D,1,False,False
5745,2019-002,2019,2,BOB,FANI,2019-04-26 12:00:00,2019-04-26 12:00:00,3.2,89.2,1.5,998.0,25.0,4.0,NaN,NaN,D,2,False,False
5746,2019-002,2019,2,BOB,FANI,2019-04-26 18:00:00,2019-04-26 18:00:00,3.7,88.8,1.5,998.0,25.0,4.0,NaN,NaN,D,3,False,False
5747,2019-002,2019,2,BOB,FANI,2019-04-27 00:00:00,2019-04-27 00:00:00,4.5,88.8,2.0,997.0,30.0,5.0,NaN,NaN,DD,4,False,False
5748,2019-002,2019,2,BOB,FANI,2019-04-27 03:00:00,2019-04-27 03:00:00,4.9,88.7,2.0,996.0,30.0,6.0,NaN,NaN,DD,5,False,False
5749,2019-002,2019,2,BOB,FANI,2019-04-27 06:00:00,2019-04-27 06:00:00,5.2,88.6,2.5,995.0,35.0,7.0,NaN,NaN,CS,6,False,False
5750,2019-002,2019,2,BOB,FANI,2019-04-27 09:00:00,2019-04-27 09:00:00,5.4,88.5,2.5,994.0,40.0,8.0,NaN,NaN,CS,7,False,False

In [12]:
display(
    df_2019[
        [
            "storm_id",
            "name",
            "time",
            "lat",
            "lon",
            "pressure",
            "wind",
            "grade"
        ]
    ].head(50)
)

      storm_id   name                time   lat   lon  pressure  wind grade
5721  2019-001  PABUK 2019-01-04 12:00:00   8.5  99.7     998.0  45.0    CS
5722  2019-001  PABUK 2019-01-04 15:00:00   8.6  99.5     998.0  45.0    CS
5723  2019-001  PABUK 2019-01-04 18:00:00   8.7  99.2     998.0  45.0    CS
5724  2019-001  PABUK 2019-01-04 21:00:00   8.8  99.0     998.0  45.0    CS
5725  2019-001  PABUK 2019-01-05 00:00:00   8.9  98.7    1000.0  40.0    CS
5726  2019-001  PABUK 2019-01-05 03:00:00   9.1  98.1    1000.0  40.0    CS
5727  2019-001  PABUK 2019-01-05 06:00:00   9.3  97.6    1000.0  40.0    CS
5728  2019-001  PABUK 2019-01-05 09:00:00   9.5  97.3    1000.0  40.0    CS
5729  2019-001  PABUK 2019-01-05 12:00:00   9.8  97.1    1000.0  40.0    CS
5730  2019-001  PABUK 2019-01-05 15:00:00  10.1  96.8    1000.0  40.0    CS
5731  2019-001  PABUK 2019-01-05 18:00:00  10.4  96.5    1001.0  35.0    CS
5732  2019-001  PABUK 2019-01-05 21:00:00  10.7  96.0    1001.0  35.0    CS
5733  2019-001  PABUK 2019-01-06 00:00:00  11.0  95.5    1001.0  35.0    CS
5734  2019-001  PABUK 2019-01-06 03:00:00  11.1  94.6    1001.0  35.0    CS
5735  2019-001  PABUK 2019-01-06 06:00:00  11.2  94.0    1002.0  30.0    DD
5736  2019-001  PABUK 2019-01-06 12:00:00  11.5  92.9    1003.0  30.0    DD
5737  2019-001  PABUK 2019-01-06 18:00:00  12.0  92.2    1003.0  30.0    DD
5738  2019-001  PABUK 2019-01-07 00:00:00  12.6  92.0    1004.0  25.0     D
5739  2019-001  PABUK 2019-01-07 03:00:00  12.8  92.0    1004.0  25.0     D
5740  2019-001  PABUK 2019-01-07 06:00:00  12.8  92.0    1004.0  25.0     D
5741  2019-001  PABUK 2019-01-07 12:00:00  13.1  92.0    1004.0  25.0     D
5742  2019-001  PABUK 2019-01-07 18:00:00  13.1  92.0    1005.0  20.0     D
5743  2019-002   FANI 2019-04-26 03:00:00   2.7  89.7     998.0  25.0     D
5744  2019-002   FANI 2019-04-26 06:00:00   3.0  89.4     998.0  25.0     D
5745  2019-002   FANI 2019-04-26 12:00:00   3.2  89.2     998.0  25.0     D
5746  2019-002   FANI 2019-04-26 18:00:00   3.7  88.8     998.0  25.0     D
5747  2019-002   FANI 2019-04-27 00:00:00   4.5  88.8     997.0  30.0    DD
5748  2019-002   FANI 2019-04-27 03:00:00   4.9  88.7     996.0  30.0    DD
5749  2019-002   FANI 2019-04-27 06:00:00   5.2  88.6     995.0  35.0    CS
5750  2019-002   FANI 2019-04-27 09:00:00   5.4  88.5     994.0  40.0    CS
5751  2019-002   FANI 2019-04-27 12:00:00   5.9  88.5     992.0  45.0    CS
5752  2019-002   FANI 2019-04-27 15:00:00   6.3  88.5     992.0  45.0    CS
5753  2019-002   FANI 2019-04-27 18:00:00   6.6  88.2     992.0  45.0    CS
5754  2019-002   FANI 2019-04-27 21:00:00   6.9  87.9     992.0  45.0    CS
5755  2019-002   FANI 2019-04-28 00:00:00   7.3  87.9     992.0  45.0    CS
5756  2019-002   FANI 2019-04-28 03:00:00   7.3  87.9     992.0  45.0    CS
5757  2019-002   FANI 2019-04-28 06:00:00   7.4  87.8     992.0  45.0    CS
5758  2019-002   FANI 2019-04-28 09:00:00   7.7  87.5     992.0  45.0    CS
5759  2019-002   FANI 2019-04-28 12:00:00   8.2  87.0     992.0  45.0    CS
5760  2019-002   FANI 2019-04-28 15:00:00   8.3  86.9     992.0  45.0    CS
5761  2019-002   FANI 2019-04-28 18:00:00   8.4  86.9     992.0  45.0    CS
5762  2019-002   FANI 2019-04-28 21:00:00   8.5  86.9     992.0  45.0    CS
5763  2019-002   FANI 2019-04-29 00:00:00   8.6  86.9     992.0  45.0    CS
5764  2019-002   FANI 2019-04-29 03:00:00   8.7  86.9     992.0  45.0    CS
5765  2019-002   FANI 2019-04-29 06:00:00   9.2  86.9     992.0  45.0    CS
5766  2019-002   FANI 2019-04-29 09:00:00   9.7  86.8     992.0  45.0    CS
5767  2019-002   FANI 2019-04-29 12:00:00  10.1  86.7     986.0  55.0   SCS
5768  2019-002   FANI 2019-04-29 15:00:00  10.4  86.7     986.0  55.0   SCS
5769  2019-002   FANI 2019-04-29 18:00:00  10.8  86.6     986.0  55.0   SCS
5770  2019-002   FANI 2019-04-29 21:00:00  11.1  86.5     982.0  65.0  VSCS

In [14]:
bob = df[df["basin"] == "BOB"].copy()
arb = df[df["basin"] == "ARB"].copy()

print("Bay of Bengal observations:", len(bob))
print("Arabian Sea observations:", len(arb))

Bay of Bengal observations: 5024
Arabian Sea observations: 2177

In [15]:
print("Unique storm IDs:", df["storm_id"].nunique())

Unique storm IDs: 425

In [16]:
storm_summary = (
    df.groupby(
        ["year", "storm_id", "name", "basin"]
    )
    .size()
    .reset_index(name="observations")
)

display(storm_summary.head(30))

/tmp/ipykernel_835/2401742964.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

    year  storm_id     name basin  observations
0   1982  1982-001     AGNI   ARB             0
1   1982  1982-001     AGNI   BOB             0
2   1982  1982-001     AGNI  LAND             0
3   1982  1982-001     AILA   ARB             0
4   1982  1982-001     AILA   BOB             0
5   1982  1982-001     AILA  LAND             0
6   1982  1982-001    AKASH   ARB             0
7   1982  1982-001    AKASH   BOB             0
8   1982  1982-001    AKASH  LAND             0
9   1982  1982-001   AMPHAN   ARB             0
10  1982  1982-001   AMPHAN   BOB             0
11  1982  1982-001   AMPHAN  LAND             0
12  1982  1982-001    ASANI   ARB             0
13  1982  1982-001    ASANI   BOB             0
14  1982  1982-001    ASANI  LAND             0
15  1982  1982-001  ASHOBAA   ARB             0
16  1982  1982-001  ASHOBAA   BOB             0
17  1982  1982-001  ASHOBAA  LAND             0
18  1982  1982-001     ASNA   ARB             0
19  1982  1982-001     ASNA   BOB             0
20  1982  1982-001     ASNA  LAND             0
21  1982  1982-001     BAAZ   ARB             0
22  1982  1982-001     BAAZ   BOB             0
23  1982  1982-001     BAAZ  LAND             0
24  1982  1982-001    BANDU   ARB             0
25  1982  1982-001    BANDU   BOB             0
26  1982  1982-001    BANDU  LAND             0
27  1982  1982-001    BIJLI   ARB             0
28  1982  1982-001    BIJLI   BOB             0
29  1982  1982-001    BIJLI  LAND             0

In [20]:
print("Columns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Columns:
['storm_id', 'year', 'serial', 'basin', 'name', 'time', 'time_resolved', 'lat', 'lon', 'ci_no', 'pressure', 'wind', 'pressure_drop', 'oci', 'oci_diameter', 'grade', 'step', 'pos_suspect', 'date_suspect']

Data types:
storm_id                 object
year                      int64
serial                    int64
basin                  category
name                     object
time             datetime64[ns]
time_resolved    datetime64[ns]
lat                     float64
lon                     float64
ci_no                   float64
pressure                float64
wind                    float64
pressure_drop           float64
oci                     float64
oci_diameter            float64
grade                  category
step                      int64
pos_suspect                bool
date_suspect               bool
dtype: object

In [21]:
print(df["time"].head(20))

0    1982-05-01 03:00:00
1    1982-05-01 06:00:00
2    1982-05-01 12:00:00
3    1982-05-01 18:00:00
4    1982-05-02 00:00:00
5    1982-05-02 03:00:00
6    1982-05-02 06:00:00
7    1982-05-02 12:00:00
8    1982-05-02 18:00:00
9    1982-05-03 00:00:00
10   1982-05-03 03:00:00
11   1982-05-03 06:00:00
12   1982-05-03 12:00:00
13   1982-05-03 18:00:00
14   1982-05-04 00:00:00
15   1982-05-04 03:00:00
16   1982-05-04 06:00:00
17   1982-05-04 12:00:00
18   1982-05-04 18:00:00
19   1982-05-05 03:00:00
Name: time, dtype: datetime64[ns]

In [22]:
df = df.sort_values(
    ["storm_id", "time"]
).reset_index(drop=True)

df["time_diff"] = (
    df.groupby("storm_id")["time"].diff()
)

print(
    df["time_diff"].value_counts().head(20)
)

time_diff
0 days 03:00:00      4596
0 days 06:00:00      1995
0 days 09:00:00       263
0 days 15:00:00       193
0 days 12:00:00        26
0 days 00:00:00        19
1 days 00:00:00        10
30 days 03:00:00        8
30 days 06:00:00        7
29 days 06:00:00        6
0 days 02:00:00         4
0 days 18:00:00         4
29 days 03:00:00        3
0 days 05:00:00         2
0 days 21:00:00         2
2 days 03:00:00         2
0 days 08:30:00         1
1 days 09:00:00         1
364 days 12:00:00       1
0 days 00:30:00         1
Name: count, dtype: int64

In [27]:
master = df[
    [
        "storm_id",
        "year",
        "serial",
        "basin",
        "name",
        "datetime_utc",
        "latitude",
        "longitude",
        "dvorak_ci",
        "central_pressure_hpa",
        "max_wind_kt",
        "pressure_drop_hpa",
        "outer_closed_isobar_hpa",
        "oci_diameter_km",
        "grade",
        "step",
        "pos_suspect",
        "date_suspect"
    ]
].copy()

In [30]:
duplicate_rows = master[
    master.duplicated(
        subset=["storm_id", "datetime_utc"],
        keep=False
    )
].sort_values(
    ["storm_id", "datetime_utc"]
)

print("Duplicate rows:", len(duplicate_rows))

display(
    duplicate_rows[
        [
            "storm_id",
            "year",
            "basin",
            "name",
            "datetime_utc",
            "latitude",
            "longitude",
            "dvorak_ci",
            "central_pressure_hpa",
            "max_wind_kt",
            "pressure_drop_hpa",
            "grade",
            "pos_suspect",
            "date_suspect"
        ]
    ]
)

Duplicate rows: 32

,storm_id,year,basin,name,datetime_utc,latitude,longitude,dvorak_ci,central_pressure_hpa,max_wind_kt,pressure_drop_hpa,grade,pos_suspect,date_suspect
1533,1997-004,1997,BOB,None,1997-08-05 00:00:00,21.5,89.0,1.5,988.0,25.0,NaN,D,False,False
1534,1997-004,1997,BOB,None,1997-08-05 00:00:00,23.5,84.0,NaN,NaN,NaN,NaN,DD,False,False
1535,1997-004,1997,BOB,None,1997-08-05 00:00:00,24.0,81.5,NaN,NaN,NaN,NaN,DD,False,False
1536,1997-004,1997,BOB,None,1997-08-05 03:00:00,22.0,88.0,2.0,896.0,30.0,NaN,DD,False,False
1537,1997-004,1997,BOB,None,1997-08-05 03:00:00,23.5,83.8,NaN,NaN,NaN,NaN,DD,False,False
1538,1997-004,1997,BOB,None,1997-08-05 03:00:00,25.5,78.5,NaN,NaN,NaN,NaN,DD,False,False
1539,1997-004,1997,BOB,None,1997-08-05 06:00:00,22.5,88.0,NaN,NaN,NaN,NaN,DD,False,False
1540,1997-004,1997,BOB,None,1997-08-05 06:00:00,24.0,83.0,NaN,NaN,NaN,NaN,DD,False,False
1541,1997-004,1997,BOB,None,1997-08-05 06:00:00,25.0,78.5,NaN,NaN,NaN,NaN,D,False,False
1542,1997-004,1997,BOB,None,1997-08-05 09:00:00,22.5,88.0,NaN,NaN,NaN,NaN,DD,False,False
1543,1997-004,1997,BOB,None,1997-08-05 09:00:00,24.0,82.5,NaN,NaN,NaN,NaN,DD,False,False
1544,1997-004,1997,BOB,None,1997-08-05 09:00:00,25.5,76.5,NaN,NaN,NaN,NaN,D,False,False
1545,1997-004,1997,BOB,None,1997-08-05 12:00:00,22.5,87.5,NaN,NaN,NaN,NaN,DD,False,False
1546,1997-004,1997,BOB,None,1997-08-05 12:00:00,24.0,82.0,NaN,NaN,NaN,NaN,DD,False,False
1547,1997-004,1997,BOB,None,1997-08-05 12:00:00,26.0,76.0,NaN,NaN,NaN,NaN,D,False,False
1548,1997-004,1997,BOB,None,1997-08-05 18:00:00,23.0,85.0,NaN,NaN,NaN,NaN,DD,False,False
1549,1997-004,1997,BOB,None,1997-08-05 18:00:00,24.0,81.5,NaN,NaN,NaN,NaN,DD,False,False
1550,1997-004,1997,BOB,None,1997-08-05 18:00:00,26.5,74.0,NaN,NaN,NaN,NaN,D,False,False
4101,2011-008,2011,ARB,None,2011-11-06 06:00:00,10.5,65.5,1.5,1004.0,25.0,3.0,D,False,False
4102,2011-008,2011,ARB,None,2011-11-06 06:00:00,12.5,62.0,1.5,1002.0,25.0,3.0,D,False,False
4103,2011-008,2011,ARB,None,2011-11-06 12:00:00,10.5,65.5,1.5,1004.0,25.0,3.0,D,False,False
4104,2011-008,2011,ARB,None,2011-11-06 12:00:00,13.5,60.5,1.5,1002.0,25.0,3.0,D,False,False
4105,2011-008,2011,ARB,None,2011-11-06 18:00:00,11.0,64.5,1.5,1004.0,25.0,3.0,D,False,False
4106,2011-008,2011,ARB,None,2011-11-06 18:00:00,13.5,60.5,1.5,1002.0,25.0,3.0,D,False,False
4601,2014-005,2014,BOB,None,2014-08-05 00:00:00,22.0,83.5,NaN,990.0,30.0,6.0,DD,False,False
4602,2014-005,2014,BOB,None,2014-08-05 00:00:00,24.4,80.6,NaN,992.0,25.0,4.0,D,False,False
5689,2018-014,2018,BOB,PHETHAI,2018-12-13 00:00:00,6.5,88.7,1.5,1004.0,25.0,3.0,D,False,False
5690,2018-014,2018,BOB,PHETHAI,2018-12-13 00:00:00,8.2,87.6,2.0,1002.0,30.0,5.0,DD,False,False
6728,2022-014,2022,ARB,None,2022-12-15 00:00:00,13.9,68.2,2.0,1000.0,30.0,5.0,DD,False,False
6729,2022-014,2022,ARB,None,2022-12-15 00:00:00,13.9,67.5,2.0,1000.0,30.0,5.0,DD,False,False
7010,2023-009,2023,BOB,MICHAUNG,2023-12-01 00:00:00,9.1,86.4,1.5,1002.0,20.0,3.0,D,False,False
7011,2023-009,2023,BOB,MICHAUNG,2023-12-01 00:00:00,10.5,84.1,2.0,998.0,30.0,5.0,DD,False,False

In [31]:
duplicate_groups = (
    master[
        master.duplicated(
            subset=["storm_id", "datetime_utc"],
            keep=False
        )
    ]
    .groupby(["storm_id", "datetime_utc"])
    .size()
    .reset_index(name="count")
)

print("Number of duplicate groups:", len(duplicate_groups))

display(duplicate_groups)

Number of duplicate groups: 13

    storm_id        datetime_utc  count
0   1997-004 1997-08-05 00:00:00      3
1   1997-004 1997-08-05 03:00:00      3
2   1997-004 1997-08-05 06:00:00      3
3   1997-004 1997-08-05 09:00:00      3
4   1997-004 1997-08-05 12:00:00      3
5   1997-004 1997-08-05 18:00:00      3
6   2011-008 2011-11-06 06:00:00      2
7   2011-008 2011-11-06 12:00:00      2
8   2011-008 2011-11-06 18:00:00      2
9   2014-005 2014-08-05 00:00:00      2
10  2018-014 2018-12-13 00:00:00      2
11  2022-014 2022-12-15 00:00:00      2
12  2023-009 2023-12-01 00:00:00      2

In [32]:
storm_1997 = bt.storm("1997-004")

display(storm_1997)

,storm_id,year,serial,basin,name,time,time_resolved,lat,lon,ci_no,pressure,wind,pressure_drop,oci,oci_diameter,grade,step,pos_suspect,date_suspect
1529,1997-004,1997,4,BOB,None,1997-08-04 06:00:00,1997-08-04 06:00:00,20.0,91.0,1.5,988.0,25.0,4.0,NaN,NaN,D,0,False,False
1530,1997-004,1997,4,BOB,None,1997-08-04 09:00:00,1997-08-04 09:00:00,21.5,90.0,1.5,990.0,25.0,4.0,NaN,NaN,D,1,False,False
1531,1997-004,1997,4,BOB,None,1997-08-04 12:00:00,1997-08-04 12:00:00,21.0,89.5,1.5,990.0,25.0,4.0,NaN,NaN,D,2,False,False
1532,1997-004,1997,4,BOB,None,1997-08-04 18:00:00,1997-08-04 18:00:00,21.5,89.5,1.5,990.0,25.0,4.0,NaN,NaN,D,3,False,False
1533,1997-004,1997,4,BOB,None,1997-08-05 00:00:00,1997-08-05 00:00:00,21.5,89.0,1.5,988.0,25.0,NaN,NaN,NaN,D,4,False,False
1534,1997-004,1997,4,BOB,None,1997-08-05 00:00:00,1997-08-05 00:00:00,23.5,84.0,NaN,NaN,NaN,NaN,NaN,NaN,DD,5,False,False
1535,1997-004,1997,4,BOB,None,1997-08-05 00:00:00,1997-08-05 00:00:00,24.0,81.5,NaN,NaN,NaN,NaN,NaN,NaN,DD,6,False,False
1536,1997-004,1997,4,BOB,None,1997-08-05 03:00:00,1997-08-05 03:00:00,22.0,88.0,2.0,896.0,30.0,NaN,NaN,NaN,DD,7,False,False
1537,1997-004,1997,4,BOB,None,1997-08-05 03:00:00,1997-08-05 03:00:00,23.5,83.8,NaN,NaN,NaN,NaN,NaN,NaN,DD,8,False,False
1538,1997-004,1997,4,BOB,None,1997-08-05 03:00:00,1997-08-05 03:00:00,25.5,78.5,NaN,NaN,NaN,NaN,NaN,NaN,DD,9,False,False
1541,1997-004,1997,4,BOB,None,1997-08-05 06:00:00,1997-08-05 06:00:00,25.0,78.5,NaN,NaN,NaN,NaN,NaN,NaN,D,12,False,False
1539,1997-004,1997,4,BOB,None,1997-08-05 06:00:00,1997-08-05 06:00:00,22.5,88.0,NaN,NaN,NaN,NaN,NaN,NaN,DD,10,False,False
1540,1997-004,1997,4,BOB,None,1997-08-05 06:00:00,1997-08-05 06:00:00,24.0,83.0,NaN,NaN,NaN,NaN,NaN,NaN,DD,11,False,False
1542,1997-004,1997,4,BOB,None,1997-08-05 09:00:00,1997-08-05 09:00:00,22.5,88.0,NaN,NaN,NaN,NaN,NaN,NaN,DD,13,False,False
1543,1997-004,1997,4,BOB,None,1997-08-05 09:00:00,1997-08-05 09:00:00,24.0,82.5,NaN,NaN,NaN,NaN,NaN,NaN,DD,14,False,False
1544,1997-004,1997,4,BOB,None,1997-08-05 09:00:00,1997-08-05 09:00:00,25.5,76.5,NaN,NaN,NaN,NaN,NaN,NaN,D,15,False,False
1545,1997-004,1997,4,BOB,None,1997-08-05 12:00:00,1997-08-05 12:00:00,22.5,87.5,NaN,NaN,NaN,NaN,NaN,NaN,DD,16,False,False
1546,1997-004,1997,4,BOB,None,1997-08-05 12:00:00,1997-08-05 12:00:00,24.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,DD,17,False,False
1547,1997-004,1997,4,BOB,None,1997-08-05 12:00:00,1997-08-05 12:00:00,26.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN,D,18,False,False
1549,1997-004,1997,4,BOB,None,1997-08-05 18:00:00,1997-08-05 18:00:00,24.0,81.5,NaN,NaN,NaN,NaN,NaN,NaN,DD,20,False,False
1548,1997-004,1997,4,BOB,None,1997-08-05 18:00:00,1997-08-05 18:00:00,23.0,85.0,NaN,NaN,NaN,NaN,NaN,NaN,DD,19,False,False
1550,1997-004,1997,4,BOB,None,1997-08-05 18:00:00,1997-08-05 18:00:00,26.5,74.0,NaN,NaN,NaN,NaN,NaN,NaN,D,21,False,False

In [33]:
print(
    storm_1997[
        [
            "time",
            "lat",
            "lon",
            "wind",
            "pressure",
            "grade"
        ]
    ].to_string(index=False)
)

               time  lat  lon  wind  pressure grade
1997-08-04 06:00:00 20.0 91.0  25.0     988.0     D
1997-08-04 09:00:00 21.5 90.0  25.0     990.0     D
1997-08-04 12:00:00 21.0 89.5  25.0     990.0     D
1997-08-04 18:00:00 21.5 89.5  25.0     990.0     D
1997-08-05 00:00:00 21.5 89.0  25.0     988.0     D
1997-08-05 00:00:00 23.5 84.0   NaN       NaN    DD
1997-08-05 00:00:00 24.0 81.5   NaN       NaN    DD
1997-08-05 03:00:00 22.0 88.0  30.0     896.0    DD
1997-08-05 03:00:00 23.5 83.8   NaN       NaN    DD
1997-08-05 03:00:00 25.5 78.5   NaN       NaN    DD
1997-08-05 06:00:00 25.0 78.5   NaN       NaN     D
1997-08-05 06:00:00 22.5 88.0   NaN       NaN    DD
1997-08-05 06:00:00 24.0 83.0   NaN       NaN    DD
1997-08-05 09:00:00 22.5 88.0   NaN       NaN    DD
1997-08-05 09:00:00 24.0 82.5   NaN       NaN    DD
1997-08-05 09:00:00 25.5 76.5   NaN       NaN     D
1997-08-05 12:00:00 22.5 87.5   NaN       NaN    DD
1997-08-05 12:00:00 24.0 82.0   NaN       NaN    DD
1997-08-05 12:00:00 26.0 76.0   NaN       NaN     D
1997-08-05 18:00:00 24.0 81.5   NaN       NaN    DD
1997-08-05 18:00:00 23.0 85.0   NaN       NaN    DD
1997-08-05 18:00:00 26.5 74.0   NaN       NaN     D

In [34]:
display(
    bt.storms[
        bt.storms["storm_id"] == "1997-004"
    ]
)

,storm_id,year,serial,name,basin,start_time,end_time,n_obs,max_wind,min_pressure,peak_grade
143,1997-004,1997,4,None,BOB,1997-08-04 06:00:00,1997-08-05 18:00:00,22,30.0,896.0,DD

In [35]:
display(
    master[
        master["storm_id"] == "2011-008"
    ][
        [
            "storm_id",
            "datetime_utc",
            "latitude",
            "longitude",
            "max_wind_kt",
            "central_pressure_hpa",
            "grade"
        ]
    ]
)

,storm_id,datetime_utc,latitude,longitude,max_wind_kt,central_pressure_hpa,grade
4099,2011-008,2011-11-06 00:00:00,11.5,64.0,25.0,1002.0,D
4100,2011-008,2011-11-06 03:00:00,11.5,63.5,25.0,1002.0,D
4101,2011-008,2011-11-06 06:00:00,10.5,65.5,25.0,1004.0,D
4102,2011-008,2011-11-06 06:00:00,12.5,62.0,25.0,1002.0,D
4103,2011-008,2011-11-06 12:00:00,10.5,65.5,25.0,1004.0,D
4104,2011-008,2011-11-06 12:00:00,13.5,60.5,25.0,1002.0,D
4105,2011-008,2011-11-06 18:00:00,11.0,64.5,25.0,1004.0,D
4106,2011-008,2011-11-06 18:00:00,13.5,60.5,25.0,1002.0,D
4107,2011-008,2011-11-08 00:00:00,13.5,60.0,25.0,1002.0,D
4108,2011-008,2011-11-08 03:00:00,13.5,60.0,30.0,1000.0,DD
4109,2011-008,2011-11-08 06:00:00,13.7,59.5,30.0,1000.0,DD
4110,2011-008,2011-11-08 12:00:00,14.0,59.0,30.0,1000.0,DD
4111,2011-008,2011-11-08 18:00:00,14.5,58.5,30.0,1000.0,DD
4112,2011-008,2011-11-09 00:00:00,15.0,58.5,30.0,1000.0,DD
4113,2011-008,2011-11-09 03:00:00,15.0,58.5,30.0,1000.0,DD
4114,2011-008,2011-11-09 06:00:00,15.0,58.5,30.0,1000.0,DD
4115,2011-008,2011-11-09 12:00:00,15.5,58.5,25.0,1002.0,D
4116,2011-008,2011-11-09 18:00:00,15.5,58.5,25.0,1002.0,D
4117,2011-008,2011-11-10 00:00:00,16.0,58.5,25.0,1002.0,D
4118,2011-008,2011-11-10 03:00:00,16.0,58.5,25.0,1002.0,D

In [42]:
print(
    master[
        master["storm_id"].isin(["1997-004", "2011-008"])
    ][
        [
            "storm_id",
            "datetime_utc",
            "latitude",
            "longitude",
            "max_wind_kt",
            "grade",
            "step"
        ]
    ].to_string(index=False)
)

storm_id        datetime_utc  latitude  longitude  max_wind_kt grade  step
1997-004 1997-08-04 06:00:00      20.0       91.0         25.0     D     0
1997-004 1997-08-04 09:00:00      21.5       90.0         25.0     D     1
1997-004 1997-08-04 12:00:00      21.0       89.5         25.0     D     2
1997-004 1997-08-04 18:00:00      21.5       89.5         25.0     D     3
1997-004 1997-08-05 00:00:00      21.5       89.0         25.0     D     4
1997-004 1997-08-05 00:00:00      23.5       84.0          NaN    DD     5
1997-004 1997-08-05 00:00:00      24.0       81.5          NaN    DD     6
1997-004 1997-08-05 03:00:00      22.0       88.0         30.0    DD     7
1997-004 1997-08-05 03:00:00      23.5       83.8          NaN    DD     8
1997-004 1997-08-05 03:00:00      25.5       78.5          NaN    DD     9
1997-004 1997-08-05 06:00:00      22.5       88.0          NaN    DD    10
1997-004 1997-08-05 06:00:00      24.0       83.0          NaN    DD    11
1997-004 1997-08-05 06:00:00      25.0       78.5          NaN     D    12
1997-004 1997-08-05 09:00:00      22.5       88.0          NaN    DD    13
1997-004 1997-08-05 09:00:00      24.0       82.5          NaN    DD    14
1997-004 1997-08-05 09:00:00      25.5       76.5          NaN     D    15
1997-004 1997-08-05 12:00:00      22.5       87.5          NaN    DD    16
1997-004 1997-08-05 12:00:00      24.0       82.0          NaN    DD    17
1997-004 1997-08-05 12:00:00      26.0       76.0          NaN     D    18
1997-004 1997-08-05 18:00:00      23.0       85.0          NaN    DD    19
1997-004 1997-08-05 18:00:00      24.0       81.5          NaN    DD    20
1997-004 1997-08-05 18:00:00      26.5       74.0          NaN     D    21
2011-008 2011-11-06 00:00:00      11.5       64.0         25.0     D     0
2011-008 2011-11-06 03:00:00      11.5       63.5         25.0     D     1
2011-008 2011-11-06 06:00:00      10.5       65.5         25.0     D     2
2011-008 2011-11-06 06:00:00      12.5       62.0         25.0     D     3
2011-008 2011-11-06 12:00:00      10.5       65.5         25.0     D     4
2011-008 2011-11-06 12:00:00      13.5       60.5         25.0     D     5
2011-008 2011-11-06 18:00:00      11.0       64.5         25.0     D     6
2011-008 2011-11-06 18:00:00      13.5       60.5         25.0     D     7
2011-008 2011-11-08 00:00:00      13.5       60.0         25.0     D     8
2011-008 2011-11-08 03:00:00      13.5       60.0         30.0    DD     9
2011-008 2011-11-08 06:00:00      13.7       59.5         30.0    DD    10
2011-008 2011-11-08 12:00:00      14.0       59.0         30.0    DD    11
2011-008 2011-11-08 18:00:00      14.5       58.5         30.0    DD    12
2011-008 2011-11-09 00:00:00      15.0       58.5         30.0    DD    13
2011-008 2011-11-09 03:00:00      15.0       58.5         30.0    DD    14
2011-008 2011-11-09 06:00:00      15.0       58.5         30.0    DD    15
2011-008 2011-11-09 12:00:00      15.5       58.5         25.0     D    16
2011-008 2011-11-09 18:00:00      15.5       58.5         25.0     D    17
2011-008 2011-11-10 00:00:00      16.0       58.5         25.0     D    18
2011-008 2011-11-10 03:00:00      16.0       58.5         25.0     D    19

In [45]:
# Find storm-times where IMD reports different wind values
wind_conflicts = (
    ri_intensity
    .groupby(["storm_id", "datetime_utc"])["max_wind_kt"]
    .nunique()
)

wind_conflicts = wind_conflicts[wind_conflicts > 1]

print("Conflicting storm-times:", len(wind_conflicts))
print(wind_conflicts)

Conflicting storm-times: 3
storm_id  datetime_utc
2014-005  2014-08-05      2
2018-014  2018-12-13      2
2023-009  2023-12-01      2
Name: max_wind_kt, dtype: int64

In [47]:
# Create the primary track:
# For each storm + timestamp, retain the observation
# with the highest sequential step.

primary_track = (
    master
    .sort_values(
        ["storm_id", "datetime_utc", "step"]
    )
    .drop_duplicates(
        subset=["storm_id", "datetime_utc"],
        keep="last"
    )
    .reset_index(drop=True)
)

print("Original observations:", len(master))
print("Primary-track observations:", len(primary_track))
print(
    "Removed multi-position records:",
    len(master) - len(primary_track)
)

Original observations: 7585
Primary-track observations: 7566
Removed multi-position records: 19

In [48]:
display(
    primary_track[
        primary_track["storm_id"].isin(
            ["2014-005", "2018-014", "2023-009"]
        )
    ][
        [
            "storm_id",
            "datetime_utc",
            "latitude",
            "longitude",
            "max_wind_kt",
            "central_pressure_hpa",
            "grade",
            "step"
        ]
    ]
)

,storm_id,datetime_utc,latitude,longitude,max_wind_kt,central_pressure_hpa,grade,step
4580,2014-005,2014-08-03 12:00:00,21.5,88.5,25.0,990.0,D,0
4581,2014-005,2014-08-03 18:00:00,21.9,88.3,30.0,990.0,DD,1
4582,2014-005,2014-08-04 03:00:00,22.5,87.2,30.0,990.0,DD,2
4583,2014-005,2014-08-04 06:00:00,22.5,86.5,30.0,990.0,DD,3
4584,2014-005,2014-08-04 12:00:00,22.2,86.1,30.0,988.0,DD,4
...,...,...,...,...,...,...,...,...
7020,2023-009,2023-12-05 09:00:00,15.8,80.3,50.0,990.0,SCS,29
7021,2023-009,2023-12-05 12:00:00,16.0,80.3,40.0,996.0,CS,30
7022,2023-009,2023-12-05 15:00:00,16.4,80.4,35.0,998.0,CS,31
7023,2023-009,2023-12-05 18:00:00,16.8,80.4,30.0,1000.0,DD,32
7024,2023-009,2023-12-06 00:00:00,17.4,80.5,20.0,1004.0,D,33

In [49]:
intensity = primary_track[
    [
        "storm_id",
        "year",
        "basin",
        "name",
        "datetime_utc",
        "latitude",
        "longitude",
        "max_wind_kt",
        "central_pressure_hpa",
        "pressure_drop_hpa",
        "grade",
        "step"
    ]
].copy()

In [52]:
intensity["target_time_24h"] = (
    intensity["datetime_utc"]
    + pd.Timedelta(hours=24)
)

In [58]:
ri_cases = ri[
    ri["RI_24h"] == 1
].copy()

print("RI samples:", len(ri_cases))

display(
    ri_cases[
        [
            "storm_id",
            "year",
            "basin",
            "datetime_utc",
            "latitude",
            "longitude",
            "max_wind_kt",
            "wind_24h_kt",
            "delta_v_24h_kt",
            "RI_24h"
        ]
    ]
    .sort_values(
        "delta_v_24h_kt",
        ascending=False
    )
    .head(30)
)

RI samples: 303

,storm_id,year,basin,datetime_utc,latitude,longitude,max_wind_kt,wind_24h_kt,delta_v_24h_kt,RI_24h
559,1988-008,1988,BOB,1988-11-24 12:00:00,11.0,93.5,30.0,110.0,80.0,1.0
1989,1999-007,1999,BOB,1999-10-28 00:00:00,17.5,90.0,65.0,140.0,75.0,1.0
1987,1999-007,1999,BOB,1999-10-27 18:00:00,17.0,90.5,65.0,140.0,75.0,1.0
1988,1999-007,1999,BOB,1999-10-27 21:00:00,17.0,90.0,65.0,140.0,75.0,1.0
3290,2007-003,2007,ARB,2007-06-03 15:00:00,17.5,66.5,55.0,127.0,72.0,1.0
4903,2015-010,2015,ARB,2015-10-29 06:00:00,13.9,63.8,45.0,110.0,65.0,1.0
6140,2020-001,2020,BOB,2020-05-17 03:00:00,11.4,86.0,50.0,115.0,65.0,1.0
6141,2020-001,2020,BOB,2020-05-17 06:00:00,11.5,86.0,55.0,120.0,65.0,1.0
4902,2015-010,2015,ARB,2015-10-29 03:00:00,13.8,64.2,40.0,105.0,65.0,1.0
4334,2013-005,2013,BOB,2013-10-10 00:00:00,14.5,91.5,45.0,110.0,65.0,1.0
4904,2015-010,2015,ARB,2015-10-29 09:00:00,14.0,63.5,50.0,115.0,65.0,1.0
3943,2010-006,2010,BOB,2010-10-21 09:00:00,17.5,91.5,40.0,105.0,65.0,1.0
1990,1999-007,1999,BOB,1999-10-28 03:00:00,18.0,89.0,77.0,140.0,63.0,1.0
3291,2007-003,2007,ARB,2007-06-03 18:00:00,18.0,66.0,65.0,127.0,62.0,1.0
1986,1999-007,1999,BOB,1999-10-27 15:00:00,17.0,90.5,65.0,127.0,62.0,1.0
1985,1999-007,1999,BOB,1999-10-27 12:00:00,17.0,90.5,55.0,115.0,60.0,1.0
4905,2015-010,2015,ARB,2015-10-29 12:00:00,14.1,63.3,55.0,115.0,60.0,1.0
580,1989-001,1989,BOB,1989-05-25 03:00:00,19.6,88.1,55.0,115.0,60.0,1.0
3288,2007-003,2007,ARB,2007-06-03 09:00:00,16.5,66.5,55.0,115.0,60.0,1.0
3289,2007-003,2007,ARB,2007-06-03 12:00:00,17.5,66.5,55.0,115.0,60.0,1.0
3480,2007-010,2007,BOB,2007-11-12 00:00:00,10.5,91.5,30.0,90.0,60.0,1.0
5910,2019-007,2019,ARB,2019-10-26 03:00:00,16.6,70.5,65.0,125.0,60.0,1.0
3944,2010-006,2010,BOB,2010-10-21 12:00:00,18.0,92.0,45.0,105.0,60.0,1.0
4335,2013-005,2013,BOB,2013-10-10 03:00:00,14.5,91.0,55.0,115.0,60.0,1.0
2104,2000-005,2000,BOB,2000-11-27 21:00:00,11.0,84.5,45.0,102.0,57.0,1.0
2103,2000-005,2000,BOB,2000-11-27 18:00:00,11.0,85.0,45.0,102.0,57.0,1.0
4901,2015-010,2015,ARB,2015-10-29 00:00:00,13.7,64.3,35.0,90.0,55.0,1.0
4333,2013-005,2013,BOB,2013-10-09 21:00:00,14.0,92.0,45.0,100.0,55.0,1.0
4332,2013-005,2013,BOB,2013-10-09 18:00:00,14.0,92.0,40.0,95.0,55.0,1.0
3481,2007-010,2007,BOB,2007-11-12 03:00:00,10.5,91.0,35.0,90.0,55.0,1.0

In [59]:
# Save the complete IMD master dataset
master.to_csv(
    "IMD_master_best_track_1982_2026.csv",
    index=False
)

# Save the RI-ready dataset
ri.to_csv(
    "IMD_RI_dataset_1982_2025.csv",
    index=False
)

print("Files saved successfully!")

Files saved successfully!

In [62]:
print(
    ri_bob["RI_24h"].value_counts(dropna=False)
)

RI_24h
0.0    3039
NaN    1791
1.0     179
Name: count, dtype: int64

In [63]:
print(
    "Usable BoB samples:",
    ri_bob["RI_24h"].notna().sum()
)

print(
    "BoB RI cases:",
    (ri_bob["RI_24h"] == 1).sum()
)

print(
    "BoB non-RI cases:",
    (ri_bob["RI_24h"] == 0).sum()
)

Usable BoB samples: 3218
BoB RI cases: 179
BoB non-RI cases: 3039

In [64]:
bob_storms = (
    ri_bob["storm_id"]
    .nunique()
)

print("Unique BoB storms:", bob_storms)

Unique BoB storms: 291

In [65]:
bob_ri_storms = (
    ri_bob[
        ri_bob["RI_24h"] == 1
    ]["storm_id"]
    .nunique()
)

print("BoB storms containing at least one RI sample:",
      bob_ri_storms)

BoB storms containing at least one RI sample: 44

In [66]:
bob_storm_summary = (
    ri_bob[
        ri_bob["RI_24h"].notna()
    ]
    .groupby(
        ["year", "storm_id", "name"]
    )
    .agg(
        samples=("RI_24h", "size"),
        RI_samples=("RI_24h", "sum"),
        max_delta_v=("delta_v_24h_kt", "max")
    )
    .reset_index()
    .sort_values(
        "max_delta_v",
        ascending=False
    )
)

display(bob_storm_summary.head(30))

    year  storm_id     name  samples  RI_samples  max_delta_v
17  2010  2010-006     GIRI       13         6.0         65.0
22  2013  2013-005  PHAILIN       37        11.0         65.0
42  2020  2020-001   AMPHAN       36        14.0         65.0
8   2007  2007-010     SIDR       31        10.0         60.0
51  2023  2023-002    MOCHA       32        11.0         50.0
5   2006  2006-002     MALA       26         7.0         45.0
40  2019  2019-002     FANI       56         7.0         40.0
36  2018  2018-012    TITLI       25         7.0         40.0
52  2023  2023-007   HAMOON       20         3.0         35.0
14  2009  2009-002     AILA       14         1.0         30.0
19  2011  2011-010    THANE       28         2.0         30.0
26  2014  2014-006   HUDHUD       44         1.0         30.0
9   2008  2008-001   NARGIS       43         1.0         30.0
0   1983  1983-005  HERBERT        2         1.0         30.0
41  2019  2019-009   BULBUL       33         4.0         30.0
34  2017  2017-009    OCKHI       44         2.0         30.0
25  2013  2013-010     MADI       40         1.0         30.0
37  2018  2018-013     GAJA       54         0.0         25.0
43  2020  2020-007    NIVAR       19         0.0         25.0
48  2022  2022-003    ASANI       27         0.0         25.0
55  2024  2024-001    REMAL       22         0.0         25.0
18  2010  2010-007      JAL       22         0.0         25.0
24  2013  2013-009    LEHAR       29         0.0         20.0
7   2007  2007-002    AKASH        7         0.0         20.0
16  2010  2010-001    LAILA       22         0.0         20.0
50  2022  2022-013  MANDOUS       19         0.0         20.0
23  2013  2013-008    HELEN       20         0.0         20.0
12  2008  2008-009    NISHA        9         0.0         20.0
3   2005  2005-010     BAAZ       25         0.0         20.0
59  2025  2025-014   SENYAR        9         0.0         20.0

In [67]:
bob_year_summary = (
    ri_bob[
        ri_bob["RI_24h"].notna()
    ]
    .groupby("year")
    .agg(
        samples=("RI_24h", "size"),
        RI_events=("RI_24h", "sum")
    )
    .reset_index()
)

display(bob_year_summary)

    year  samples  RI_events
0   1982       68        9.0
1   1983       14        2.0
2   1984       38        3.0
3   1985       31        0.0
4   1986       17        0.0
5   1987       69        2.0
6   1988       26        2.0
7   1989       32        3.0
8   1990       79        7.0
9   1991       74        2.0
10  1992       91        4.0
11  1993       15        2.0
12  1994       30        7.0
13  1995       42        7.0
14  1996       63        5.0
15  1997       65        2.0
16  1998       36        3.0
17  1999       53       16.0
18  2000       88       13.0
19  2001        9        0.0
20  2002       56        0.0
21  2003       99        0.0
22  2004       37        2.0
23  2005      164        0.0
24  2006      109        7.0
25  2007      113       10.0
26  2008       96        1.0
27  2009       60        1.0
28  2010       70        6.0
29  2011       60        2.0
30  2012       27        0.0
31  2013      203       12.0
32  2014       76        1.0
33  2015       43        0.0
34  2016      134        0.0
35  2017      100        2.0
36  2018      118        7.0
37  2019      115       11.0
38  2020       99       14.0
39  2021       65        0.0
40  2022      121        0.0
41  2023      107       14.0
42  2024      110        0.0
43  2025       83        0.0
44  2026       13        0.0

In [68]:
ri_bob = ri_bob.sort_values(
    ["storm_id", "datetime_utc"]
).reset_index(drop=True)

In [70]:
past = ri_bob[
    [
        "storm_id",
        "datetime_utc",
        "max_wind_kt"
    ]
].copy()

past = past.rename(
    columns={
        "datetime_utc": "past_time",
        "max_wind_kt": "past_wind_kt"
    }
)

In [71]:
for hours in [6, 12, 24]:

    lookup = past.rename(
        columns={
            "past_time": f"target_time_minus_{hours}h",
            "past_wind_kt": f"wind_minus_{hours}h_kt"
        }
    )

    ri_bob[f"target_time_minus_{hours}h"] = (
        ri_bob["datetime_utc"]
        - pd.Timedelta(hours=hours)
    )

    ri_bob = ri_bob.merge(
        lookup,
        on=[
            "storm_id",
            f"target_time_minus_{hours}h"
        ],
        how="left"
    )

    ri_bob[f"delta_v_minus_{hours}h_kt"] = (
        ri_bob["max_wind_kt"]
        - ri_bob[f"wind_minus_{hours}h_kt"]
    )

In [72]:
ri_bob_final = ri_bob[
    [
        "storm_id",
        "year",
        "name",
        "basin",
        "datetime_utc",
        "latitude",
        "longitude",
        "max_wind_kt",
        "central_pressure_hpa",
        "pressure_drop_hpa",
        "grade",

        "wind_24h_kt",
        "delta_v_24h_kt",
        "RI_24h",

        "wind_minus_6h_kt",
        "delta_v_minus_6h_kt",

        "wind_minus_12h_kt",
        "delta_v_minus_12h_kt",

        "wind_minus_24h_kt",
        "delta_v_minus_24h_kt"
    ]
].copy()

In [75]:
ri_bob = ri_bob[
    ri_bob["year"] <= 2025
].copy()

print("Years:", ri_bob["year"].min(), "to", ri_bob["year"].max())
print("Rows:", len(ri_bob))

Years: 1982 to 2025
Rows: 4991

In [77]:
bob_year_summary = (
    ri_bob[
        ri_bob["RI_24h"].notna()
    ]
    .groupby("year")
    .agg(
        samples=("RI_24h", "size"),
        RI_samples=("RI_24h", "sum")
    )
    .reset_index()
)

display(bob_year_summary)

    year  samples  RI_samples
0   1982       68         9.0
1   1983       14         2.0
2   1984       38         3.0
3   1985       31         0.0
4   1986       17         0.0
5   1987       69         2.0
6   1988       26         2.0
7   1989       32         3.0
8   1990       79         7.0
9   1991       74         2.0
10  1992       91         4.0
11  1993       15         2.0
12  1994       30         7.0
13  1995       42         7.0
14  1996       63         5.0
15  1997       65         2.0
16  1998       36         3.0
17  1999       53        16.0
18  2000       88        13.0
19  2001        9         0.0
20  2002       56         0.0
21  2003       99         0.0
22  2004       37         2.0
23  2005      164         0.0
24  2006      109         7.0
25  2007      113        10.0
26  2008       96         1.0
27  2009       60         1.0
28  2010       70         6.0
29  2011       60         2.0
30  2012       27         0.0
31  2013      203        12.0
32  2014       76         1.0
33  2015       43         0.0
34  2016      134         0.0
35  2017      100         2.0
36  2018      118         7.0
37  2019      115        11.0
38  2020       99        14.0
39  2021       65         0.0
40  2022      121         0.0
41  2023      107        14.0
42  2024      110         0.0
43  2025       83         0.0

In [78]:
ri_bob.to_csv(
    "IMD_BoB_RI_training_base.csv",
    index=False
)

print("Corrected BoB RI dataset saved.")

Corrected BoB RI dataset saved.

In [79]:
from google.colab import files

files.download(
    "IMD_BoB_RI_training_base.csv"
)

In [82]:
ri_bob["forecast_horizon_hours"] = 24
ri_bob["ri_threshold_kt"] = 30

In [89]:
# ============================================================
# STEP 2: CHECK RI TARGET
# ============================================================

print("Dataset shape:", ri_bob.shape)

print("\nRI_24h distribution:")
print(ri_bob["RI_24h"].value_counts(dropna=False))

print("\nRI_24h percentages:")
print(
    ri_bob["RI_24h"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

print("\nMissing target:")
print(ri_bob["RI_24h"].isna().sum())

print("\nValid target rows:")
print(ri_bob["RI_24h"].notna().sum())

Dataset shape: (4991, 26)

RI_24h distribution:
RI_24h
0.0    3026
NaN    1786
1.0     179
Name: count, dtype: int64

RI_24h percentages:
RI_24h
0.0    60.63
NaN    35.78
1.0     3.59
Name: proportion, dtype: float64

Missing target:
1786

Valid target rows:
3205

In [90]:
# ============================================================
# STEP 3: REMOVE ROWS WITHOUT A KNOWN 24-HOUR TARGET
# ============================================================

ri_bob_model = ri_bob[
    ri_bob["RI_24h"].notna()
].copy()

print("Original rows:", len(ri_bob))
print("Rows with valid RI target:", len(ri_bob_model))

print("\nTarget distribution:")
print(ri_bob_model["RI_24h"].value_counts())

print("\nTarget percentages:")
print(
    ri_bob_model["RI_24h"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Original rows: 4991
Rows with valid RI target: 3205

Target distribution:
RI_24h
0.0    3026
1.0     179
Name: count, dtype: int64

Target percentages:
RI_24h
0.0    94.41
1.0     5.59
Name: proportion, dtype: float64

In [91]:
# ============================================================
# STEP 4: PHYSICAL RANGE CHECK
# ============================================================

print("Wind range:")
print(
    ri_bob_model["max_wind_kt"].min(),
    "to",
    ri_bob_model["max_wind_kt"].max(),
    "kt"
)

print("\nPressure range:")
print(
    ri_bob_model["central_pressure_hpa"].min(),
    "to",
    ri_bob_model["central_pressure_hpa"].max(),
    "hPa"
)

print("\nLatitude range:")
print(
    ri_bob_model["latitude"].min(),
    "to",
    ri_bob_model["latitude"].max()
)

print("\nLongitude range:")
print(
    ri_bob_model["longitude"].min(),
    "to",
    ri_bob_model["longitude"].max()
)

print("\nDelta V 24h range:")
print(
    ri_bob_model["delta_v_24h_kt"].min(),
    "to",
    ri_bob_model["delta_v_24h_kt"].max(),
    "kt"
)

Wind range:
20.0 to 130.0 kt

Pressure range:
920.0 to 1008.0 hPa

Latitude range:
2.7 to 26.2

Longitude range:
67.0 to 103.0

Delta V 24h range:
-97.0 to 80.0 kt

In [92]:
# ============================================================
# STEP 5: MISSING VALUE CHECK
# ============================================================

missing = (
    ri_bob_model.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_pct = (
    ri_bob_model.isna()
    .mean()
    .mul(100)
    .round(2)
)

missing_table = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})

display(missing_table)

                       missing_count  missing_percent
RI_24h                             0             0.00
basin                              0             0.00
central_pressure_hpa             231             7.21
datetime_utc                       0             0.00
delta_v_24h_kt                     0             0.00
delta_v_minus_12h_kt            1060            33.07
delta_v_minus_24h_kt            1250            39.00
delta_v_minus_6h_kt              791            24.68
grade                              9             0.28
latitude                           1             0.03
longitude                          6             0.19
max_wind_kt                        0             0.00
name                            1781            55.57
pressure_drop_hpa                147             4.59
step                               0             0.00
storm_id                           0             0.00
target_time_24h                    0             0.00
target_time_minus_12h              0             0.00
target_time_minus_24h              0             0.00
target_time_minus_6h               0             0.00
wind_24h_kt                        0             0.00
wind_6h_change                   240             7.49
wind_minus_12h_kt               1060            33.07
wind_minus_24h_kt               1250            39.00
wind_minus_6h_kt                 791            24.68
year                               0             0.00

In [93]:
# ============================================================
# STEP 6: INITIAL PREDICTOR SET
# ============================================================

feature_cols = [
    "latitude",
    "longitude",
    "max_wind_kt",
    "central_pressure_hpa",
    "pressure_drop_hpa",

    # Recent intensity history
    "wind_6h_change",
    "wind_minus_6h_kt",
    "delta_v_minus_6h_kt",

    "wind_minus_12h_kt",
    "delta_v_minus_12h_kt",

    "wind_minus_24h_kt",
    "delta_v_minus_24h_kt",
]

target_col = "RI_24h"

print("Features:")
for i, col in enumerate(feature_cols, 1):
    print(i, col)

print("\nTarget:", target_col)

Features:
1 latitude
2 longitude
3 max_wind_kt
4 central_pressure_hpa
5 pressure_drop_hpa
6 wind_6h_change
7 wind_minus_6h_kt
8 delta_v_minus_6h_kt
9 wind_minus_12h_kt
10 delta_v_minus_12h_kt
11 wind_minus_24h_kt
12 delta_v_minus_24h_kt

Target: RI_24h

In [95]:
# ============================================================
# STEP 8: CLEAN ML DATASET
# ============================================================

ml_df = ri_bob.copy()

# Keep only rows where the 24-hour outcome is known
ml_df = ml_df[ml_df["RI_24h"].notna()].copy()

print("Rows with valid RI target:", len(ml_df))

# Remove physically impossible central pressure values
bad_pressure = (
    (ml_df["central_pressure_hpa"] < 850) |
    (ml_df["central_pressure_hpa"] > 1050)
)

print("Physically suspicious pressure rows:", bad_pressure.sum())

ml_df = ml_df[~bad_pressure].copy()

print("Rows after pressure cleaning:", len(ml_df))

# Make sure datetime is datetime
ml_df["datetime_utc"] = pd.to_datetime(ml_df["datetime_utc"])

# Sort chronologically
ml_df = ml_df.sort_values(
    ["year", "storm_id", "datetime_utc"]
).reset_index(drop=True)

print("\nFinal ML dataset shape:", ml_df.shape)

Rows with valid RI target: 3205
Physically suspicious pressure rows: 0
Rows after pressure cleaning: 3205

Final ML dataset shape: (3205, 26)

In [97]:
# ============================================================
# STEP 10: RI EVENTS BY YEAR
# ============================================================

year_stats = (
    ml_df
    .groupby("year")["RI_24h"]
    .agg(
        samples="count",
        RI_events="sum"
    )
    .reset_index()
)

year_stats["RI_percent"] = (
    year_stats["RI_events"] /
    year_stats["samples"] *
    100
).round(2)

display(year_stats)

    year  samples  RI_events  RI_percent
0   1982       68        9.0       13.24
1   1983       14        2.0       14.29
2   1984       38        3.0        7.89
3   1985       31        0.0        0.00
4   1986       17        0.0        0.00
5   1987       69        2.0        2.90
6   1988       26        2.0        7.69
7   1989       32        3.0        9.38
8   1990       79        7.0        8.86
9   1991       74        2.0        2.70
10  1992       91        4.0        4.40
11  1993       15        2.0       13.33
12  1994       30        7.0       23.33
13  1995       42        7.0       16.67
14  1996       63        5.0        7.94
15  1997       65        2.0        3.08
16  1998       36        3.0        8.33
17  1999       53       16.0       30.19
18  2000       88       13.0       14.77
19  2001        9        0.0        0.00
20  2002       56        0.0        0.00
21  2003       99        0.0        0.00
22  2004       37        2.0        5.41
23  2005      164        0.0        0.00
24  2006      109        7.0        6.42
25  2007      113       10.0        8.85
26  2008       96        1.0        1.04
27  2009       60        1.0        1.67
28  2010       70        6.0        8.57
29  2011       60        2.0        3.33
30  2012       27        0.0        0.00
31  2013      203       12.0        5.91
32  2014       76        1.0        1.32
33  2015       43        0.0        0.00
34  2016      134        0.0        0.00
35  2017      100        2.0        2.00
36  2018      118        7.0        5.93
37  2019      115       11.0        9.57
38  2020       99       14.0       14.14
39  2021       65        0.0        0.00
40  2022      121        0.0        0.00
41  2023      107       14.0       13.08
42  2024      110        0.0        0.00
43  2025       83        0.0        0.00

In [100]:
# ============================================================
# STEP 13: CREATE MISSING-VALUE INDICATORS
# ============================================================

model_df = ml_df.copy()

for col in feature_cols:
    model_df[col + "_missing"] = model_df[col].isna().astype(int)

print("Original predictors:", len(feature_cols))
print("Missing indicators:", len(feature_cols))

all_model_features = (
    feature_cols +
    [col + "_missing" for col in feature_cols]
)

print("Total model inputs:", len(all_model_features))

Original predictors: 12
Missing indicators: 12
Total model inputs: 24

In [103]:
# ============================================================
# STEP 17: CHECK TARGET BALANCE IN EACH SPLIT
# ============================================================

for name, data in [
    ("TRAIN", train_df),
    ("VALIDATION", val_df),
    ("TEST", test_df)
]:

    print("\n" + "=" * 50)
    print(name)
    print("=" * 50)

    print(data["RI_24h"].value_counts())

    print(
        "\nRI percentage:",
        round(data["RI_24h"].mean() * 100, 2),
        "%"
    )

==================================================
TRAIN
==================================================
RI_24h
0.0    2469
1.0     151
Name: count, dtype: int64

RI percentage: 5.76 %

==================================================
VALIDATION
==================================================
RI_24h
0.0    271
1.0     14
Name: count, dtype: int64

RI percentage: 4.91 %

==================================================
TEST
==================================================
RI_24h
0.0    286
1.0     14
Name: count, dtype: int64

RI percentage: 4.67 %

In [112]:
# ============================================================
# STEP 24B: CHECK FOR STORM-LEVEL DATA LEAKAGE
# ============================================================

train_storms = set(train_df["storm_id"].unique())
val_storms = set(val_df["storm_id"].unique())
test_storms = set(test_df["storm_id"].unique())

print("Training storms:", len(train_storms))
print("Validation storms:", len(val_storms))
print("Test storms:", len(test_storms))

print("\nTrain ∩ Validation:",
      len(train_storms & val_storms))

print("Train ∩ Test:",
      len(train_storms & test_storms))

print("Validation ∩ Test:",
      len(val_storms & test_storms))

Training storms: 216
Validation storms: 21
Test storms: 21

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

In [115]:
# ============================================================
# STEP 26: THRESHOLD ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

def threshold_analysis(y_true, probabilities, model_name):

    thresholds = np.arange(0.05, 0.96, 0.05)

    results = []

    for threshold in thresholds:

        predictions = (
            probabilities >= threshold
        ).astype(int)

        tn, fp, fn, tp = confusion_matrix(
            y_true,
            predictions,
            labels=[0, 1]
        ).ravel()

        precision = precision_score(
            y_true,
            predictions,
            zero_division=0
        )

        recall = recall_score(
            y_true,
            predictions,
            zero_division=0
        )

        f1 = f1_score(
            y_true,
            predictions,
            zero_division=0
        )

        false_alarm_rate = fp / (fp + tn)

        results.append({
            "threshold": threshold,
            "TP": tp,
            "FP": fp,
            "FN": fn,
            "TN": tn,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "false_alarm_rate": false_alarm_rate
        })

    results_df = pd.DataFrame(results)

    print("\n" + "=" * 80)
    print(model_name)
    print("=" * 80)

    display(
        results_df.round(3)
    )

    print("\nBest threshold by F1:")

    best = results_df.loc[
        results_df["f1"].idxmax()
    ]

    display(
        best.to_frame().T.round(3)
    )

    return results_df


# ------------------------------------------------------------
# Logistic Regression
# ------------------------------------------------------------

lr_thresholds = threshold_analysis(
    y_test,
    y_test_prob,
    "LOGISTIC REGRESSION — TEST"
)


# ------------------------------------------------------------
# Random Forest
# ------------------------------------------------------------

rf_thresholds = threshold_analysis(
    y_test,
    rf_test_prob,
    "RANDOM FOREST — TEST"
)

================================================================================
LOGISTIC REGRESSION — TEST
================================================================================

    threshold  TP   FP  FN   TN  precision  recall     f1  false_alarm_rate
0        0.05  14  279   0    7      0.048   1.000  0.091             0.976
1        0.10  14  277   0    9      0.048   1.000  0.092             0.969
2        0.15  14  258   0   28      0.051   1.000  0.098             0.902
3        0.20  14  231   0   55      0.057   1.000  0.108             0.808
4        0.25  14  193   0   93      0.068   1.000  0.127             0.675
5        0.30  14  161   0  125      0.080   1.000  0.148             0.563
6        0.35  12  129   2  157      0.085   0.857  0.155             0.451
7        0.40  11   93   3  193      0.106   0.786  0.186             0.325
8        0.45  11   77   3  209      0.125   0.786  0.216             0.269
9        0.50  10   61   4  225      0.141   0.714  0.235             0.213
10       0.55  10   53   4  233      0.159   0.714  0.260             0.185
11       0.60  10   38   4  248      0.208   0.714  0.323             0.133
12       0.65   9   32   5  254      0.220   0.643  0.327             0.112
13       0.70   7   26   7  260      0.212   0.500  0.298             0.091
14       0.75   6   17   8  269      0.261   0.429  0.324             0.059
15       0.80   4   13  10  273      0.235   0.286  0.258             0.045
16       0.85   3   10  11  276      0.231   0.214  0.222             0.035
17       0.90   1    8  13  278      0.111   0.071  0.087             0.028
18       0.95   0    2  14  284      0.000   0.000  0.000             0.007

Best threshold by F1:

,threshold,TP,FP,FN,TN,precision,recall,f1,false_alarm_rate
12,0.65,9.0,32.0,5.0,254.0,0.22,0.643,0.327,0.112

================================================================================
RANDOM FOREST — TEST
================================================================================

    threshold  TP   FP  FN   TN  precision  recall     f1  false_alarm_rate
0        0.05  14  170   0  116      0.076   1.000  0.141             0.594
1        0.10  11   93   3  193      0.106   0.786  0.186             0.325
2        0.15  11   46   3  240      0.193   0.786  0.310             0.161
3        0.20  11   36   3  250      0.234   0.786  0.361             0.126
4        0.25   7   20   7  266      0.259   0.500  0.341             0.070
5        0.30   4   14  10  272      0.222   0.286  0.250             0.049
6        0.35   4   11  10  275      0.267   0.286  0.276             0.038
7        0.40   2    7  12  279      0.222   0.143  0.174             0.024
8        0.45   1    5  13  281      0.167   0.071  0.100             0.017
9        0.50   1    3  13  283      0.250   0.071  0.111             0.010
10       0.55   0    2  14  284      0.000   0.000  0.000             0.007
11       0.60   0    2  14  284      0.000   0.000  0.000             0.007
12       0.65   0    0  14  286      0.000   0.000  0.000             0.000
13       0.70   0    0  14  286      0.000   0.000  0.000             0.000
14       0.75   0    0  14  286      0.000   0.000  0.000             0.000
15       0.80   0    0  14  286      0.000   0.000  0.000             0.000
16       0.85   0    0  14  286      0.000   0.000  0.000             0.000
17       0.90   0    0  14  286      0.000   0.000  0.000             0.000
18       0.95   0    0  14  286      0.000   0.000  0.000             0.000

Best threshold by F1:

,threshold,TP,FP,FN,TN,precision,recall,f1,false_alarm_rate
3,0.2,11.0,36.0,3.0,250.0,0.234,0.786,0.361,0.126

In [117]:
# ============================================================
# STEP 28 — FINAL TEST EVALUATION
# LOCKED VALIDATION THRESHOLD
# ============================================================

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score
)

# ------------------------------------------------------------
# LOCKED THRESHOLD
# ------------------------------------------------------------

FINAL_THRESHOLD = 0.75

y_test_pred_final = (
    y_test_prob >= FINAL_THRESHOLD
).astype(int)


# ------------------------------------------------------------
# METRICS
# ------------------------------------------------------------

tn, fp, fn, tp = confusion_matrix(
    y_test,
    y_test_pred_final,
    labels=[0, 1]
).ravel()

precision = precision_score(
    y_test,
    y_test_pred_final,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_test_pred_final,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_test_pred_final,
    zero_division=0
)

far = fp / (fp + tn)

roc_auc = roc_auc_score(
    y_test,
    y_test_prob
)

pr_auc = average_precision_score(
    y_test,
    y_test_prob
)


# ------------------------------------------------------------
# PRINT
# ------------------------------------------------------------

print("=" * 70)
print("FINAL LOGISTIC REGRESSION — TEST")
print("=" * 70)

print(f"Locked threshold: {FINAL_THRESHOLD}")

print(f"\nROC-AUC: {roc_auc:.4f}")
print(f"PR-AUC:  {pr_auc:.4f}")

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_test_pred_final
    )
)

print("\nTP:", tp)
print("FP:", fp)
print("FN:", fn)
print("TN:", tn)

print(f"\nPrecision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1:        {f1:.4f}")
print(f"False Alarm Rate: {far:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_test_pred_final,
        digits=4,
        zero_division=0
    )
)

======================================================================
FINAL LOGISTIC REGRESSION — TEST
======================================================================
Locked threshold: 0.75

ROC-AUC: 0.8319
PR-AUC:  0.1951

Confusion Matrix:
[[269  17]
 [  8   6]]

TP: 6
FP: 17
FN: 8
TN: 269

Precision: 0.2609
Recall:    0.4286
F1:        0.3243
False Alarm Rate: 0.0594

Classification Report:
              precision    recall  f1-score   support

           0     0.9711    0.9406    0.9556       286
           1     0.2609    0.4286    0.3243        14

    accuracy                         0.9167       300
   macro avg     0.6160    0.6846    0.6400       300
weighted avg     0.9380    0.9167    0.9261       300

In [119]:
import cdsapi

print("cdsapi installed successfully")

cdsapi installed successfully

In [121]:
import cdsapi
import getpass

api_key = getpass.getpass("Paste your CDS API key: ")

client = cdsapi.Client(
    url="https://cds.climate.copernicus.eu/api",
    key=api_key
)

print("CDS client created successfully!")

Paste your CDS API key: ··········
CDS client created successfully!

In [123]:
test_file = "era5_test.grib"

client.retrieve(
    "reanalysis-era5-pressure-levels",
    {
        "product_type": ["reanalysis"],
        "variable": ["relative_humidity"],
        "year": ["2020"],
        "month": ["05"],
        "day": ["17"],
        "time": ["03:00"],
        "pressure_level": ["850"],
        "data_format": "grib",
    },
    test_file
)

print("Download complete!")
print("File exists:", os.path.exists(test_file))
print("File size:", os.path.getsize(test_file) / 1024, "KB")

2026-08-30 08:44:51,875 INFO Request ID is bc98fc80-9941-436f-81c2-fe09a805c498
INFO:ecmwf.datastores.legacy_client:Request ID is bc98fc80-9941-436f-81c2-fe09a805c498
2026-08-30 08:44:52,132 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 08:45:14,397 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 08:45:26,018 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f608e3e91e6747a58b7af733c7c751a9.grib:   0%|          | 0.00/1.98M [00:00<?, ?B/s]

Download complete!
File exists: True
File size: 2027.91796875 KB

In [126]:
print(ri_bob.shape)
print(ri_bob.columns.tolist())

print("\nYears:")
print(ri_bob["year"].min(), "to", ri_bob["year"].max())

print("\nUnique storms:")
print(ri_bob["storm_id"].nunique())

print("\nRI distribution:")
print(ri_bob["RI_24h"].value_counts(dropna=False))

(4991, 26)
['storm_id', 'year', 'basin', 'name', 'datetime_utc', 'latitude', 'longitude', 'max_wind_kt', 'central_pressure_hpa', 'pressure_drop_hpa', 'grade', 'step', 'target_time_24h', 'wind_24h_kt', 'delta_v_24h_kt', 'RI_24h', 'wind_6h_change', 'target_time_minus_6h', 'wind_minus_6h_kt', 'delta_v_minus_6h_kt', 'target_time_minus_12h', 'wind_minus_12h_kt', 'delta_v_minus_12h_kt', 'target_time_minus_24h', 'wind_minus_24h_kt', 'delta_v_minus_24h_kt']

Years:
1982 to 2025

Unique storms:
290

RI distribution:
RI_24h
0.0    3026
NaN    1786
1.0     179
Name: count, dtype: int64

In [128]:
# ============================================================
# STEP 1 — PREPARE VALID RI ROWS FOR ERA5 EXTRACTION
# ============================================================

import pandas as pd
import numpy as np

# Keep ONLY rows with a known RI target
ri_valid = ri_bob[
    ri_bob["RI_24h"].notna()
].copy()

# Make sure datetime is actually datetime
ri_valid["datetime_utc"] = pd.to_datetime(
    ri_valid["datetime_utc"]
)

# Sort properly
ri_valid = ri_valid.sort_values(
    ["storm_id", "datetime_utc"]
).reset_index(drop=True)

print("=" * 60)
print("ERA5 EXTRACTION DATASET")
print("=" * 60)

print("Rows:", len(ri_valid))
print("Unique storms:", ri_valid["storm_id"].nunique())

print("\nRI distribution:")
print(ri_valid["RI_24h"].value_counts())

print("\nRI percentage:")
print(
    ri_valid["RI_24h"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nDate range:")
print(ri_valid["datetime_utc"].min())
print(ri_valid["datetime_utc"].max())

============================================================
ERA5 EXTRACTION DATASET
============================================================
Rows: 3205
Unique storms: 258

RI distribution:
RI_24h
0.0    3026
1.0     179
Name: count, dtype: int64

RI percentage:
RI_24h
0.0    94.41
1.0     5.59
Name: proportion, dtype: float64

Date range:
1982-05-01 03:00:00
2025-12-01 18:00:00

In [130]:
# Number of unique calendar days
unique_days = (
    ri_valid["datetime_utc"]
    .dt.floor("D")
    .nunique()
)

print("\nUnique calendar days:", unique_days)

Unique calendar days: 794

In [131]:
ri_valid["era5_longitude"] = (
    ri_valid["longitude"] % 360
)

print(
    ri_valid[
        ["storm_id", "datetime_utc",
         "latitude", "longitude",
         "era5_longitude", "RI_24h"]
    ].head(10)
)

   storm_id        datetime_utc  latitude  longitude  era5_longitude  RI_24h
0  1982-001 1982-05-01 03:00:00      14.0       82.5            82.5     0.0
1  1982-001 1982-05-01 06:00:00      14.5       82.5            82.5     0.0
2  1982-001 1982-05-01 12:00:00      15.0       82.0            82.0     0.0
3  1982-001 1982-05-01 18:00:00      15.5       82.5            82.5     0.0
4  1982-001 1982-05-02 00:00:00      16.0       83.0            83.0     0.0
5  1982-001 1982-05-02 03:00:00      16.5       83.5            83.5     0.0
6  1982-001 1982-05-02 06:00:00      16.5       84.0            84.0     1.0
7  1982-001 1982-05-02 12:00:00      16.5       84.5            84.5     1.0
8  1982-001 1982-05-02 18:00:00      17.0       85.0            85.0     1.0
9  1982-001 1982-05-03 00:00:00      17.0       86.0            86.0     1.0

In [135]:
import xarray as xr

ds_pilot = xr.open_dataset(
    "ERA5_pilot_1982_001.grib",
    engine="cfgrib",
    backend_kwargs={"indexpath": ""}
)

print(ds_pilot)
print("\nVariables:")
print(list(ds_pilot.data_vars))

print("\nPressure levels:")
print(ds_pilot.isobaricInhPa.values)

print("\nTimes:")
print(ds_pilot.time.values[:10])

<xarray.Dataset> Size: 8MB
Dimensions:        (time: 72, isobaricInhPa: 4, latitude: 33, longitude: 37)
Coordinates:
  * time           (time) datetime64[ns] 576B 1982-05-01 ... 1982-05-03T23:00:00
  * isobaricInhPa  (isobaricInhPa) float64 32B 850.0 700.0 500.0 200.0
  * latitude       (latitude) float64 264B 20.0 19.75 19.5 ... 12.5 12.25 12.0
  * longitude      (longitude) float64 296B 80.0 80.25 80.5 ... 88.5 88.75 89.0
    number         int64 8B ...
    step           timedelta64[ns] 8B ...
    valid_time     (time) datetime64[ns] 576B ...
Data variables:
    vo             (time, isobaricInhPa, latitude, longitude) float32 1MB ...
    d              (time, isobaricInhPa, latitude, longitude) float32 1MB ...
    u              (time, isobaricInhPa, latitude, longitude) float32 1MB ...
    v              (time, isobaricInhPa, latitude, longitude) float32 1MB ...
    r              (time, isobaricInhPa, latitude, longitude) float32 1MB ...
    t              (time, isobaricInhPa, latitude, longitude) float32 1MB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-08-30T08:53 GRIB to CDM+CF via cfgrib-0.9.1...

Variables:
['vo', 'd', 'u', 'v', 'r', 't']

Pressure levels:
[850. 700. 500. 200.]

Times:
['1982-05-01T00:00:00.000000000' '1982-05-01T01:00:00.000000000'
 '1982-05-01T02:00:00.000000000' '1982-05-01T03:00:00.000000000'
 '1982-05-01T04:00:00.000000000' '1982-05-01T05:00:00.000000000'
 '1982-05-01T06:00:00.000000000' '1982-05-01T07:00:00.000000000'
 '1982-05-01T08:00:00.000000000' '1982-05-01T09:00:00.000000000']

In [141]:
import pandas as pd
import numpy as np

# ============================================================
# LOAD RI DATASET
# ============================================================

ri_df = pd.read_csv(
    "IMD_BoB_RI_training_base-2.csv",
    parse_dates=[
        "datetime_utc",
        "target_time_24h",
        "target_time_minus_6h",
        "target_time_minus_12h",
        "target_time_minus_24h"
    ]
)

# Keep only rows with a valid RI target
ri_valid = ri_df.dropna(subset=["RI_24h"]).copy()

# Make sure target is integer
ri_valid["RI_24h"] = ri_valid["RI_24h"].astype(int)

print("=" * 60)
print("VALID RI DATASET")
print("=" * 60)

print("Shape:", ri_valid.shape)
print("Unique storms:", ri_valid["storm_id"].nunique())

print("\nRI distribution:")
print(ri_valid["RI_24h"].value_counts())

print("\nRI percentage:")
print(
    ri_valid["RI_24h"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nDate range:")
print(ri_valid["datetime_utc"].min())
print(ri_valid["datetime_utc"].max())

============================================================
VALID RI DATASET
============================================================
Shape: (3205, 26)
Unique storms: 258

RI distribution:
RI_24h
0    3026
1     179
Name: count, dtype: int64

RI percentage:
RI_24h
0    94.41
1     5.59
Name: proportion, dtype: float64

Date range:
1982-05-01 03:00:00
2025-12-01 18:00:00

In [145]:
def extract_era5_point(ds, row):

    point = ds.sel(
        time=np.datetime64(row["datetime_utc"]),
        latitude=row["latitude"],
        longitude=row["longitude"],
        method="nearest"
    )

    result = {
        "storm_id": row["storm_id"],
        "datetime_utc": row["datetime_utc"],
        "latitude": row["latitude"],
        "longitude": row["longitude"],
        "RI_24h": row["RI_24h"],

        # 850 hPa
        "vo_850": float(
            point["vo"].sel(isobaricInhPa=850).values
        ),
        "d_850": float(
            point["d"].sel(isobaricInhPa=850).values
        ),
        "u_850": float(
            point["u"].sel(isobaricInhPa=850).values
        ),
        "v_850": float(
            point["v"].sel(isobaricInhPa=850).values
        ),
        "rh_850": float(
            point["r"].sel(isobaricInhPa=850).values
        ),
        "t_850": float(
            point["t"].sel(isobaricInhPa=850).values
        ),

        # 700 hPa
        "vo_700": float(
            point["vo"].sel(isobaricInhPa=700).values
        ),
        "d_700": float(
            point["d"].sel(isobaricInhPa=700).values
        ),
        "rh_700": float(
            point["r"].sel(isobaricInhPa=700).values
        ),
        "t_700": float(
            point["t"].sel(isobaricInhPa=700).values
        ),

        # 500 hPa
        "vo_500": float(
            point["vo"].sel(isobaricInhPa=500).values
        ),
        "d_500": float(
            point["d"].sel(isobaricInhPa=500).values
        ),
        "rh_500": float(
            point["r"].sel(isobaricInhPa=500).values
        ),
        "t_500": float(
            point["t"].sel(isobaricInhPa=500).values
        ),

        # 200 hPa
        "vo_200": float(
            point["vo"].sel(isobaricInhPa=200).values
        ),
        "d_200": float(
            point["d"].sel(isobaricInhPa=200).values
        ),
        "u_200": float(
            point["u"].sel(isobaricInhPa=200).values
        ),
        "v_200": float(
            point["v"].sel(isobaricInhPa=200).values
        ),
    }

    return result

In [146]:
era5_features = pd.DataFrame(
    [
        extract_era5_point(ds, row)
        for _, row in pilot_points.iterrows()
    ]
)

print("=" * 60)
print("ERA5 PILOT FEATURES")
print("=" * 60)

print("Shape:", era5_features.shape)

display(era5_features)

============================================================
ERA5 PILOT FEATURES
============================================================
Shape: (14, 23)

,storm_id,datetime_utc,latitude,longitude,RI_24h,vo_850,d_850,u_850,v_850,rh_850,...,rh_700,t_700,vo_500,d_500,rh_500,t_500,vo_200,d_200,u_200,v_200
0,1982-001,1982-05-01 03:00:00,14.0,82.5,0,0.000082,-4.079193e-07,-0.333221,2.756058,80.231781,...,65.478195,282.640198,0.000113,-0.000024,84.298286,268.002991,0.000028,-0.000043,-4.276566,8.924133
1,1982-001,1982-05-01 06:00:00,14.5,82.5,0,0.000078,-1.272652e-05,-1.734726,2.606705,93.119141,...,72.028610,281.836121,0.000210,-0.000050,99.798660,267.923767,0.000017,0.000132,-3.117004,7.907318
2,1982-001,1982-05-01 12:00:00,15.0,82.0,0,0.000104,4.061800e-05,-4.161774,-1.988754,59.162445,...,68.244553,281.967285,0.000064,-0.000027,61.855255,268.983276,0.000058,-0.000054,-0.488846,8.184021
3,1982-001,1982-05-01 18:00:00,15.5,82.5,0,0.000180,-3.664079e-05,-1.106979,-3.612183,87.167816,...,77.476120,281.999268,0.000253,-0.000011,95.300842,269.200867,0.000022,0.000034,2.326035,5.994690
4,1982-001,1982-05-02 00:00:00,16.0,83.0,0,0.000225,-6.458722e-07,-2.156296,-6.790405,95.531540,...,72.458099,283.066162,0.000086,0.000009,94.426819,268.662781,-0.000022,-0.000023,-4.064621,8.522324
5,1982-001,1982-05-02 03:00:00,16.5,83.5,0,0.000128,-4.584435e-07,-8.296600,-4.813797,98.012634,...,72.353134,282.048401,0.000119,0.000034,101.575409,268.550171,0.000166,-0.000014,0.042999,9.489502
6,1982-001,1982-05-02 06:00:00,16.5,84.0,1,0.000230,-5.737506e-05,-8.812180,-2.857956,91.762848,...,88.687119,281.843750,0.000156,0.000035,98.843582,269.489136,-0.000009,0.000016,3.550461,10.740570
7,1982-001,1982-05-02 12:00:00,16.5,84.5,1,0.000265,1.771469e-05,-4.189240,-2.636887,91.429718,...,80.012360,282.796143,0.000128,-0.000021,96.712433,269.904907,-0.000033,0.000041,2.788330,4.675415
8,1982-001,1982-05-02 18:00:00,17.0,85.0,1,0.000336,2.704188e-05,-2.332855,-1.115677,90.875656,...,75.709152,283.211609,0.000400,0.000016,92.612366,270.679321,0.000027,0.000058,-0.430466,0.619186
9,1982-001,1982-05-03 00:00:00,17.0,86.0,1,0.000355,-2.999371e-05,5.805084,0.331894,94.641983,...,80.752930,282.467957,0.000456,0.000060,78.044899,269.583618,0.000003,0.000059,-2.435547,1.183151
10,1982-001,1982-05-03 03:00:00,17.0,86.5,1,0.000446,7.835682e-06,9.983505,-0.675400,90.156784,...,83.097458,282.161133,0.000383,0.000045,98.814354,269.637451,0.000060,-0.000046,-0.610687,7.898895
11,1982-001,1982-05-03 06:00:00,17.5,87.5,1,0.000380,-4.724762e-05,-3.139709,11.423203,91.278488,...,76.472488,282.144653,0.000261,0.000106,98.727615,269.522034,0.000124,-0.000133,1.305588,4.465286
12,1982-001,1982-05-03 12:00:00,17.5,88.5,0,0.000544,-3.938307e-05,1.999512,9.931137,96.454483,...,82.452682,282.673157,0.000520,0.000058,99.848503,270.227905,0.000309,0.000003,7.034470,4.171036
13,1982-001,1982-05-03 18:00:00,17.5,90.0,0,0.000362,6.520888e-06,8.048553,-10.259476,79.478165,...,70.456985,283.503906,0.000300,0.000021,76.675056,271.531372,0.000050,0.000126,0.486328,-8.108444

In [147]:
# ============================================================
# STEP 1 — PREPARE STORM OBSERVATIONS FOR FULL ERA5 EXTRACTION
# ============================================================

import pandas as pd
import numpy as np
import os
from collections import defaultdict

# ------------------------------------------------------------
# Load IMD RI dataset
# ------------------------------------------------------------

input_file = "IMD_BoB_RI_training_base-2.csv"

df = pd.read_csv(input_file, parse_dates=["datetime_utc"])

print("=" * 70)
print("IMD DATASET LOADED")
print("=" * 70)

print("Shape:", df.shape)

# Keep only observations with a valid RI target
df_era5 = df[df["RI_24h"].notna()].copy()

# Make sure datetime is datetime
df_era5["datetime_utc"] = pd.to_datetime(
    df_era5["datetime_utc"],
    errors="coerce"
)

# Remove rows with invalid coordinates/time
df_era5 = df_era5.dropna(
    subset=["datetime_utc", "latitude", "longitude"]
).copy()

# ERA5 longitude convention = 0 to 360
df_era5["era5_longitude"] = df_era5["longitude"] % 360

# Calendar date
df_era5["date"] = df_era5["datetime_utc"].dt.strftime("%Y-%m-%d")

# Hour
df_era5["hour"] = df_era5["datetime_utc"].dt.hour

print("\nValid RI observations:", len(df_era5))
print("Unique storms:", df_era5["storm_id"].nunique())
print("Unique dates:", df_era5["date"].nunique())

print("\nRI distribution:")
print(df_era5["RI_24h"].value_counts())

print("\nDate range:")
print(df_era5["datetime_utc"].min())
print(df_era5["datetime_utc"].max())

print("\nRequired ERA5 hours:")
print(sorted(df_era5["hour"].unique()))

print("\nLatitude range:")
print(df_era5["latitude"].min(), "to", df_era5["latitude"].max())

print("\nLongitude range:")
print(df_era5["longitude"].min(), "to", df_era5["longitude"].max())

# ------------------------------------------------------------
# Save prepared observation table
# ------------------------------------------------------------

df_era5.to_csv(
    "IMD_ERA5_observations_ready.csv",
    index=False
)

print("\nSaved:")
print("IMD_ERA5_observations_ready.csv")

======================================================================
IMD DATASET LOADED
======================================================================
Shape: (4991, 26)

Valid RI observations: 3198
Unique storms: 258
Unique dates: 793

RI distribution:
RI_24h
0.0    3019
1.0     179
Name: count, dtype: int64

Date range:
1982-05-01 03:00:00
2025-12-01 18:00:00

Required ERA5 hours:
[np.int32(0), np.int32(3), np.int32(6), np.int32(9), np.int32(12), np.int32(15), np.int32(18), np.int32(21)]

Latitude range:
2.7 to 26.2

Longitude range:
67.0 to 103.0

Saved:
IMD_ERA5_observations_ready.csv

In [149]:
# ============================================================
# FIXED ERA5 DOWNLOADER
# ONE CALENDAR DAY PER REQUEST
# ============================================================

import pandas as pd
import numpy as np
import os
import time

# ------------------------------------------------------------
# Load IMD observations
# ------------------------------------------------------------

obs = pd.read_csv(
    "IMD_ERA5_observations_ready.csv",
    parse_dates=["datetime_utc"]
)

obs = obs[obs["RI_24h"].notna()].copy()

# Required calendar dates
required_dates = sorted(
    obs["datetime_utc"]
    .dt.strftime("%Y-%m-%d")
    .unique()
)

print("=" * 70)
print("FIXED ERA5 DOWNLOAD")
print("=" * 70)

print("Valid observations:", len(obs))
print("Unique storms:", obs["storm_id"].nunique())
print("Required calendar dates:", len(required_dates))
print("First:", required_dates[0])
print("Last:", required_dates[-1])

# ------------------------------------------------------------
# ERA5 variables
#
# IMPORTANT:
# Do NOT include "relative_vorticity".
# It was causing the duplicate parameter 157 error.
# ------------------------------------------------------------

VARIABLES = [
    "divergence",
    "relative_humidity",
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind"
]

PRESSURE_LEVELS = [
    "850",
    "700",
    "500",
    "200"
]

TIMES = [
    "00:00",
    "03:00",
    "06:00",
    "09:00",
    "12:00",
    "15:00",
    "18:00",
    "21:00"
]

# ------------------------------------------------------------
# Download region
#
# north, west, south, east
# ------------------------------------------------------------

AREA = [30, 65, 0, 105]

# ------------------------------------------------------------
# Output directory
# ------------------------------------------------------------

DOWNLOAD_DIR = "ERA5_chunks_fixed"

os.makedirs(DOWNLOAD_DIR, exist_ok=True)

successful = 0
failed = []

# ------------------------------------------------------------
# DOWNLOAD ONE CALENDAR DAY AT A TIME
# ------------------------------------------------------------

for i, date in enumerate(required_dates):

    output_file = os.path.join(
        DOWNLOAD_DIR,
        f"ERA5_{date}.grib"
    )

    print("\n" + "=" * 70)
    print(f"DAY {i + 1}/{len(required_dates)}")
    print("=" * 70)

    print("Date:", date)
    print("Output:", output_file)

    # --------------------------------------------------------
    # Skip existing files
    # --------------------------------------------------------

    if os.path.exists(output_file):

        size_mb = os.path.getsize(output_file) / (1024 ** 2)

        print("Already downloaded.")
        print(f"Size: {size_mb:.2f} MB")

        successful += 1
        continue

    request = {
        "product_type": ["reanalysis"],

        "variable": VARIABLES,

        "pressure_level": PRESSURE_LEVELS,

        "year": [date[:4]],

        "month": [date[5:7]],

        "day": [date[8:10]],

        "time": TIMES,

        "area": AREA,

        "data_format": "grib"
    }

    try:

        print("Submitting request...")

        client.retrieve(
            "reanalysis-era5-pressure-levels",
            request,
            output_file
        )

        if os.path.exists(output_file):

            size_mb = os.path.getsize(output_file) / (1024 ** 2)

            print("SUCCESS")
            print(f"Size: {size_mb:.2f} MB")

            successful += 1

        else:

            print("ERROR: output file missing")
            failed.append(date)

    except Exception as e:

        print("FAILED")
        print("Date:", date)
        print("Error:", str(e))

        failed.append(date)

    # Don't hammer CDS
    time.sleep(2)


# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n")
print("=" * 70)
print("DOWNLOAD SUMMARY")
print("=" * 70)

print("Required dates:", len(required_dates))
print("Successful:", successful)
print("Failed:", len(failed))

if failed:

    print("\nFailed dates:")
    print(failed[:30])

    if len(failed) > 30:
        print("... and", len(failed) - 30, "more")

else:

    print("\nALL REQUIRED ERA5 DAYS DOWNLOADED!")

======================================================================
FIXED ERA5 DOWNLOAD
======================================================================
Valid observations: 3198
Unique storms: 258
Required calendar dates: 793
First: 1982-05-01
Last: 2025-12-01

======================================================================
DAY 1/793
======================================================================
Date: 1982-05-01
Output: ERA5_chunks_fixed/ERA5_1982-05-01.grib
Submitting request...

2026-08-30 09:00:01,337 INFO Request ID is 51f5d49f-0ce5-42a8-9290-0fa63fbf1916
INFO:ecmwf.datastores.legacy_client:Request ID is 51f5d49f-0ce5-42a8-9290-0fa63fbf1916
2026-08-30 09:00:01,587 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:00:37,243 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

de26781842a89087b46bb7d825f0d9fb.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 2/793
======================================================================
Date: 1982-05-02
Output: ERA5_chunks_fixed/ERA5_1982-05-02.grib
Submitting request...

2026-08-30 09:00:45,008 INFO Request ID is ef742a05-3b55-4561-a82a-15b806145ae4
INFO:ecmwf.datastores.legacy_client:Request ID is ef742a05-3b55-4561-a82a-15b806145ae4
2026-08-30 09:00:47,026 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:01:28,927 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:02:12,525 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a1368692cde8fad8849a1f6ad151405c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 3/793
======================================================================
Date: 1982-05-03
Output: ERA5_chunks_fixed/ERA5_1982-05-03.grib
Submitting request...

2026-08-30 09:02:19,002 INFO Request ID is b5268f6e-caf9-4f45-8eed-c889d5433fd3
INFO:ecmwf.datastores.legacy_client:Request ID is b5268f6e-caf9-4f45-8eed-c889d5433fd3
2026-08-30 09:02:20,214 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:02:42,431 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:03:11,557 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c97145c6b922f8064553a36f895dc669.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 4/793
======================================================================
Date: 1982-05-04
Output: ERA5_chunks_fixed/ERA5_1982-05-04.grib
Submitting request...

2026-08-30 09:03:17,887 INFO Request ID is 7ca614af-190f-4ac2-b75a-00a38b400ca6
INFO:ecmwf.datastores.legacy_client:Request ID is 7ca614af-190f-4ac2-b75a-00a38b400ca6
2026-08-30 09:03:18,126 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:03:53,749 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:04:11,117 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e8f269a4c057e103c5723fe562fcb93b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 5/793
======================================================================
Date: 1982-05-31
Output: ERA5_chunks_fixed/ERA5_1982-05-31.grib
Submitting request...

2026-08-30 09:04:17,667 INFO Request ID is 50304e54-170b-4db2-9b95-b1702672e0b5
INFO:ecmwf.datastores.legacy_client:Request ID is 50304e54-170b-4db2-9b95-b1702672e0b5
2026-08-30 09:04:18,211 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:04:53,299 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:05:37,031 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2626d2a6968e2fb504968d90f27f4122.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 6/793
======================================================================
Date: 1982-06-01
Output: ERA5_chunks_fixed/ERA5_1982-06-01.grib
Submitting request...

2026-08-30 09:05:43,599 INFO Request ID is b77777b6-711f-49e0-8189-8892a7145488
INFO:ecmwf.datastores.legacy_client:Request ID is b77777b6-711f-49e0-8189-8892a7145488
2026-08-30 09:05:43,960 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:06:18,181 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:07:02,365 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a21dc35aeb58ab429fffceaf2d3d69f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 7/793
======================================================================
Date: 1982-06-02
Output: ERA5_chunks_fixed/ERA5_1982-06-02.grib
Submitting request...

2026-08-30 09:07:08,757 INFO Request ID is 6568980c-a9b0-436d-9269-825aa9cbab1d
INFO:ecmwf.datastores.legacy_client:Request ID is 6568980c-a9b0-436d-9269-825aa9cbab1d
2026-08-30 09:07:09,002 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:07:43,497 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:08:26,959 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d4a6a3c5b340e0d6f3bd821a022abb77.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 8/793
======================================================================
Date: 1982-06-03
Output: ERA5_chunks_fixed/ERA5_1982-06-03.grib
Submitting request...

2026-08-30 09:08:34,722 INFO Request ID is 372f847f-6812-4b49-a852-6e7c7385c64e
INFO:ecmwf.datastores.legacy_client:Request ID is 372f847f-6812-4b49-a852-6e7c7385c64e
2026-08-30 09:08:34,946 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:09:26,108 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c7fa5bf567da735714a731f2c5f74c0d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 9/793
======================================================================
Date: 1982-06-04
Output: ERA5_chunks_fixed/ERA5_1982-06-04.grib
Submitting request...

2026-08-30 09:09:34,515 INFO Request ID is e888c143-f702-41ec-b4db-f3b889ecb6ef
INFO:ecmwf.datastores.legacy_client:Request ID is e888c143-f702-41ec-b4db-f3b889ecb6ef
2026-08-30 09:09:34,753 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:10:08,869 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:10:26,199 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fd2c3d61a9f8a65e45dc2899a8706bb.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 10/793
======================================================================
Date: 1982-07-18
Output: ERA5_chunks_fixed/ERA5_1982-07-18.grib
Submitting request...

2026-08-30 09:10:32,592 INFO Request ID is fc4e185d-6000-4298-819e-d94b6c2a37e1
INFO:ecmwf.datastores.legacy_client:Request ID is fc4e185d-6000-4298-819e-d94b6c2a37e1
2026-08-30 09:10:32,826 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:11:06,846 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:11:24,190 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e0c5539f02006c6cd51f08ff8ff162ee.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 11/793
======================================================================
Date: 1982-07-19
Output: ERA5_chunks_fixed/ERA5_1982-07-19.grib
Submitting request...

2026-08-30 09:11:33,217 INFO Request ID is 59287cf6-3f66-4570-8810-7eae0eb20f36
INFO:ecmwf.datastores.legacy_client:Request ID is 59287cf6-3f66-4570-8810-7eae0eb20f36
2026-08-30 09:11:33,456 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:12:09,819 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

95a37a66a873590d69bf86431dea0967.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 12/793
======================================================================
Date: 1982-08-18
Output: ERA5_chunks_fixed/ERA5_1982-08-18.grib
Submitting request...

2026-08-30 09:12:16,502 INFO Request ID is 18799d3b-c012-4a37-bcf6-77c847ad8b31
INFO:ecmwf.datastores.legacy_client:Request ID is 18799d3b-c012-4a37-bcf6-77c847ad8b31
2026-08-30 09:12:16,754 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:12:50,964 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:13:08,287 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c3913a92b455a82321c6db7c53aeaa03.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 13/793
======================================================================
Date: 1982-08-27
Output: ERA5_chunks_fixed/ERA5_1982-08-27.grib
Submitting request...

2026-08-30 09:13:14,929 INFO Request ID is ef73085e-ae46-40a3-bc40-03c49def0f57
INFO:ecmwf.datastores.legacy_client:Request ID is ef73085e-ae46-40a3-bc40-03c49def0f57
2026-08-30 09:13:16,164 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:13:38,495 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

96c49724f49ee31dd6157898385cbb3d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 14/793
======================================================================
Date: 1982-08-28
Output: ERA5_chunks_fixed/ERA5_1982-08-28.grib
Submitting request...

2026-08-30 09:13:46,858 INFO Request ID is 3cef27c9-55b3-47b6-a7c3-b322961f50d9
INFO:ecmwf.datastores.legacy_client:Request ID is 3cef27c9-55b3-47b6-a7c3-b322961f50d9
2026-08-30 09:13:47,139 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:14:01,888 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:14:21,352 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

93076d47ecec259534122143ab2ed66e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 15/793
======================================================================
Date: 1982-08-29
Output: ERA5_chunks_fixed/ERA5_1982-08-29.grib
Submitting request...

2026-08-30 09:14:27,960 INFO Request ID is e548c2f9-5d87-485e-a8e5-f64e662566ca
INFO:ecmwf.datastores.legacy_client:Request ID is e548c2f9-5d87-485e-a8e5-f64e662566ca
2026-08-30 09:14:28,187 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:14:43,218 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:15:02,689 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4f59300d77c7ca5f0f0232ba4f3fe1b2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 16/793
======================================================================
Date: 1982-08-30
Output: ERA5_chunks_fixed/ERA5_1982-08-30.grib
Submitting request...

2026-08-30 09:15:08,742 INFO Request ID is ef48c50c-a0ef-48df-a7be-e9e9f1f1a1a3
INFO:ecmwf.datastores.legacy_client:Request ID is ef48c50c-a0ef-48df-a7be-e9e9f1f1a1a3
2026-08-30 09:15:08,973 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:15:48,630 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:16:05,977 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b72ebf6c192db33a6c71a6fd1bacce9d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 17/793
======================================================================
Date: 1982-08-31
Output: ERA5_chunks_fixed/ERA5_1982-08-31.grib
Submitting request...

2026-08-30 09:16:12,181 INFO Request ID is 5ca7a371-1aa6-474f-9819-e7d98ba50cf4
INFO:ecmwf.datastores.legacy_client:Request ID is 5ca7a371-1aa6-474f-9819-e7d98ba50cf4
2026-08-30 09:16:12,428 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:16:37,156 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:17:06,145 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6c9e0ce7109725735ad3be0353b15bd6.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 18/793
======================================================================
Date: 1982-09-01
Output: ERA5_chunks_fixed/ERA5_1982-09-01.grib
Submitting request...

2026-08-30 09:17:14,558 INFO Request ID is 69ef3c80-6c8b-4f35-a038-678e620671cc
INFO:ecmwf.datastores.legacy_client:Request ID is 69ef3c80-6c8b-4f35-a038-678e620671cc
2026-08-30 09:17:15,113 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:17:37,343 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:18:06,305 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c670571558142a516aa3fa753cb17415.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 19/793
======================================================================
Date: 1982-09-09
Output: ERA5_chunks_fixed/ERA5_1982-09-09.grib
Submitting request...

2026-08-30 09:18:12,789 INFO Request ID is 1757602e-f133-49e3-99be-793847570c07
INFO:ecmwf.datastores.legacy_client:Request ID is 1757602e-f133-49e3-99be-793847570c07
2026-08-30 09:18:13,032 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:18:47,746 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:19:05,138 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

50fd50aeefc4342929ddd31fce9bbcc2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 20/793
======================================================================
Date: 1982-10-15
Output: ERA5_chunks_fixed/ERA5_1982-10-15.grib
Submitting request...

2026-08-30 09:19:11,398 INFO Request ID is 5995e7cf-aaff-47b2-a810-839a459fc838
INFO:ecmwf.datastores.legacy_client:Request ID is 5995e7cf-aaff-47b2-a810-839a459fc838
2026-08-30 09:19:11,639 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:19:47,526 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:20:04,862 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

42242b8e0970a7590d59f3186e4b8650.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 21/793
======================================================================
Date: 1982-10-16
Output: ERA5_chunks_fixed/ERA5_1982-10-16.grib
Submitting request...

2026-08-30 09:20:11,902 INFO Request ID is 3a63ab44-f456-4c45-9039-06a64ce3f56c
INFO:ecmwf.datastores.legacy_client:Request ID is 3a63ab44-f456-4c45-9039-06a64ce3f56c
2026-08-30 09:20:13,114 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:20:49,879 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:21:33,124 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5c4d50591fb624c8942d374d12fec53a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 22/793
======================================================================
Date: 1982-10-17
Output: ERA5_chunks_fixed/ERA5_1982-10-17.grib
Submitting request...

2026-08-30 09:21:41,383 INFO Request ID is 9e201f6e-d780-4cd5-9f7a-448ccec591d8
INFO:ecmwf.datastores.legacy_client:Request ID is 9e201f6e-d780-4cd5-9f7a-448ccec591d8
2026-08-30 09:21:42,813 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:22:16,782 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:22:34,137 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

dd439f24439946f1db86362424354aee.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 23/793
======================================================================
Date: 1982-10-18
Output: ERA5_chunks_fixed/ERA5_1982-10-18.grib
Submitting request...

2026-08-30 09:22:40,987 INFO Request ID is 3ffe1d12-3bf7-4197-9c2c-b618ec095f78
INFO:ecmwf.datastores.legacy_client:Request ID is 3ffe1d12-3bf7-4197-9c2c-b618ec095f78
2026-08-30 09:22:41,214 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:23:32,408 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:23:58,298 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

17e8d33d2978b286e0ea6fa1fa07571d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 24/793
======================================================================
Date: 1982-10-19
Output: ERA5_chunks_fixed/ERA5_1982-10-19.grib
Submitting request...

2026-08-30 09:24:04,671 INFO Request ID is 17822fef-46c9-4702-a566-3fd2f1f2d80f
INFO:ecmwf.datastores.legacy_client:Request ID is 17822fef-46c9-4702-a566-3fd2f1f2d80f
2026-08-30 09:24:04,894 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:24:41,660 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:25:24,898 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1b1d32a1823a2910b72d2bd29aa6fc52.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 25/793
======================================================================
Date: 1982-10-20
Output: ERA5_chunks_fixed/ERA5_1982-10-20.grib
Submitting request...

2026-08-30 09:25:32,094 INFO Request ID is bc36df59-99b8-4284-82c7-884bafadfa02
INFO:ecmwf.datastores.legacy_client:Request ID is bc36df59-99b8-4284-82c7-884bafadfa02
2026-08-30 09:25:32,453 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:26:06,374 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ce35aad34066c02fbeb23ea63a6f739c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 26/793
======================================================================
Date: 1982-11-28
Output: ERA5_chunks_fixed/ERA5_1982-11-28.grib
Submitting request...

2026-08-30 09:26:17,186 INFO Request ID is 3f41250d-28b6-4ffe-a52a-046e0ff52e5f
INFO:ecmwf.datastores.legacy_client:Request ID is 3f41250d-28b6-4ffe-a52a-046e0ff52e5f
2026-08-30 09:26:17,411 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:26:52,968 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:27:10,280 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8b367cd7cc04506c94625dd938efda4f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 27/793
======================================================================
Date: 1982-12-02
Output: ERA5_chunks_fixed/ERA5_1982-12-02.grib
Submitting request...

2026-08-30 09:27:16,665 INFO Request ID is 7393f36f-1dcc-4360-9315-049c8adbe687
INFO:ecmwf.datastores.legacy_client:Request ID is 7393f36f-1dcc-4360-9315-049c8adbe687
2026-08-30 09:27:18,727 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:27:53,519 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:28:10,832 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

92212bf875c69df2abafe38d655ab6f6.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 28/793
======================================================================
Date: 1983-06-24
Output: ERA5_chunks_fixed/ERA5_1983-06-24.grib
Submitting request...

2026-08-30 09:28:17,251 INFO Request ID is 3c02bea7-93ec-4e79-aac3-f416ecc3e1d3
INFO:ecmwf.datastores.legacy_client:Request ID is 3c02bea7-93ec-4e79-aac3-f416ecc3e1d3
2026-08-30 09:28:17,508 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:28:39,721 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:29:08,820 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6336de6290eef2be4a31471d4eb915de.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 29/793
======================================================================
Date: 1983-06-25
Output: ERA5_chunks_fixed/ERA5_1983-06-25.grib
Submitting request...

2026-08-30 09:29:15,715 INFO Request ID is b5a8103c-d616-451e-88a5-ab7d08656125
INFO:ecmwf.datastores.legacy_client:Request ID is b5a8103c-d616-451e-88a5-ab7d08656125
2026-08-30 09:29:15,946 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:29:39,450 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:29:51,067 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cd6c3217c143a1107a8d260ec387690f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 30/793
======================================================================
Date: 1983-06-26
Output: ERA5_chunks_fixed/ERA5_1983-06-26.grib
Submitting request...

2026-08-30 09:29:57,981 INFO Request ID is 85d77d34-18c2-4903-8508-907bec2dc0c2
INFO:ecmwf.datastores.legacy_client:Request ID is 85d77d34-18c2-4903-8508-907bec2dc0c2
2026-08-30 09:29:58,208 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:30:32,431 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:31:15,734 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5b0bea9152ccc3f05d9b3a09da75a50f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 31/793
======================================================================
Date: 1983-10-14
Output: ERA5_chunks_fixed/ERA5_1983-10-14.grib
Submitting request...

2026-08-30 09:31:21,890 INFO Request ID is 58f6b854-d5fc-4e36-b683-aafea4991b2d
INFO:ecmwf.datastores.legacy_client:Request ID is 58f6b854-d5fc-4e36-b683-aafea4991b2d
2026-08-30 09:31:22,733 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:31:45,820 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:31:58,593 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b69455444f9bb10980e83d91a2981763.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 32/793
======================================================================
Date: 1983-11-06
Output: ERA5_chunks_fixed/ERA5_1983-11-06.grib
Submitting request...

2026-08-30 09:32:06,765 INFO Request ID is 8bda4b28-8713-40af-a46a-db7f4746e87c
INFO:ecmwf.datastores.legacy_client:Request ID is 8bda4b28-8713-40af-a46a-db7f4746e87c
2026-08-30 09:32:06,994 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:32:40,878 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:33:24,136 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

af263535684b014de4cd7a2aec2624f7.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 33/793
======================================================================
Date: 1983-11-07
Output: ERA5_chunks_fixed/ERA5_1983-11-07.grib
Submitting request...

2026-08-30 09:33:33,106 INFO Request ID is b52ecced-24c2-4464-8f74-f3e10a15d327
INFO:ecmwf.datastores.legacy_client:Request ID is b52ecced-24c2-4464-8f74-f3e10a15d327
2026-08-30 09:33:33,355 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:34:07,249 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:34:24,562 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

24b6b2a8e76095c2f1f44b3bc8890000.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 34/793
======================================================================
Date: 1983-11-08
Output: ERA5_chunks_fixed/ERA5_1983-11-08.grib
Submitting request...

2026-08-30 09:34:31,787 INFO Request ID is e819b121-a5ea-41b6-bb66-5769d5ef3418
INFO:ecmwf.datastores.legacy_client:Request ID is e819b121-a5ea-41b6-bb66-5769d5ef3418
2026-08-30 09:34:32,085 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:34:51,244 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:35:28,086 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1481035e7b84d51bb03dfc6396599816.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 35/793
======================================================================
Date: 1984-07-31
Output: ERA5_chunks_fixed/ERA5_1984-07-31.grib
Submitting request...

2026-08-30 09:35:35,174 INFO Request ID is 56570622-e3bf-424d-824d-e8f4a9be7fca
INFO:ecmwf.datastores.legacy_client:Request ID is 56570622-e3bf-424d-824d-e8f4a9be7fca
2026-08-30 09:35:35,427 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:36:27,072 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9c43876bd54081a7bf778d6b0827c699.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 36/793
======================================================================
Date: 1984-08-01
Output: ERA5_chunks_fixed/ERA5_1984-08-01.grib
Submitting request...

2026-08-30 09:36:33,373 INFO Request ID is 7a411f2e-daa2-4cfa-bc5f-bf19af5aef49
INFO:ecmwf.datastores.legacy_client:Request ID is 7a411f2e-daa2-4cfa-bc5f-bf19af5aef49
2026-08-30 09:36:33,785 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:37:24,996 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2e98b20542962581569649f47f020f82.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 37/793
======================================================================
Date: 1984-08-02
Output: ERA5_chunks_fixed/ERA5_1984-08-02.grib
Submitting request...

2026-08-30 09:37:31,281 INFO Request ID is 57fced5a-8aa5-4970-b1bd-a1db60c2a82c
INFO:ecmwf.datastores.legacy_client:Request ID is 57fced5a-8aa5-4970-b1bd-a1db60c2a82c
2026-08-30 09:37:32,012 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:38:06,328 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:38:24,082 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9bd70c3f5e624779099c9ae73bf34d99.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 38/793
======================================================================
Date: 1984-08-03
Output: ERA5_chunks_fixed/ERA5_1984-08-03.grib
Submitting request...

2026-08-30 09:38:30,750 INFO Request ID is 377c51ba-ec1a-4c80-b334-bbc294a6b98d
INFO:ecmwf.datastores.legacy_client:Request ID is 377c51ba-ec1a-4c80-b334-bbc294a6b98d
2026-08-30 09:38:30,994 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:39:05,155 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:39:22,469 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

22b07c01c87574d36d7249b76c235cf4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 39/793
======================================================================
Date: 1984-08-04
Output: ERA5_chunks_fixed/ERA5_1984-08-04.grib
Submitting request...

2026-08-30 09:39:28,734 INFO Request ID is 42316e05-cd66-4f86-be60-c2d739578dd0
INFO:ecmwf.datastores.legacy_client:Request ID is 42316e05-cd66-4f86-be60-c2d739578dd0
2026-08-30 09:39:28,970 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:40:03,393 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:40:24,377 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d0d4280a9089d9e29d211962e05ce3f8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 40/793
======================================================================
Date: 1984-08-05
Output: ERA5_chunks_fixed/ERA5_1984-08-05.grib
Submitting request...

2026-08-30 09:40:31,726 INFO Request ID is 4d35b408-59cd-4ba9-913a-abd6a2cec50a
INFO:ecmwf.datastores.legacy_client:Request ID is 4d35b408-59cd-4ba9-913a-abd6a2cec50a
2026-08-30 09:40:31,972 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:41:05,788 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:41:24,980 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cdff89f96e6fec1899b4c17df147626a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 41/793
======================================================================
Date: 1984-08-06
Output: ERA5_chunks_fixed/ERA5_1984-08-06.grib
Submitting request...

2026-08-30 09:41:33,034 INFO Request ID is e1207f0e-a910-4b5b-91ae-0630c71ce8d7
INFO:ecmwf.datastores.legacy_client:Request ID is e1207f0e-a910-4b5b-91ae-0630c71ce8d7
2026-08-30 09:41:33,274 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:42:07,077 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:42:24,423 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

112b3e5f6b031aa05f037d3efd089d9d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 42/793
======================================================================
Date: 1984-08-15
Output: ERA5_chunks_fixed/ERA5_1984-08-15.grib
Submitting request...

2026-08-30 09:42:31,441 INFO Request ID is c7bd082d-7afb-4148-9e30-025f77d1d90f
INFO:ecmwf.datastores.legacy_client:Request ID is c7bd082d-7afb-4148-9e30-025f77d1d90f
2026-08-30 09:42:31,677 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:43:06,971 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:43:24,303 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7fb04fb1ba6a04dfe2220e36a01f14be.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 43/793
======================================================================
Date: 1984-08-16
Output: ERA5_chunks_fixed/ERA5_1984-08-16.grib
Submitting request...

2026-08-30 09:43:32,923 INFO Request ID is 22c424fa-9a6c-42c1-9b2e-964461035f75
INFO:ecmwf.datastores.legacy_client:Request ID is 22c424fa-9a6c-42c1-9b2e-964461035f75
2026-08-30 09:43:33,150 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:44:07,809 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:44:51,029 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5c44ca80fae9700e4ef8cd590693d357.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 44/793
======================================================================
Date: 1984-08-17
Output: ERA5_chunks_fixed/ERA5_1984-08-17.grib
Submitting request...

2026-08-30 09:44:58,865 INFO Request ID is 24900b48-db05-4413-9799-7637f016843c
INFO:ecmwf.datastores.legacy_client:Request ID is 24900b48-db05-4413-9799-7637f016843c
2026-08-30 09:44:59,106 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:45:33,394 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:45:50,708 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

39819b4301d0121883e1508b3b68ca30.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 45/793
======================================================================
Date: 1984-08-18
Output: ERA5_chunks_fixed/ERA5_1984-08-18.grib
Submitting request...

2026-08-30 09:45:57,514 INFO Request ID is 8d4b7890-9d1b-4982-a905-e3028b0ae5c6
INFO:ecmwf.datastores.legacy_client:Request ID is 8d4b7890-9d1b-4982-a905-e3028b0ae5c6
2026-08-30 09:45:57,777 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:46:12,204 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:46:31,709 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ca2a08d92bfd65a4ecd6b11511d0e402.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 46/793
======================================================================
Date: 1984-10-13
Output: ERA5_chunks_fixed/ERA5_1984-10-13.grib
Submitting request...

2026-08-30 09:46:38,594 INFO Request ID is 245c30aa-ce91-489b-a096-45aa0ca87391
INFO:ecmwf.datastores.legacy_client:Request ID is 245c30aa-ce91-489b-a096-45aa0ca87391
2026-08-30 09:46:38,837 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:47:02,005 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:47:30,959 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

18e1cdd3c0d8ec3d4801293cd365d4c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 47/793
======================================================================
Date: 1984-10-14
Output: ERA5_chunks_fixed/ERA5_1984-10-14.grib
Submitting request...

2026-08-30 09:47:38,416 INFO Request ID is f1945b77-9c52-4e51-a868-14fb48e641f0
INFO:ecmwf.datastores.legacy_client:Request ID is f1945b77-9c52-4e51-a868-14fb48e641f0
2026-08-30 09:47:38,665 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:48:12,533 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:48:29,867 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

35c4f9e6bfd30b2a48746c35ff7672ca.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 48/793
======================================================================
Date: 1984-11-09
Output: ERA5_chunks_fixed/ERA5_1984-11-09.grib
Submitting request...

2026-08-30 09:48:39,856 INFO Request ID is c63fb697-4bf0-4181-9bfa-139183d4a63d
INFO:ecmwf.datastores.legacy_client:Request ID is c63fb697-4bf0-4181-9bfa-139183d4a63d
2026-08-30 09:48:43,356 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:48:57,765 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:49:34,785 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

52cb68d020467454d9f2009be38c9282.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 49/793
======================================================================
Date: 1984-11-10
Output: ERA5_chunks_fixed/ERA5_1984-11-10.grib
Submitting request...

2026-08-30 09:49:43,413 INFO Request ID is 16f2d102-a5ce-42cd-bdf9-d1156f9ebfd3
INFO:ecmwf.datastores.legacy_client:Request ID is 16f2d102-a5ce-42cd-bdf9-d1156f9ebfd3
2026-08-30 09:49:43,658 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:49:59,300 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:50:36,100 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f31a40a7ad3e02c3f8baf662d88ffa3.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 50/793
======================================================================
Date: 1984-11-11
Output: ERA5_chunks_fixed/ERA5_1984-11-11.grib
Submitting request...

2026-08-30 09:50:42,441 INFO Request ID is 9a7b4c90-e0d0-4176-b775-3bf6296391ee
INFO:ecmwf.datastores.legacy_client:Request ID is 9a7b4c90-e0d0-4176-b775-3bf6296391ee
2026-08-30 09:50:42,688 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:51:04,919 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:51:35,202 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3a413804c3feb9fe335248c517242db1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 51/793
======================================================================
Date: 1984-11-12
Output: ERA5_chunks_fixed/ERA5_1984-11-12.grib
Submitting request...

2026-08-30 09:51:42,734 INFO Request ID is 8c21988b-a333-4cdf-a8bd-5c937c8c50e0
INFO:ecmwf.datastores.legacy_client:Request ID is 8c21988b-a333-4cdf-a8bd-5c937c8c50e0
2026-08-30 09:51:43,408 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:52:07,079 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:52:36,062 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ec9f410d32f2a7814ccc018d34aa5aa1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 52/793
======================================================================
Date: 1984-11-13
Output: ERA5_chunks_fixed/ERA5_1984-11-13.grib
Submitting request...

2026-08-30 09:52:42,535 INFO Request ID is 89ee6f82-c034-4c80-b203-51b50274f0ad
INFO:ecmwf.datastores.legacy_client:Request ID is 89ee6f82-c034-4c80-b203-51b50274f0ad
2026-08-30 09:52:42,781 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:53:05,052 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:53:33,989 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3f99ae5ac61c497b6c2fdade93ccc1b8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 53/793
======================================================================
Date: 1984-11-27
Output: ERA5_chunks_fixed/ERA5_1984-11-27.grib
Submitting request...

2026-08-30 09:53:41,326 INFO Request ID is 5d191039-7050-4c10-93ee-f7e7c6bfedb3
INFO:ecmwf.datastores.legacy_client:Request ID is 5d191039-7050-4c10-93ee-f7e7c6bfedb3
2026-08-30 09:53:41,556 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:54:03,958 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:54:36,673 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

28c7f0aadcbfbe0c8d5624ce45f91749.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 54/793
======================================================================
Date: 1984-11-30
Output: ERA5_chunks_fixed/ERA5_1984-11-30.grib
Submitting request...

2026-08-30 09:54:45,415 INFO Request ID is 8bd9f5fe-2c9f-40f1-944c-875563e4859a
INFO:ecmwf.datastores.legacy_client:Request ID is 8bd9f5fe-2c9f-40f1-944c-875563e4859a
2026-08-30 09:54:45,641 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:55:21,378 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:55:38,700 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

578ea3a39808e2d3bc6e19f1ac6b39f2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 55/793
======================================================================
Date: 1984-12-01
Output: ERA5_chunks_fixed/ERA5_1984-12-01.grib
Submitting request...

2026-08-30 09:55:44,912 INFO Request ID is 4d58a83e-15d5-4c4d-9e2f-5bdce44693ea
INFO:ecmwf.datastores.legacy_client:Request ID is 4d58a83e-15d5-4c4d-9e2f-5bdce44693ea
2026-08-30 09:55:45,178 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:56:07,502 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:56:36,446 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

62c696e70a324085f19329eec9cff144.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 56/793
======================================================================
Date: 1985-05-22
Output: ERA5_chunks_fixed/ERA5_1985-05-22.grib
Submitting request...

2026-08-30 09:56:42,969 INFO Request ID is f1a92337-8d92-446a-85d2-e2d666d6a47b
INFO:ecmwf.datastores.legacy_client:Request ID is f1a92337-8d92-446a-85d2-e2d666d6a47b
2026-08-30 09:56:43,208 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:57:18,545 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:57:35,921 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fdcde212a8ad21c80a0ee641c6beda05.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 57/793
======================================================================
Date: 1985-05-23
Output: ERA5_chunks_fixed/ERA5_1985-05-23.grib
Submitting request...

2026-08-30 09:57:42,256 INFO Request ID is c9eecb89-974f-4f57-bf4e-2155ff0ae45e
INFO:ecmwf.datastores.legacy_client:Request ID is c9eecb89-974f-4f57-bf4e-2155ff0ae45e
2026-08-30 09:57:42,499 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:57:57,130 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:58:17,628 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cf9e6397aa4937f68d8790caa7185881.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 58/793
======================================================================
Date: 1985-05-24
Output: ERA5_chunks_fixed/ERA5_1985-05-24.grib
Submitting request...

2026-08-30 09:58:24,192 INFO Request ID is 7684466d-59d7-4aa9-a2f7-be70ea1b0468
INFO:ecmwf.datastores.legacy_client:Request ID is 7684466d-59d7-4aa9-a2f7-be70ea1b0468
2026-08-30 09:58:24,435 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:58:47,969 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:58:59,588 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a450c34e7489b19a5bfb8ace1263b1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 59/793
======================================================================
Date: 1985-08-06
Output: ERA5_chunks_fixed/ERA5_1985-08-06.grib
Submitting request...

2026-08-30 09:59:06,426 INFO Request ID is 82edb74c-33f5-475b-9529-98d27fe566b9
INFO:ecmwf.datastores.legacy_client:Request ID is 82edb74c-33f5-475b-9529-98d27fe566b9
2026-08-30 09:59:06,677 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 09:59:40,530 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 09:59:58,082 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2c9355a445688a38b566b016d8c0b2db.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 60/793
======================================================================
Date: 1985-08-07
Output: ERA5_chunks_fixed/ERA5_1985-08-07.grib
Submitting request...

2026-08-30 10:00:06,413 INFO Request ID is 420bff6d-464f-4806-8fcb-2040d72758a2
INFO:ecmwf.datastores.legacy_client:Request ID is 420bff6d-464f-4806-8fcb-2040d72758a2
2026-08-30 10:00:11,443 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:00:33,801 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:00:45,419 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

77f07e836f0a50c2ee465da00fe81dfa.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 61/793
======================================================================
Date: 1985-08-08
Output: ERA5_chunks_fixed/ERA5_1985-08-08.grib
Submitting request...

2026-08-30 10:00:58,118 INFO Request ID is 31ee16df-bfd6-4065-bf0b-aecdc896aa1e
INFO:ecmwf.datastores.legacy_client:Request ID is 31ee16df-bfd6-4065-bf0b-aecdc896aa1e
2026-08-30 10:01:03,011 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:02:25,643 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:03:05,768 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

882da961c06eb00097920d82d6069c43.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 62/793
======================================================================
Date: 1985-09-19
Output: ERA5_chunks_fixed/ERA5_1985-09-19.grib
Submitting request...

2026-08-30 10:03:12,369 INFO Request ID is 2b368ccf-e268-4912-9043-5094542cbf5c
INFO:ecmwf.datastores.legacy_client:Request ID is 2b368ccf-e268-4912-9043-5094542cbf5c
2026-08-30 10:03:13,153 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:03:50,342 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:04:07,671 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2d16596db0bc202814fd49dd4840a82f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 63/793
======================================================================
Date: 1985-09-20
Output: ERA5_chunks_fixed/ERA5_1985-09-20.grib
Submitting request...

2026-08-30 10:04:14,235 INFO Request ID is 36e8b61f-35f4-41ca-afb7-2b3bda36b9af
INFO:ecmwf.datastores.legacy_client:Request ID is 36e8b61f-35f4-41ca-afb7-2b3bda36b9af
2026-08-30 10:04:14,485 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:04:50,061 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:05:09,943 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a160eececae3db305e43b679f51c4a6e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 64/793
======================================================================
Date: 1985-10-01
Output: ERA5_chunks_fixed/ERA5_1985-10-01.grib
Submitting request...

2026-08-30 10:05:17,169 INFO Request ID is 8b844ec4-5f30-46dc-a7d8-fc57c0aaaa26
INFO:ecmwf.datastores.legacy_client:Request ID is 8b844ec4-5f30-46dc-a7d8-fc57c0aaaa26
2026-08-30 10:05:17,419 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:05:35,447 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:07:17,087 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

90b47260d242407de3187e0fd51155c1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 65/793
======================================================================
Date: 1985-10-09
Output: ERA5_chunks_fixed/ERA5_1985-10-09.grib
Submitting request...

2026-08-30 10:07:23,730 INFO Request ID is a0b7434a-5df0-4d13-aa4a-707877908525
INFO:ecmwf.datastores.legacy_client:Request ID is a0b7434a-5df0-4d13-aa4a-707877908525
2026-08-30 10:07:24,193 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:08:00,430 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:08:43,649 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

21ed1628ee0eec733757310aedad40d3.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 66/793
======================================================================
Date: 1985-10-10
Output: ERA5_chunks_fixed/ERA5_1985-10-10.grib
Submitting request...

2026-08-30 10:08:50,100 INFO Request ID is 953095e6-2760-4bf6-aed1-acabad60bc15
INFO:ecmwf.datastores.legacy_client:Request ID is 953095e6-2760-4bf6-aed1-acabad60bc15
2026-08-30 10:08:50,338 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:09:42,541 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:10:08,462 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

dd8c3b9c2c29069ebdf10e8790cdcc84.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 67/793
======================================================================
Date: 1985-10-12
Output: ERA5_chunks_fixed/ERA5_1985-10-12.grib
Submitting request...

2026-08-30 10:10:15,352 INFO Request ID is 1b1da5b7-cfa7-4fb2-97df-cfed05e944b0
INFO:ecmwf.datastores.legacy_client:Request ID is 1b1da5b7-cfa7-4fb2-97df-cfed05e944b0
2026-08-30 10:10:15,592 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:10:49,562 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:11:08,085 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

de3422459046e8ae87c15031667e7b21.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 68/793
======================================================================
Date: 1985-10-13
Output: ERA5_chunks_fixed/ERA5_1985-10-13.grib
Submitting request...

2026-08-30 10:11:17,286 INFO Request ID is 127ba60a-acde-43dc-9705-0fd524cff8a0
INFO:ecmwf.datastores.legacy_client:Request ID is 127ba60a-acde-43dc-9705-0fd524cff8a0
2026-08-30 10:11:17,643 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:11:35,791 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:11:55,518 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

883f17bf0630991523284ff4345f853e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 69/793
======================================================================
Date: 1985-10-14
Output: ERA5_chunks_fixed/ERA5_1985-10-14.grib
Submitting request...

2026-08-30 10:12:03,387 INFO Request ID is f8c5bf67-6ea4-4fc3-9b61-2f524cad8d4b
INFO:ecmwf.datastores.legacy_client:Request ID is f8c5bf67-6ea4-4fc3-9b61-2f524cad8d4b
2026-08-30 10:12:03,727 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:12:28,278 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:12:40,001 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b5abc492ef5bc3456cad4074bc82d41c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 70/793
======================================================================
Date: 1985-10-15
Output: ERA5_chunks_fixed/ERA5_1985-10-15.grib
Submitting request...

2026-08-30 10:12:46,757 INFO Request ID is 4387c495-0e25-4ff2-b6ea-0db04dc71eb3
INFO:ecmwf.datastores.legacy_client:Request ID is 4387c495-0e25-4ff2-b6ea-0db04dc71eb3
2026-08-30 10:12:46,997 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:13:21,788 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:13:39,163 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3893ff5a18b29f7c527e4ed14e746c22.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 71/793
======================================================================
Date: 1985-10-16
Output: ERA5_chunks_fixed/ERA5_1985-10-16.grib
Submitting request...

2026-08-30 10:13:46,125 INFO Request ID is d3b364fe-142e-420c-b154-09eca99e3078
INFO:ecmwf.datastores.legacy_client:Request ID is d3b364fe-142e-420c-b154-09eca99e3078
2026-08-30 10:13:46,392 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:14:20,489 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:15:03,702 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b50980e4660f9cc95dabfc1deb4c6026.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 72/793
======================================================================
Date: 1985-11-15
Output: ERA5_chunks_fixed/ERA5_1985-11-15.grib
Submitting request...

2026-08-30 10:15:13,296 INFO Request ID is cfa6604c-aba4-48e1-b4ae-c367375a0803
INFO:ecmwf.datastores.legacy_client:Request ID is cfa6604c-aba4-48e1-b4ae-c367375a0803
2026-08-30 10:15:13,628 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:15:36,570 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:16:05,612 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ef56c4e8dcc83ccfc324cde77657627.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 73/793
======================================================================
Date: 1985-11-16
Output: ERA5_chunks_fixed/ERA5_1985-11-16.grib
Submitting request...

2026-08-30 10:16:12,192 INFO Request ID is b17de1f8-b75d-4dca-b61e-a1c380d8b993
INFO:ecmwf.datastores.legacy_client:Request ID is b17de1f8-b75d-4dca-b61e-a1c380d8b993
2026-08-30 10:16:12,439 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:17:03,947 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:17:30,550 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

37b72aa2541537093371f97e97ad9d1c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 74/793
======================================================================
Date: 1985-12-11
Output: ERA5_chunks_fixed/ERA5_1985-12-11.grib
Submitting request...

2026-08-30 10:17:37,077 INFO Request ID is 518388bb-1634-4b32-96ff-143f1e367f27
INFO:ecmwf.datastores.legacy_client:Request ID is 518388bb-1634-4b32-96ff-143f1e367f27
2026-08-30 10:17:37,336 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:18:00,641 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:18:30,545 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4dd6293d276e6c021443a160e4a6fe27.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 75/793
======================================================================
Date: 1985-12-12
Output: ERA5_chunks_fixed/ERA5_1985-12-12.grib
Submitting request...

2026-08-30 10:18:37,956 INFO Request ID is c2106bd1-aa0d-4f83-a38b-e92a808afe18
INFO:ecmwf.datastores.legacy_client:Request ID is c2106bd1-aa0d-4f83-a38b-e92a808afe18
2026-08-30 10:18:39,137 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:19:15,385 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:19:32,699 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

57fc196e59800b1f16b1e1fb1c8c71a1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 76/793
======================================================================
Date: 1985-12-13
Output: ERA5_chunks_fixed/ERA5_1985-12-13.grib
Submitting request...

2026-08-30 10:19:40,049 INFO Request ID is f380ad8e-36e1-4034-9d84-faaa2617aa27
INFO:ecmwf.datastores.legacy_client:Request ID is f380ad8e-36e1-4034-9d84-faaa2617aa27
2026-08-30 10:19:40,283 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:20:14,480 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:20:32,984 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7c6f835ab527a496601683f0accc134f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 77/793
======================================================================
Date: 1986-01-07
Output: ERA5_chunks_fixed/ERA5_1986-01-07.grib
Submitting request...

2026-08-30 10:20:39,622 INFO Request ID is 6c9046ed-5ccc-4cf5-b705-42c77f8c7d58
INFO:ecmwf.datastores.legacy_client:Request ID is 6c9046ed-5ccc-4cf5-b705-42c77f8c7d58
2026-08-30 10:20:39,917 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:21:13,837 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:21:31,170 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ff4cd150717150417a3be019a6a178c7.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 78/793
======================================================================
Date: 1986-08-10
Output: ERA5_chunks_fixed/ERA5_1986-08-10.grib
Submitting request...

2026-08-30 10:21:37,277 INFO Request ID is 57eb8b4f-a1b6-4b30-8f67-430944afd1f6
INFO:ecmwf.datastores.legacy_client:Request ID is 57eb8b4f-a1b6-4b30-8f67-430944afd1f6
2026-08-30 10:21:37,515 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:22:13,304 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:22:30,619 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a9b05f0591bd7177b733de6451681c53.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 79/793
======================================================================
Date: 1986-08-11
Output: ERA5_chunks_fixed/ERA5_1986-08-11.grib
Submitting request...

2026-08-30 10:22:37,172 INFO Request ID is 6cb1a58e-36ab-4db8-8d4b-c7cd69fa7c05
INFO:ecmwf.datastores.legacy_client:Request ID is 6cb1a58e-36ab-4db8-8d4b-c7cd69fa7c05
2026-08-30 10:22:37,427 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:23:12,848 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:23:30,304 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

11fd5ecdadc2dd764a1d7c0f9c4aecea.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 80/793
======================================================================
Date: 1986-08-12
Output: ERA5_chunks_fixed/ERA5_1986-08-12.grib
Submitting request...

2026-08-30 10:23:37,844 INFO Request ID is b20d94b0-2330-4768-8913-69a4884edb76
INFO:ecmwf.datastores.legacy_client:Request ID is b20d94b0-2330-4768-8913-69a4884edb76
2026-08-30 10:23:38,087 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:24:13,836 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:24:31,152 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4b6985362b8e99cf8c03d5ab1af8e19d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 81/793
======================================================================
Date: 1986-08-13
Output: ERA5_chunks_fixed/ERA5_1986-08-13.grib
Submitting request...

2026-08-30 10:24:37,808 INFO Request ID is f887cfe1-edf6-4a48-b232-5fced8f9daf0
INFO:ecmwf.datastores.legacy_client:Request ID is f887cfe1-edf6-4a48-b232-5fced8f9daf0
2026-08-30 10:24:38,130 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:25:12,129 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:25:31,550 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2dda7be132e4c0e44d15756011a2ef4d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 82/793
======================================================================
Date: 1986-08-19
Output: ERA5_chunks_fixed/ERA5_1986-08-19.grib
Submitting request...

2026-08-30 10:25:38,994 INFO Request ID is 0285511e-bea1-4415-9473-3d4b39488c09
INFO:ecmwf.datastores.legacy_client:Request ID is 0285511e-bea1-4415-9473-3d4b39488c09
2026-08-30 10:25:39,231 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:26:02,854 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:26:31,827 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

55d9a543c47a8104fa613d9a7b3c3b35.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 83/793
======================================================================
Date: 1986-09-24
Output: ERA5_chunks_fixed/ERA5_1986-09-24.grib
Submitting request...

2026-08-30 10:26:39,184 INFO Request ID is dd8a114d-c1b2-4c8e-b3b8-673d700805dd
INFO:ecmwf.datastores.legacy_client:Request ID is dd8a114d-c1b2-4c8e-b3b8-673d700805dd
2026-08-30 10:26:39,426 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:27:14,214 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

81bad52c9e311f683f1cd3e0747f2f4a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 84/793
======================================================================
Date: 1986-09-25
Output: ERA5_chunks_fixed/ERA5_1986-09-25.grib
Submitting request...

2026-08-30 10:27:20,856 INFO Request ID is 345ab417-917b-4944-a6a9-1f93163e0ae2
INFO:ecmwf.datastores.legacy_client:Request ID is 345ab417-917b-4944-a6a9-1f93163e0ae2
2026-08-30 10:27:21,116 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:27:55,633 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:28:38,849 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2710020793b4401f4205f35f0b7ddcb9.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 85/793
======================================================================
Date: 1986-11-07
Output: ERA5_chunks_fixed/ERA5_1986-11-07.grib
Submitting request...

2026-08-30 10:28:46,036 INFO Request ID is df20ed8d-75d1-4e5f-b360-c422f3e34e3c
INFO:ecmwf.datastores.legacy_client:Request ID is df20ed8d-75d1-4e5f-b360-c422f3e34e3c
2026-08-30 10:28:46,288 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:29:21,928 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:29:39,239 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d6e3727fba69c288808565df3c8a2a2b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 86/793
======================================================================
Date: 1986-11-08
Output: ERA5_chunks_fixed/ERA5_1986-11-08.grib
Submitting request...

2026-08-30 10:29:46,140 INFO Request ID is 6138a560-a29c-4ab5-8c30-562948e15af7
INFO:ecmwf.datastores.legacy_client:Request ID is 6138a560-a29c-4ab5-8c30-562948e15af7
2026-08-30 10:29:46,384 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:30:24,670 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:30:42,019 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

19e939064ffe49a5588ebd037f69e21d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 87/793
======================================================================
Date: 1987-01-30
Output: ERA5_chunks_fixed/ERA5_1987-01-30.grib
Submitting request...

2026-08-30 10:30:49,921 INFO Request ID is 1afeb67a-bcf0-4eb6-9807-8c2072f41688
INFO:ecmwf.datastores.legacy_client:Request ID is 1afeb67a-bcf0-4eb6-9807-8c2072f41688
2026-08-30 10:30:50,205 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:31:24,691 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:31:42,004 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

dca2f7e3b42fe7d42f055b58b68fb329.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 88/793
======================================================================
Date: 1987-01-31
Output: ERA5_chunks_fixed/ERA5_1987-01-31.grib
Submitting request...

2026-08-30 10:31:53,246 INFO Request ID is ca5ecc7f-aaed-4101-b273-ae877e16642b
INFO:ecmwf.datastores.legacy_client:Request ID is ca5ecc7f-aaed-4101-b273-ae877e16642b
2026-08-30 10:31:53,475 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:33:12,877 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4cbf978c3bce53083a534ae7e12bdb42.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 89/793
======================================================================
Date: 1987-02-01
Output: ERA5_chunks_fixed/ERA5_1987-02-01.grib
Submitting request...

2026-08-30 10:33:22,154 INFO Request ID is 196db576-1907-43c8-846d-b0f7ff14ff56
INFO:ecmwf.datastores.legacy_client:Request ID is 196db576-1907-43c8-846d-b0f7ff14ff56
2026-08-30 10:33:22,403 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:34:14,419 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

71821dfc7f53a3a6e21368a0508928e5.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 90/793
======================================================================
Date: 1987-02-02
Output: ERA5_chunks_fixed/ERA5_1987-02-02.grib
Submitting request...

2026-08-30 10:34:20,782 INFO Request ID is 4a74462e-ed4c-4692-ab5a-b9ff7a7ca8f4
INFO:ecmwf.datastores.legacy_client:Request ID is 4a74462e-ed4c-4692-ab5a-b9ff7a7ca8f4
2026-08-30 10:34:21,007 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:34:55,500 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:35:12,836 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cd1302267f3e6ba0b1e49137c1780d0a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 91/793
======================================================================
Date: 1987-02-03
Output: ERA5_chunks_fixed/ERA5_1987-02-03.grib
Submitting request...

2026-08-30 10:35:20,436 INFO Request ID is 0d1828c6-46f9-4efa-b387-77e4070b14df
INFO:ecmwf.datastores.legacy_client:Request ID is 0d1828c6-46f9-4efa-b387-77e4070b14df
2026-08-30 10:35:20,691 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:35:55,743 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:36:13,075 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9fd9e281932defe9cf25185cbf08d956.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 92/793
======================================================================
Date: 1987-06-01
Output: ERA5_chunks_fixed/ERA5_1987-06-01.grib
Submitting request...

2026-08-30 10:36:19,544 INFO Request ID is 58b66ebc-c2a8-4b7f-9be0-b5db28d1222c
INFO:ecmwf.datastores.legacy_client:Request ID is 58b66ebc-c2a8-4b7f-9be0-b5db28d1222c
2026-08-30 10:36:19,801 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:36:53,768 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:37:11,389 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

919712a57e9f9d1d7898016c8f7acf8b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 93/793
======================================================================
Date: 1987-06-02
Output: ERA5_chunks_fixed/ERA5_1987-06-02.grib
Submitting request...

2026-08-30 10:37:18,105 INFO Request ID is ed2eafc8-7052-4bae-9241-d59c97d07cd6
INFO:ecmwf.datastores.legacy_client:Request ID is ed2eafc8-7052-4bae-9241-d59c97d07cd6
2026-08-30 10:37:18,361 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:37:54,272 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:38:11,770 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

792c2131b0159d9a833616fe7d40563d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 94/793
======================================================================
Date: 1987-06-03
Output: ERA5_chunks_fixed/ERA5_1987-06-03.grib
Submitting request...

2026-08-30 10:38:17,951 INFO Request ID is a5cadfa4-449a-4a24-b0a0-93256c84707b
INFO:ecmwf.datastores.legacy_client:Request ID is a5cadfa4-449a-4a24-b0a0-93256c84707b
2026-08-30 10:38:18,177 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:39:10,387 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:39:36,279 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d479493665e2b550ff052346710f258b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 95/793
======================================================================
Date: 1987-06-04
Output: ERA5_chunks_fixed/ERA5_1987-06-04.grib
Submitting request...

2026-08-30 10:39:43,334 INFO Request ID is d1e5a60e-1b88-484b-843a-0af5f431c298
INFO:ecmwf.datastores.legacy_client:Request ID is d1e5a60e-1b88-484b-843a-0af5f431c298
2026-08-30 10:39:43,586 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:40:06,029 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:40:34,974 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

50160eb17ebdb8dc58cbd1d436c80696.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 96/793
======================================================================
Date: 1987-08-26
Output: ERA5_chunks_fixed/ERA5_1987-08-26.grib
Submitting request...

2026-08-30 10:40:42,124 INFO Request ID is b8484815-fe13-46be-a97d-3d6cc90b2cc9
INFO:ecmwf.datastores.legacy_client:Request ID is b8484815-fe13-46be-a97d-3d6cc90b2cc9
2026-08-30 10:40:42,385 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:41:36,422 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:42:02,287 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

49eba57448c207cd21eb8ca14cc2cee6.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 97/793
======================================================================
Date: 1987-08-27
Output: ERA5_chunks_fixed/ERA5_1987-08-27.grib
Submitting request...

2026-08-30 10:42:09,129 INFO Request ID is 51c60721-4cc9-41fe-930b-afd3ffd64ce1
INFO:ecmwf.datastores.legacy_client:Request ID is 51c60721-4cc9-41fe-930b-afd3ffd64ce1
2026-08-30 10:42:09,377 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:42:23,980 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:42:43,471 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b3d9e15f091671e3b8f08bd9c905bf9b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 98/793
======================================================================
Date: 1987-08-28
Output: ERA5_chunks_fixed/ERA5_1987-08-28.grib
Submitting request...

2026-08-30 10:42:51,806 INFO Request ID is a9b5a904-f7db-45f9-9018-8e0a5d4e1443
INFO:ecmwf.datastores.legacy_client:Request ID is a9b5a904-f7db-45f9-9018-8e0a5d4e1443
2026-08-30 10:42:52,063 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:43:15,041 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:43:44,012 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ba3ea00f3f2a561de94582bd2d14a40c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 99/793
======================================================================
Date: 1987-09-11
Output: ERA5_chunks_fixed/ERA5_1987-09-11.grib
Submitting request...

2026-08-30 10:43:50,622 INFO Request ID is 3472d2d5-5028-4567-96b1-760a02dab5d8
INFO:ecmwf.datastores.legacy_client:Request ID is 3472d2d5-5028-4567-96b1-760a02dab5d8
2026-08-30 10:43:51,465 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:44:13,742 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:44:42,696 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

bc2a6cc9d3231005821ee5a3fd41bc7d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 100/793
======================================================================
Date: 1987-09-15
Output: ERA5_chunks_fixed/ERA5_1987-09-15.grib
Submitting request...

2026-08-30 10:44:49,120 INFO Request ID is ba182ad7-a9a9-45f4-84f4-e7a56cb3019b
INFO:ecmwf.datastores.legacy_client:Request ID is ba182ad7-a9a9-45f4-84f4-e7a56cb3019b
2026-08-30 10:44:49,343 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:45:11,580 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:45:23,227 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

116be215eb8f27d9aebb10e696b4cad5.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 101/793
======================================================================
Date: 1987-10-14
Output: ERA5_chunks_fixed/ERA5_1987-10-14.grib
Submitting request...

2026-08-30 10:45:31,322 INFO Request ID is af3c8600-a18b-4c55-b883-469c73eca9f6
INFO:ecmwf.datastores.legacy_client:Request ID is af3c8600-a18b-4c55-b883-469c73eca9f6
2026-08-30 10:45:31,962 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:46:06,045 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:46:23,368 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5011659a80bce200a7091d4e90a15b20.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 102/793
======================================================================
Date: 1987-10-15
Output: ERA5_chunks_fixed/ERA5_1987-10-15.grib
Submitting request...

2026-08-30 10:46:31,085 INFO Request ID is 54cdaa08-9a70-42fa-a773-a7d72cd41b43
INFO:ecmwf.datastores.legacy_client:Request ID is 54cdaa08-9a70-42fa-a773-a7d72cd41b43
2026-08-30 10:46:33,730 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:47:09,720 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

608ef51f8a1ee74f0dcd9dd053635046.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 103/793
======================================================================
Date: 1987-10-16
Output: ERA5_chunks_fixed/ERA5_1987-10-16.grib
Submitting request...

2026-08-30 10:47:16,334 INFO Request ID is 3e5a11ec-5bb8-40b6-8576-95360600fb05
INFO:ecmwf.datastores.legacy_client:Request ID is 3e5a11ec-5bb8-40b6-8576-95360600fb05
2026-08-30 10:47:16,583 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:47:50,430 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

654d5d76e73f9f3002686a69e33cb3df.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 104/793
======================================================================
Date: 1987-10-17
Output: ERA5_chunks_fixed/ERA5_1987-10-17.grib
Submitting request...

2026-08-30 10:47:59,249 INFO Request ID is 5e8b158e-b393-4ede-bfa6-ba9c83d1e118
INFO:ecmwf.datastores.legacy_client:Request ID is 5e8b158e-b393-4ede-bfa6-ba9c83d1e118
2026-08-30 10:48:01,267 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:48:35,408 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:48:52,755 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ff9f91b5055d0d92cafb8b78f39df66c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 105/793
======================================================================
Date: 1987-10-18
Output: ERA5_chunks_fixed/ERA5_1987-10-18.grib
Submitting request...

2026-08-30 10:48:59,319 INFO Request ID is f167a214-9f99-40ea-b298-6fb2ee235e3e
INFO:ecmwf.datastores.legacy_client:Request ID is f167a214-9f99-40ea-b298-6fb2ee235e3e
2026-08-30 10:48:59,554 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:49:23,317 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:49:34,947 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

be5307170985764323b3b1afc933d37a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 106/793
======================================================================
Date: 1987-10-31
Output: ERA5_chunks_fixed/ERA5_1987-10-31.grib
Submitting request...

2026-08-30 10:49:42,393 INFO Request ID is 1777186a-40a6-41fb-bea0-14d7d7a08aca
INFO:ecmwf.datastores.legacy_client:Request ID is 1777186a-40a6-41fb-bea0-14d7d7a08aca
2026-08-30 10:49:42,633 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:50:16,835 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:51:00,179 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2456c98ce4c5e34b166bb644fa1f61f9.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 107/793
======================================================================
Date: 1987-11-01
Output: ERA5_chunks_fixed/ERA5_1987-11-01.grib
Submitting request...

WARNING:multiurl.retry:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:multiurl.retry:Retrying in 120 seconds
2026-08-30 10:53:08,858 INFO Request ID is d4827e7c-2928-497a-950f-f385df55af25
INFO:ecmwf.datastores.legacy_client:Request ID is d4827e7c-2928-497a-950f-f385df55af25
2026-08-30 10:53:09,185 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:53:32,131 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:53:43,766 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

180bff4a2f505c13814ee8ee90923872.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 108/793
======================================================================
Date: 1987-11-02
Output: ERA5_chunks_fixed/ERA5_1987-11-02.grib
Submitting request...

2026-08-30 10:53:50,246 INFO Request ID is 647ff96b-0028-4c7c-8455-d8310fda1dca
INFO:ecmwf.datastores.legacy_client:Request ID is 647ff96b-0028-4c7c-8455-d8310fda1dca
2026-08-30 10:53:50,762 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:54:26,701 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:54:44,102 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fb0d0590ff9255026499c54c901e4a91.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 109/793
======================================================================
Date: 1987-11-11
Output: ERA5_chunks_fixed/ERA5_1987-11-11.grib
Submitting request...

2026-08-30 10:54:50,739 INFO Request ID is 3ddedf06-78ae-4f09-8c01-02e2ef9c3be8
INFO:ecmwf.datastores.legacy_client:Request ID is 3ddedf06-78ae-4f09-8c01-02e2ef9c3be8
2026-08-30 10:54:50,993 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:55:27,278 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:55:44,624 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f8c9a4e49f5302ae99578663b651c345.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 110/793
======================================================================
Date: 1987-11-12
Output: ERA5_chunks_fixed/ERA5_1987-11-12.grib
Submitting request...

2026-08-30 10:55:51,553 INFO Request ID is f8dac62c-aaf9-42dd-95d0-f06a84df74be
INFO:ecmwf.datastores.legacy_client:Request ID is f8dac62c-aaf9-42dd-95d0-f06a84df74be
2026-08-30 10:55:53,135 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:56:28,761 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:56:46,094 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

73b79372317cbf60dfcbe1d97c52b69d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 111/793
======================================================================
Date: 1987-12-19
Output: ERA5_chunks_fixed/ERA5_1987-12-19.grib
Submitting request...

2026-08-30 10:56:52,395 INFO Request ID is 4da5fe5a-ec01-4aa9-baf0-dc76a09baf35
INFO:ecmwf.datastores.legacy_client:Request ID is 4da5fe5a-ec01-4aa9-baf0-dc76a09baf35
2026-08-30 10:56:52,690 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:57:15,192 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:57:26,816 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2f932641dcc93ae53f0ae0ba3c52626d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 112/793
======================================================================
Date: 1987-12-20
Output: ERA5_chunks_fixed/ERA5_1987-12-20.grib
Submitting request...

2026-08-30 10:57:33,549 INFO Request ID is a8da929b-f816-4b96-a74b-951ee17abf54
INFO:ecmwf.datastores.legacy_client:Request ID is a8da929b-f816-4b96-a74b-951ee17abf54
2026-08-30 10:57:33,834 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:58:07,816 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:58:26,149 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6376a9843b32f703947755ec616f852e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 113/793
======================================================================
Date: 1987-12-21
Output: ERA5_chunks_fixed/ERA5_1987-12-21.grib
Submitting request...

2026-08-30 10:58:36,419 INFO Request ID is 9b9f8116-a41f-44f4-b578-5d5855bbbe96
INFO:ecmwf.datastores.legacy_client:Request ID is 9b9f8116-a41f-44f4-b578-5d5855bbbe96
2026-08-30 10:58:36,651 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:58:59,652 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 10:59:11,288 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

448dad0fc24da707c206ea6ee3a763e8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 114/793
======================================================================
Date: 1988-06-08
Output: ERA5_chunks_fixed/ERA5_1988-06-08.grib
Submitting request...

2026-08-30 10:59:17,648 INFO Request ID is 9bb2246d-2783-4807-b887-2a02bdbc394f
INFO:ecmwf.datastores.legacy_client:Request ID is 9bb2246d-2783-4807-b887-2a02bdbc394f
2026-08-30 10:59:17,891 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 10:59:51,902 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:00:09,244 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8ca8858e1c06cba26a05fb4da19c36de.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 115/793
======================================================================
Date: 1988-06-09
Output: ERA5_chunks_fixed/ERA5_1988-06-09.grib
Submitting request...

2026-08-30 11:00:19,305 INFO Request ID is 1ab0fb64-0e9c-4a76-bd64-4074b2cc2fa2
INFO:ecmwf.datastores.legacy_client:Request ID is 1ab0fb64-0e9c-4a76-bd64-4074b2cc2fa2
2026-08-30 11:00:19,581 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:00:42,839 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:00:54,509 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1d2387550b1f482f37912e9b221d4904.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 116/793
======================================================================
Date: 1988-07-17
Output: ERA5_chunks_fixed/ERA5_1988-07-17.grib
Submitting request...

2026-08-30 11:01:03,912 INFO Request ID is cc5af323-c780-4eec-84e5-110646f75641
INFO:ecmwf.datastores.legacy_client:Request ID is cc5af323-c780-4eec-84e5-110646f75641
2026-08-30 11:01:04,459 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:01:42,835 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:02:26,214 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a6c48e4a9a2fb5cd42cab5bf06f06ac8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 117/793
======================================================================
Date: 1988-08-02
Output: ERA5_chunks_fixed/ERA5_1988-08-02.grib
Submitting request...

2026-08-30 11:02:33,783 INFO Request ID is b5583540-1533-4242-b1b1-cdf38511db52
INFO:ecmwf.datastores.legacy_client:Request ID is b5583540-1533-4242-b1b1-cdf38511db52
2026-08-30 11:02:34,056 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:03:08,651 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:03:26,019 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6dca69d2540f696ab77cc26b2f568f63.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 118/793
======================================================================
Date: 1988-08-03
Output: ERA5_chunks_fixed/ERA5_1988-08-03.grib
Submitting request...

2026-08-30 11:03:34,261 INFO Request ID is 1fdc1a7c-828e-41b9-a1b4-94ddbe1c6148
INFO:ecmwf.datastores.legacy_client:Request ID is 1fdc1a7c-828e-41b9-a1b4-94ddbe1c6148
2026-08-30 11:03:34,771 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:04:12,070 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:04:55,751 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a74f506ce5699788316fd3dfa2f6c70.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 119/793
======================================================================
Date: 1988-08-04
Output: ERA5_chunks_fixed/ERA5_1988-08-04.grib
Submitting request...

2026-08-30 11:05:03,714 INFO Request ID is cd532313-1aa0-4daa-a63f-6e35f3ca16d7
INFO:ecmwf.datastores.legacy_client:Request ID is cd532313-1aa0-4daa-a63f-6e35f3ca16d7
2026-08-30 11:05:03,973 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:05:37,895 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:05:55,232 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b62d88ac1600f9bae86037f8bd195e70.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 120/793
======================================================================
Date: 1988-08-05
Output: ERA5_chunks_fixed/ERA5_1988-08-05.grib
Submitting request...

2026-08-30 11:06:02,244 INFO Request ID is 306d8194-07ff-4e41-bfff-659413e3fd61
INFO:ecmwf.datastores.legacy_client:Request ID is 306d8194-07ff-4e41-bfff-659413e3fd61
2026-08-30 11:06:02,496 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:06:25,009 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:06:53,970 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fc3f48ebfc6452dcd9d61eba35dbe81e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 121/793
======================================================================
Date: 1988-10-01
Output: ERA5_chunks_fixed/ERA5_1988-10-01.grib
Submitting request...

2026-08-30 11:07:00,682 INFO Request ID is 2bb62e6f-0509-4385-9ed6-b0a493009179
INFO:ecmwf.datastores.legacy_client:Request ID is 2bb62e6f-0509-4385-9ed6-b0a493009179
2026-08-30 11:07:01,018 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:07:39,932 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:07:57,270 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fae6637a9584316162749b0bb9f603ba.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 122/793
======================================================================
Date: 1988-10-02
Output: ERA5_chunks_fixed/ERA5_1988-10-02.grib
Submitting request...

2026-08-30 11:08:03,687 INFO Request ID is bab696d7-2c13-434a-bcd7-b5966ad876cb
INFO:ecmwf.datastores.legacy_client:Request ID is bab696d7-2c13-434a-bcd7-b5966ad876cb
2026-08-30 11:08:03,917 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:08:18,296 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:08:55,098 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8bc711d1aa378d94566c12a801b0e489.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 123/793
======================================================================
Date: 1988-11-15
Output: ERA5_chunks_fixed/ERA5_1988-11-15.grib
Submitting request...

2026-08-30 11:09:02,984 INFO Request ID is 31a4d3e2-db4e-4ac3-b004-886462716df6
INFO:ecmwf.datastores.legacy_client:Request ID is 31a4d3e2-db4e-4ac3-b004-886462716df6
2026-08-30 11:09:03,251 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:09:25,825 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:09:56,706 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e4a81b1ad44b728046ee0368394d29e7.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 124/793
======================================================================
Date: 1988-11-23
Output: ERA5_chunks_fixed/ERA5_1988-11-23.grib
Submitting request...

2026-08-30 11:10:03,257 INFO Request ID is d09d9d3f-4413-4d94-b423-fd4f2f5c139c
INFO:ecmwf.datastores.legacy_client:Request ID is d09d9d3f-4413-4d94-b423-fd4f2f5c139c
2026-08-30 11:10:03,524 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:10:39,926 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:10:57,558 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4228b37877c34dc567449e9ec5607e05.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 125/793
======================================================================
Date: 1988-11-24
Output: ERA5_chunks_fixed/ERA5_1988-11-24.grib
Submitting request...

2026-08-30 11:11:06,448 INFO Request ID is 00929fda-7a28-4aea-8094-d3225a3cc85b
INFO:ecmwf.datastores.legacy_client:Request ID is 00929fda-7a28-4aea-8094-d3225a3cc85b
2026-08-30 11:11:06,745 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:11:21,452 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:11:29,356 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6ee65f933d0b4e1abb615b535172a9a4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 126/793
======================================================================
Date: 1988-11-25
Output: ERA5_chunks_fixed/ERA5_1988-11-25.grib
Submitting request...

2026-08-30 11:11:37,263 INFO Request ID is c6fc8165-8f1f-428d-9726-5e3877c20c02
INFO:ecmwf.datastores.legacy_client:Request ID is c6fc8165-8f1f-428d-9726-5e3877c20c02
2026-08-30 11:11:37,495 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:12:00,231 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:12:11,890 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a788d163acf9d108668017149e11575b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 127/793
======================================================================
Date: 1988-11-27
Output: ERA5_chunks_fixed/ERA5_1988-11-27.grib
Submitting request...

2026-08-30 11:12:19,072 INFO Request ID is d68f62b0-dcb2-4205-a6a4-c6698d750e21
INFO:ecmwf.datastores.legacy_client:Request ID is d68f62b0-dcb2-4205-a6a4-c6698d750e21
2026-08-30 11:12:19,380 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:12:54,843 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:13:12,400 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6b6afcae7269fa326cf9846062279faa.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 128/793
======================================================================
Date: 1988-11-28
Output: ERA5_chunks_fixed/ERA5_1988-11-28.grib
Submitting request...

2026-08-30 11:13:19,119 INFO Request ID is 3dbfeecf-56c0-467b-a08d-69922518e314
INFO:ecmwf.datastores.legacy_client:Request ID is 3dbfeecf-56c0-467b-a08d-69922518e314
2026-08-30 11:13:19,370 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:13:41,873 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:14:10,845 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f5ed6ede6a05b37afd33ecfa41903369.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 129/793
======================================================================
Date: 1988-12-06
Output: ERA5_chunks_fixed/ERA5_1988-12-06.grib
Submitting request...

2026-08-30 11:14:18,122 INFO Request ID is a9a83c2f-d40b-4e97-91ff-5f20eebcce42
INFO:ecmwf.datastores.legacy_client:Request ID is a9a83c2f-d40b-4e97-91ff-5f20eebcce42
2026-08-30 11:14:18,360 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:14:52,276 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:15:09,605 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2e5ea89fb66bc8fbb351cf69c4487cf2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 130/793
======================================================================
Date: 1988-12-07
Output: ERA5_chunks_fixed/ERA5_1988-12-07.grib
Submitting request...

2026-08-30 11:15:19,375 INFO Request ID is 5eef8e81-1ce4-48c0-908b-dfdd9c2dd235
INFO:ecmwf.datastores.legacy_client:Request ID is 5eef8e81-1ce4-48c0-908b-dfdd9c2dd235
2026-08-30 11:15:19,612 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:15:44,893 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:15:57,228 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b8e6e48bc144dbba8e012410acaaee86.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 131/793
======================================================================
Date: 1989-05-23
Output: ERA5_chunks_fixed/ERA5_1989-05-23.grib
Submitting request...

2026-08-30 11:16:03,643 INFO Request ID is 0d4922d0-741e-4dba-b0c3-4aedc61a2fdb
INFO:ecmwf.datastores.legacy_client:Request ID is 0d4922d0-741e-4dba-b0c3-4aedc61a2fdb
2026-08-30 11:16:03,886 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:16:37,926 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:16:55,261 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ca134ce60dc3f5b98d5281b53bac616e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 132/793
======================================================================
Date: 1989-05-24
Output: ERA5_chunks_fixed/ERA5_1989-05-24.grib
Submitting request...

2026-08-30 11:17:01,947 INFO Request ID is 99755108-95b0-4b36-936d-a616cb1d3643
INFO:ecmwf.datastores.legacy_client:Request ID is 99755108-95b0-4b36-936d-a616cb1d3643
2026-08-30 11:17:02,284 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:17:16,906 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:17:55,249 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

32a41a9859c77a19353517b92e48ef9a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 133/793
======================================================================
Date: 1989-05-25
Output: ERA5_chunks_fixed/ERA5_1989-05-25.grib
Submitting request...

2026-08-30 11:18:01,806 INFO Request ID is 02881a18-9a24-49a8-869b-ce46a29ea116
INFO:ecmwf.datastores.legacy_client:Request ID is 02881a18-9a24-49a8-869b-ce46a29ea116
2026-08-30 11:18:02,149 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:18:27,539 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:18:56,500 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9774ce923ddaef3eeaa51d125b463ea8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 134/793
======================================================================
Date: 1989-05-26
Output: ERA5_chunks_fixed/ERA5_1989-05-26.grib
Submitting request...

2026-08-30 11:19:02,923 INFO Request ID is 568bb2e6-7142-402b-b01f-e3b25d6a8d89
INFO:ecmwf.datastores.legacy_client:Request ID is 568bb2e6-7142-402b-b01f-e3b25d6a8d89
2026-08-30 11:19:03,161 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:19:25,611 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:20:21,104 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a9e390eef04c732eb1f9cb3c7fc52853.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 135/793
======================================================================
Date: 1989-06-12
Output: ERA5_chunks_fixed/ERA5_1989-06-12.grib
Submitting request...

2026-08-30 11:20:27,626 INFO Request ID is 74845694-6e67-4853-91e6-7e67aca44538
INFO:ecmwf.datastores.legacy_client:Request ID is 74845694-6e67-4853-91e6-7e67aca44538
2026-08-30 11:20:28,467 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:20:44,671 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:20:52,494 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c2e08014d589f593ac90ef96c1df2a4e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 136/793
======================================================================
Date: 1989-06-13
Output: ERA5_chunks_fixed/ERA5_1989-06-13.grib
Submitting request...

2026-08-30 11:20:58,603 INFO Request ID is 72baaf2e-a1b0-4259-af99-d9ee5abc8c8f
INFO:ecmwf.datastores.legacy_client:Request ID is 72baaf2e-a1b0-4259-af99-d9ee5abc8c8f
2026-08-30 11:20:58,830 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:21:32,654 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:22:15,940 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c9858db9c53b22778e11991496154d9d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 137/793
======================================================================
Date: 1989-07-21
Output: ERA5_chunks_fixed/ERA5_1989-07-21.grib
Submitting request...

2026-08-30 11:22:24,178 INFO Request ID is 48a24ea5-59ca-4878-9429-b2027dd81736
INFO:ecmwf.datastores.legacy_client:Request ID is 48a24ea5-59ca-4878-9429-b2027dd81736
2026-08-30 11:22:24,405 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:22:58,353 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:23:15,828 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

80d08f6fe4dbb0f0521a3e86ffb79c23.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 138/793
======================================================================
Date: 1989-07-22
Output: ERA5_chunks_fixed/ERA5_1989-07-22.grib
Submitting request...

2026-08-30 11:23:23,809 INFO Request ID is 354fc61c-529b-4c7a-b6ee-1bd998b0740a
INFO:ecmwf.datastores.legacy_client:Request ID is 354fc61c-529b-4c7a-b6ee-1bd998b0740a
2026-08-30 11:23:24,066 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:23:48,828 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:24:01,311 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

262e2564f05e4a51dacba95a232a6758.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 139/793
======================================================================
Date: 1989-07-23
Output: ERA5_chunks_fixed/ERA5_1989-07-23.grib
Submitting request...

2026-08-30 11:24:07,648 INFO Request ID is 00e22be4-f5eb-4983-a2cc-2e27fcea5eac
INFO:ecmwf.datastores.legacy_client:Request ID is 00e22be4-f5eb-4983-a2cc-2e27fcea5eac
2026-08-30 11:24:08,678 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:24:42,516 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:24:59,905 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

61fa956109b1fa865b7d24f8d789becc.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 140/793
======================================================================
Date: 1989-07-24
Output: ERA5_chunks_fixed/ERA5_1989-07-24.grib
Submitting request...

2026-08-30 11:25:07,852 INFO Request ID is b2b5c302-c913-4d90-89c6-d28758a20559
INFO:ecmwf.datastores.legacy_client:Request ID is b2b5c302-c913-4d90-89c6-d28758a20559
2026-08-30 11:25:08,139 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:25:30,573 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:25:43,037 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2b536c2b0aa2d7f4d9c5c2d7051df0e8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 141/793
======================================================================
Date: 1989-08-16
Output: ERA5_chunks_fixed/ERA5_1989-08-16.grib
Submitting request...

2026-08-30 11:25:50,145 INFO Request ID is 28e852ae-b88e-4a45-a6df-75a2dd519a1f
INFO:ecmwf.datastores.legacy_client:Request ID is 28e852ae-b88e-4a45-a6df-75a2dd519a1f
2026-08-30 11:25:50,383 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:26:29,604 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:26:47,122 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

80c95487865112439380eb694ac52c6c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 142/793
======================================================================
Date: 1989-10-17
Output: ERA5_chunks_fixed/ERA5_1989-10-17.grib
Submitting request...

2026-08-30 11:26:54,010 INFO Request ID is 01f0038c-02a1-4b2c-ad2f-509adb9328f1
INFO:ecmwf.datastores.legacy_client:Request ID is 01f0038c-02a1-4b2c-ad2f-509adb9328f1
2026-08-30 11:26:54,281 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:28:11,336 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

705a2bb7b518aad3f76e27b9cb1d249d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 143/793
======================================================================
Date: 1989-11-01
Output: ERA5_chunks_fixed/ERA5_1989-11-01.grib
Submitting request...

2026-08-30 11:28:28,211 INFO Request ID is a6339cc4-8ec8-471a-8141-f3bd1dfa7fca
INFO:ecmwf.datastores.legacy_client:Request ID is a6339cc4-8ec8-471a-8141-f3bd1dfa7fca
2026-08-30 11:28:28,461 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:29:02,303 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

37ff7186df11331ddc71597efdb9a70f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 144/793
======================================================================
Date: 1989-11-02
Output: ERA5_chunks_fixed/ERA5_1989-11-02.grib
Submitting request...

2026-08-30 11:29:11,650 INFO Request ID is e27be568-c9fe-43e7-a134-9ad91c9b5395
INFO:ecmwf.datastores.legacy_client:Request ID is e27be568-c9fe-43e7-a134-9ad91c9b5395
2026-08-30 11:29:11,906 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:29:45,742 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:30:03,063 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

431f4ecc51f62547491e0c68967b7822.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 145/793
======================================================================
Date: 1989-11-03
Output: ERA5_chunks_fixed/ERA5_1989-11-03.grib
Submitting request...

2026-08-30 11:30:10,419 INFO Request ID is defb8d0a-6644-41b8-8959-baf576a31c19
INFO:ecmwf.datastores.legacy_client:Request ID is defb8d0a-6644-41b8-8959-baf576a31c19
2026-08-30 11:30:10,670 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:30:46,570 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:31:29,769 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4d7e75d69a0a71b44fd9a5e9ceb0089b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 146/793
======================================================================
Date: 1989-11-04
Output: ERA5_chunks_fixed/ERA5_1989-11-04.grib
Submitting request...

2026-08-30 11:31:36,248 INFO Request ID is 632c5ed9-0c1c-4f09-96ed-8f2d2950f142
INFO:ecmwf.datastores.legacy_client:Request ID is 632c5ed9-0c1c-4f09-96ed-8f2d2950f142
2026-08-30 11:31:36,498 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:31:59,454 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:32:11,101 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ccd1e2af1bd4287ad0833d848cac1ecb.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 147/793
======================================================================
Date: 1989-11-08
Output: ERA5_chunks_fixed/ERA5_1989-11-08.grib
Submitting request...

2026-08-30 11:32:17,768 INFO Request ID is 12fa37b2-9f37-425b-aaa0-78a215e16094
INFO:ecmwf.datastores.legacy_client:Request ID is 12fa37b2-9f37-425b-aaa0-78a215e16094
2026-08-30 11:32:18,024 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:32:40,427 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:32:52,075 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a3fd3b69531878365ce1e67c0e257773.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 148/793
======================================================================
Date: 1989-11-16
Output: ERA5_chunks_fixed/ERA5_1989-11-16.grib
Submitting request...

2026-08-30 11:32:58,663 INFO Request ID is 63c3110f-04db-41ed-965c-b5b0d2865751
INFO:ecmwf.datastores.legacy_client:Request ID is 63c3110f-04db-41ed-965c-b5b0d2865751
2026-08-30 11:32:58,892 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:33:37,007 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

711d2aa8d95fbfb2fee6eba14d8dbc1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 149/793
======================================================================
Date: 1989-11-17
Output: ERA5_chunks_fixed/ERA5_1989-11-17.grib
Submitting request...

2026-08-30 11:33:48,249 INFO Request ID is 11f4e7a7-1016-4cb7-87c3-e58fe23e57f4
INFO:ecmwf.datastores.legacy_client:Request ID is 11f4e7a7-1016-4cb7-87c3-e58fe23e57f4
2026-08-30 11:33:48,478 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:34:23,717 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:34:41,061 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3cf005b03ba68df76f351db9e3e3db99.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 150/793
======================================================================
Date: 1989-11-18
Output: ERA5_chunks_fixed/ERA5_1989-11-18.grib
Submitting request...

2026-08-30 11:34:47,625 INFO Request ID is bbdb9725-a429-42bf-8015-5d8124b35a16
INFO:ecmwf.datastores.legacy_client:Request ID is bbdb9725-a429-42bf-8015-5d8124b35a16
2026-08-30 11:34:47,855 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:35:22,717 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:35:40,067 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e2ae15d532a402221fa89d93c69958ad.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 151/793
======================================================================
Date: 1989-11-19
Output: ERA5_chunks_fixed/ERA5_1989-11-19.grib
Submitting request...

2026-08-30 11:35:46,803 INFO Request ID is 6d018517-70d9-4174-b26a-578cc920d41c
INFO:ecmwf.datastores.legacy_client:Request ID is 6d018517-70d9-4174-b26a-578cc920d41c
2026-08-30 11:35:47,039 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:36:25,413 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:36:42,723 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

89bbf4417c63c5c4e6b1a886e93b14d7.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 152/793
======================================================================
Date: 1990-05-04
Output: ERA5_chunks_fixed/ERA5_1990-05-04.grib
Submitting request...

2026-08-30 11:36:49,313 INFO Request ID is a684b13a-e4ed-426d-ad1c-548f50467eb5
INFO:ecmwf.datastores.legacy_client:Request ID is a684b13a-e4ed-426d-ad1c-548f50467eb5
2026-08-30 11:36:50,299 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:37:27,171 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4b3d9cb4d993ab861134418c4897a774.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 153/793
======================================================================
Date: 1990-05-05
Output: ERA5_chunks_fixed/ERA5_1990-05-05.grib
Submitting request...

2026-08-30 11:37:34,024 INFO Request ID is 6a9c5d5f-a8c2-4fef-8492-fb5440c2bcdf
INFO:ecmwf.datastores.legacy_client:Request ID is 6a9c5d5f-a8c2-4fef-8492-fb5440c2bcdf
2026-08-30 11:37:34,253 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:38:12,087 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:38:31,483 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

34a6846bb63a3222eaa9f12d00c4298f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 154/793
======================================================================
Date: 1990-05-06
Output: ERA5_chunks_fixed/ERA5_1990-05-06.grib
Submitting request...

2026-08-30 11:38:37,620 INFO Request ID is 8a85f344-d3d7-473f-b216-d7af3e0cd64f
INFO:ecmwf.datastores.legacy_client:Request ID is 8a85f344-d3d7-473f-b216-d7af3e0cd64f
2026-08-30 11:38:37,875 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:39:02,325 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:39:14,032 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e75f974328d8db7ae8559e7ddfc52e15.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 155/793
======================================================================
Date: 1990-05-07
Output: ERA5_chunks_fixed/ERA5_1990-05-07.grib
Submitting request...

2026-08-30 11:39:20,406 INFO Request ID is a81c8ed5-67f4-40f3-9c4b-364b866523ea
INFO:ecmwf.datastores.legacy_client:Request ID is a81c8ed5-67f4-40f3-9c4b-364b866523ea
2026-08-30 11:39:20,633 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:39:43,082 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:39:54,721 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c1a35d27367490743a32e1f55d883f3e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 156/793
======================================================================
Date: 1990-05-08
Output: ERA5_chunks_fixed/ERA5_1990-05-08.grib
Submitting request...

2026-08-30 11:40:01,339 INFO Request ID is 4d2984d5-4add-4751-9046-ed2b5c4ebf2a
INFO:ecmwf.datastores.legacy_client:Request ID is 4d2984d5-4add-4751-9046-ed2b5c4ebf2a
2026-08-30 11:40:01,613 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:40:36,718 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:40:54,048 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f851ba23e49b343c30414f05da66949f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 157/793
======================================================================
Date: 1990-05-09
Output: ERA5_chunks_fixed/ERA5_1990-05-09.grib
Submitting request...

2026-08-30 11:41:00,869 INFO Request ID is e1cadffb-8fc8-445c-a2a4-839634b4188e
INFO:ecmwf.datastores.legacy_client:Request ID is e1cadffb-8fc8-445c-a2a4-839634b4188e
2026-08-30 11:41:01,115 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:41:35,002 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:41:52,334 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

654785493c3676825ec97dc346c9fcbf.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 158/793
======================================================================
Date: 1990-06-13
Output: ERA5_chunks_fixed/ERA5_1990-06-13.grib
Submitting request...

2026-08-30 11:41:58,647 INFO Request ID is 9ec7a20f-7536-4f89-955d-bbb6b3e54da2
INFO:ecmwf.datastores.legacy_client:Request ID is 9ec7a20f-7536-4f89-955d-bbb6b3e54da2
2026-08-30 11:41:58,895 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:42:34,019 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fd0377d649833b594dd1126e40faf1bc.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 159/793
======================================================================
Date: 1990-06-14
Output: ERA5_chunks_fixed/ERA5_1990-06-14.grib
Submitting request...

2026-08-30 11:42:40,591 INFO Request ID is 6e538aa9-e538-4a57-8591-1487cc1be30b
INFO:ecmwf.datastores.legacy_client:Request ID is 6e538aa9-e538-4a57-8591-1487cc1be30b
2026-08-30 11:42:43,755 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:43:07,365 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:43:37,173 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2455680440e3ca1fa99327375298da17.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 160/793
======================================================================
Date: 1990-08-14
Output: ERA5_chunks_fixed/ERA5_1990-08-14.grib
Submitting request...

2026-08-30 11:43:44,942 INFO Request ID is b16c3be2-3485-45ff-a661-64d81f87849b
INFO:ecmwf.datastores.legacy_client:Request ID is b16c3be2-3485-45ff-a661-64d81f87849b
2026-08-30 11:43:45,468 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:43:59,924 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:44:07,771 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

32028aa01cf139890bf149b00baa64a2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 161/793
======================================================================
Date: 1990-08-15
Output: ERA5_chunks_fixed/ERA5_1990-08-15.grib
Submitting request...

2026-08-30 11:44:14,437 INFO Request ID is d87ce4a0-bd25-4524-b1ae-693298031a42
INFO:ecmwf.datastores.legacy_client:Request ID is d87ce4a0-bd25-4524-b1ae-693298031a42
2026-08-30 11:44:14,697 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:44:29,171 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:44:48,712 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

300b42826fa0fcdd9bb6315763bd939.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 162/793
======================================================================
Date: 1990-08-16
Output: ERA5_chunks_fixed/ERA5_1990-08-16.grib
Submitting request...

2026-08-30 11:44:59,763 INFO Request ID is d5731c14-c580-4167-8938-2e67843068ef
INFO:ecmwf.datastores.legacy_client:Request ID is d5731c14-c580-4167-8938-2e67843068ef
2026-08-30 11:45:00,054 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:45:34,220 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:45:51,554 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

65580afff2c2a01904e14f65344f0e4b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 163/793
======================================================================
Date: 1990-08-20
Output: ERA5_chunks_fixed/ERA5_1990-08-20.grib
Submitting request...

2026-08-30 11:46:00,623 INFO Request ID is d42f748d-3742-428a-869e-97a5c2aeb162
INFO:ecmwf.datastores.legacy_client:Request ID is d42f748d-3742-428a-869e-97a5c2aeb162
2026-08-30 11:46:00,874 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:46:34,808 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:46:52,155 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

482b2e580751d2186c5b9b1fdf23b395.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 164/793
======================================================================
Date: 1990-08-21
Output: ERA5_chunks_fixed/ERA5_1990-08-21.grib
Submitting request...

2026-08-30 11:46:58,724 INFO Request ID is 8b81f323-8635-4c95-991b-bd954bc9a4c0
INFO:ecmwf.datastores.legacy_client:Request ID is 8b81f323-8635-4c95-991b-bd954bc9a4c0
2026-08-30 11:46:58,988 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:47:32,993 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:47:50,325 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

539b21b433ae9735f7ada84c35eb9483.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 165/793
======================================================================
Date: 1990-08-22
Output: ERA5_chunks_fixed/ERA5_1990-08-22.grib
Submitting request...

2026-08-30 11:47:56,946 INFO Request ID is b0d813fb-0b64-4324-a62a-d7d4915512b9
INFO:ecmwf.datastores.legacy_client:Request ID is b0d813fb-0b64-4324-a62a-d7d4915512b9
2026-08-30 11:47:57,189 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:48:11,624 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:48:31,267 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d2d33962232656d2b23fbe8c2d2dc4a1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 166/793
======================================================================
Date: 1990-08-23
Output: ERA5_chunks_fixed/ERA5_1990-08-23.grib
Submitting request...

2026-08-30 11:48:37,765 INFO Request ID is 52bd0e4c-67f5-4419-a996-8e0738899530
INFO:ecmwf.datastores.legacy_client:Request ID is 52bd0e4c-67f5-4419-a996-8e0738899530
2026-08-30 11:48:38,018 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:49:00,241 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:49:29,223 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

bb61a7749b256e64e2616945f990f297.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 167/793
======================================================================
Date: 1990-09-03
Output: ERA5_chunks_fixed/ERA5_1990-09-03.grib
Submitting request...

2026-08-30 11:49:35,814 INFO Request ID is 67a013e2-1161-4048-842b-034707d542d8
INFO:ecmwf.datastores.legacy_client:Request ID is 67a013e2-1161-4048-842b-034707d542d8
2026-08-30 11:49:36,101 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:50:12,415 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:50:29,759 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fa054750869defdd1affcee8b1f3526d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 168/793
======================================================================
Date: 1990-10-06
Output: ERA5_chunks_fixed/ERA5_1990-10-06.grib
Submitting request...

2026-08-30 11:50:36,232 INFO Request ID is a0869364-feb6-46a5-bfde-4986128572e1
INFO:ecmwf.datastores.legacy_client:Request ID is a0869364-feb6-46a5-bfde-4986128572e1
2026-08-30 11:50:36,480 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:51:12,540 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:51:29,919 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d89de498827de79506243b013ef122d4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 169/793
======================================================================
Date: 1990-10-07
Output: ERA5_chunks_fixed/ERA5_1990-10-07.grib
Submitting request...

2026-08-30 11:51:36,758 INFO Request ID is f36fe1eb-bbe2-4abd-9c0b-95ae50c5c59e
INFO:ecmwf.datastores.legacy_client:Request ID is f36fe1eb-bbe2-4abd-9c0b-95ae50c5c59e
2026-08-30 11:51:36,986 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:51:59,319 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:52:28,346 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2c06510e379d251b4d5d961629efe112.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 170/793
======================================================================
Date: 1990-10-31
Output: ERA5_chunks_fixed/ERA5_1990-10-31.grib
Submitting request...

2026-08-30 11:52:38,514 INFO Request ID is 5d64db9b-a912-4073-961f-94b89f1f8fd2
INFO:ecmwf.datastores.legacy_client:Request ID is 5d64db9b-a912-4073-961f-94b89f1f8fd2
2026-08-30 11:52:39,582 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:53:13,440 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:53:31,811 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fe600e73fa3b88960a1be29b24f50d8f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 171/793
======================================================================
Date: 1990-11-01
Output: ERA5_chunks_fixed/ERA5_1990-11-01.grib
Submitting request...

2026-08-30 11:53:41,570 INFO Request ID is 95bfadd4-6dfa-49da-b740-2df138b446f8
INFO:ecmwf.datastores.legacy_client:Request ID is 95bfadd4-6dfa-49da-b740-2df138b446f8
2026-08-30 11:53:41,811 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:54:05,627 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:54:34,593 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2597853a27d869a001427ca4818cc0dd.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 172/793
======================================================================
Date: 1990-11-02
Output: ERA5_chunks_fixed/ERA5_1990-11-02.grib
Submitting request...

2026-08-30 11:54:42,851 INFO Request ID is 847b6c81-0acf-463b-9423-af99b0c7f9ef
INFO:ecmwf.datastores.legacy_client:Request ID is 847b6c81-0acf-463b-9423-af99b0c7f9ef
2026-08-30 11:54:43,100 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:55:17,124 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:55:34,466 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

eaf6251fff1a8b6a54308e2ffc676b71.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 173/793
======================================================================
Date: 1990-11-03
Output: ERA5_chunks_fixed/ERA5_1990-11-03.grib
Submitting request...

2026-08-30 11:55:40,878 INFO Request ID is 223508ad-00ef-441d-9dc5-ed239fefa89c
INFO:ecmwf.datastores.legacy_client:Request ID is 223508ad-00ef-441d-9dc5-ed239fefa89c
2026-08-30 11:55:41,133 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:56:15,081 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:56:32,405 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7a3664691d9eb5f587f69a5106815530.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 174/793
======================================================================
Date: 1990-12-14
Output: ERA5_chunks_fixed/ERA5_1990-12-14.grib
Submitting request...

2026-08-30 11:56:39,755 INFO Request ID is e2c7ffb2-954b-4219-95d1-6c8286f318a5
INFO:ecmwf.datastores.legacy_client:Request ID is e2c7ffb2-954b-4219-95d1-6c8286f318a5
2026-08-30 11:56:40,446 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:57:04,423 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:57:33,391 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

adc136bebe5a57b23d7710c3fc62cc3c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 175/793
======================================================================
Date: 1990-12-15
Output: ERA5_chunks_fixed/ERA5_1990-12-15.grib
Submitting request...

2026-08-30 11:57:40,335 INFO Request ID is 5557feba-8ff3-4358-af4b-69517f93ad4e
INFO:ecmwf.datastores.legacy_client:Request ID is 5557feba-8ff3-4358-af4b-69517f93ad4e
2026-08-30 11:57:40,572 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:58:14,493 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

73b4e21fd9c0ac80db634fbed95392ad.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 176/793
======================================================================
Date: 1990-12-16
Output: ERA5_chunks_fixed/ERA5_1990-12-16.grib
Submitting request...

2026-08-30 11:58:21,037 INFO Request ID is 2a4cc8bd-ed1b-4c6f-bbba-250584313a87
INFO:ecmwf.datastores.legacy_client:Request ID is 2a4cc8bd-ed1b-4c6f-bbba-250584313a87
2026-08-30 11:58:21,286 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:58:43,598 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:58:55,248 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7274c0d5d5b319bca3c517cb1e37dcab.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 177/793
======================================================================
Date: 1990-12-17
Output: ERA5_chunks_fixed/ERA5_1990-12-17.grib
Submitting request...

2026-08-30 11:59:01,865 INFO Request ID is aa3c43dc-d6a1-4409-908c-13fc56a1cde3
INFO:ecmwf.datastores.legacy_client:Request ID is aa3c43dc-d6a1-4409-908c-13fc56a1cde3
2026-08-30 11:59:02,115 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 11:59:24,373 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 11:59:53,354 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f9c2d3059720252f5374e1f62feabdf2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 178/793
======================================================================
Date: 1991-04-24
Output: ERA5_chunks_fixed/ERA5_1991-04-24.grib
Submitting request...

2026-08-30 12:00:00,633 INFO Request ID is 1dea73ca-0b32-4a39-8a7e-1721e1653fa7
INFO:ecmwf.datastores.legacy_client:Request ID is 1dea73ca-0b32-4a39-8a7e-1721e1653fa7
2026-08-30 12:00:01,149 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:00:27,268 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:00:38,954 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7c57182e8cbb6579b8b06fe106621639.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 179/793
======================================================================
Date: 1991-04-25
Output: ERA5_chunks_fixed/ERA5_1991-04-25.grib
Submitting request...

2026-08-30 12:00:52,853 INFO Request ID is 2eb89777-6382-44a2-a4dd-965aff71c235
INFO:ecmwf.datastores.legacy_client:Request ID is 2eb89777-6382-44a2-a4dd-965aff71c235
2026-08-30 12:00:53,152 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:01:28,466 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:01:45,821 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8ca99bdf868eaf23a21d38a579d388cb.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 180/793
======================================================================
Date: 1991-04-26
Output: ERA5_chunks_fixed/ERA5_1991-04-26.grib
Submitting request...

2026-08-30 12:02:00,448 INFO Request ID is 2d84e57a-5006-4ec4-91ff-4940d553d7ab
INFO:ecmwf.datastores.legacy_client:Request ID is 2d84e57a-5006-4ec4-91ff-4940d553d7ab
2026-08-30 12:02:00,699 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:02:35,498 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b66b6d1b73ebb4bcf22476e5ff88a856.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 181/793
======================================================================
Date: 1991-04-27
Output: ERA5_chunks_fixed/ERA5_1991-04-27.grib
Submitting request...

2026-08-30 12:02:44,284 INFO Request ID is 20548cdc-dc00-4f65-86e0-bc1e58227d57
INFO:ecmwf.datastores.legacy_client:Request ID is 20548cdc-dc00-4f65-86e0-bc1e58227d57
2026-08-30 12:02:44,547 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:03:18,482 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:03:38,149 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9c999942a63450190418b62bdb022081.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 182/793
======================================================================
Date: 1991-04-28
Output: ERA5_chunks_fixed/ERA5_1991-04-28.grib
Submitting request...

2026-08-30 12:03:44,902 INFO Request ID is 296383c1-4cd6-4211-abd8-1c624f452c28
INFO:ecmwf.datastores.legacy_client:Request ID is 296383c1-4cd6-4211-abd8-1c624f452c28
2026-08-30 12:03:45,189 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:04:19,089 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:05:41,015 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

59751ad621ce04796b58e5bafac527ad.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 183/793
======================================================================
Date: 1991-04-29
Output: ERA5_chunks_fixed/ERA5_1991-04-29.grib
Submitting request...

2026-08-30 12:05:47,929 INFO Request ID is 4da78e84-8120-4a4c-a5fa-ee74d620e5a9
INFO:ecmwf.datastores.legacy_client:Request ID is 4da78e84-8120-4a4c-a5fa-ee74d620e5a9
2026-08-30 12:05:48,202 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:06:11,080 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:06:22,766 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

418865f4daf9f78e5b4378f18b2a9814.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 184/793
======================================================================
Date: 1991-05-31
Output: ERA5_chunks_fixed/ERA5_1991-05-31.grib
Submitting request...

2026-08-30 12:06:30,899 INFO Request ID is bb7eb0ce-0f9b-4073-9db6-9103ac26d7d1
INFO:ecmwf.datastores.legacy_client:Request ID is bb7eb0ce-0f9b-4073-9db6-9103ac26d7d1
2026-08-30 12:06:31,133 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:06:57,096 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:07:32,522 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

df173718f146a1e338283311734a96d4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 185/793
======================================================================
Date: 1991-06-01
Output: ERA5_chunks_fixed/ERA5_1991-06-01.grib
Submitting request...

2026-08-30 12:07:54,681 INFO Request ID is fe0bdc72-2127-4cc4-9e44-b0265e47ae62
INFO:ecmwf.datastores.legacy_client:Request ID is fe0bdc72-2127-4cc4-9e44-b0265e47ae62
2026-08-30 12:07:54,952 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:08:30,505 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d8f48e15d03f00e9fdf2fba8aadbde74.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 186/793
======================================================================
Date: 1991-07-27
Output: ERA5_chunks_fixed/ERA5_1991-07-27.grib
Submitting request...

2026-08-30 12:08:38,332 INFO Request ID is 97280fd4-0e16-40c6-8f34-9e91cf9905a9
INFO:ecmwf.datastores.legacy_client:Request ID is 97280fd4-0e16-40c6-8f34-9e91cf9905a9
2026-08-30 12:08:38,815 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:09:13,095 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:09:32,288 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4d642812e60e91272ca34b262d655bd.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 187/793
======================================================================
Date: 1991-07-28
Output: ERA5_chunks_fixed/ERA5_1991-07-28.grib
Submitting request...

2026-08-30 12:09:38,819 INFO Request ID is 1f439baf-df81-4cdd-9e26-6dc0b96207c9
INFO:ecmwf.datastores.legacy_client:Request ID is 1f439baf-df81-4cdd-9e26-6dc0b96207c9
2026-08-30 12:09:39,054 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:10:13,223 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:10:33,840 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1064906be07adccd6eb28d67ff2daaff.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 188/793
======================================================================
Date: 1991-07-29
Output: ERA5_chunks_fixed/ERA5_1991-07-29.grib
Submitting request...

2026-08-30 12:10:40,383 INFO Request ID is c0a2f452-e680-4183-8f56-0ff5b73f89b3
INFO:ecmwf.datastores.legacy_client:Request ID is c0a2f452-e680-4183-8f56-0ff5b73f89b3
2026-08-30 12:10:40,634 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:11:03,852 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:11:15,605 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

dfaa500cfb03808dc769f95d6a0d9c55.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 189/793
======================================================================
Date: 1991-07-30
Output: ERA5_chunks_fixed/ERA5_1991-07-30.grib
Submitting request...

2026-08-30 12:11:22,578 INFO Request ID is 0bce064d-02ea-4230-96bb-319c0f23eba5
INFO:ecmwf.datastores.legacy_client:Request ID is 0bce064d-02ea-4230-96bb-319c0f23eba5
2026-08-30 12:11:22,817 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:12:17,924 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

29b06a73bf099a5a97df8e3bb98cf274.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 190/793
======================================================================
Date: 1991-08-22
Output: ERA5_chunks_fixed/ERA5_1991-08-22.grib
Submitting request...

2026-08-30 12:12:24,470 INFO Request ID is 555739fa-a3bc-4df8-9ebc-1c619d8dab6d
INFO:ecmwf.datastores.legacy_client:Request ID is 555739fa-a3bc-4df8-9ebc-1c619d8dab6d
2026-08-30 12:12:24,734 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:12:58,631 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9370034af03ba03402f2d5eca624738e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 191/793
======================================================================
Date: 1991-08-23
Output: ERA5_chunks_fixed/ERA5_1991-08-23.grib
Submitting request...

2026-08-30 12:13:05,371 INFO Request ID is 2bc3219b-375d-4fa4-8e77-d61ec32aed75
INFO:ecmwf.datastores.legacy_client:Request ID is 2bc3219b-375d-4fa4-8e77-d61ec32aed75
2026-08-30 12:13:07,105 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:13:23,712 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:13:45,269 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f391435b03eda54a66863c4d4ae3b914.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 192/793
======================================================================
Date: 1991-08-24
Output: ERA5_chunks_fixed/ERA5_1991-08-24.grib
Submitting request...

2026-08-30 12:13:51,458 INFO Request ID is 522cb196-3000-4216-8415-495ae3ba8566
INFO:ecmwf.datastores.legacy_client:Request ID is 522cb196-3000-4216-8415-495ae3ba8566
2026-08-30 12:13:51,706 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:14:42,881 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:15:08,757 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c3f1dc035e03c75dc983da2e0b1f86f2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 193/793
======================================================================
Date: 1991-08-25
Output: ERA5_chunks_fixed/ERA5_1991-08-25.grib
Submitting request...

2026-08-30 12:15:16,033 INFO Request ID is 2f684c26-dbcd-4f6c-b9a3-18f992d49ce9
INFO:ecmwf.datastores.legacy_client:Request ID is 2f684c26-dbcd-4f6c-b9a3-18f992d49ce9
2026-08-30 12:15:16,285 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:15:38,945 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:15:50,602 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2f5ceaf85457095d1d7e681bfd3ea6a7.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 194/793
======================================================================
Date: 1991-09-21
Output: ERA5_chunks_fixed/ERA5_1991-09-21.grib
Submitting request...

2026-08-30 12:15:57,005 INFO Request ID is e32dfc00-af30-4b29-a3fb-f7ae7e97f581
INFO:ecmwf.datastores.legacy_client:Request ID is e32dfc00-af30-4b29-a3fb-f7ae7e97f581
2026-08-30 12:15:57,257 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:16:31,142 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:17:14,442 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2089883e73b161287cc0fa6bcfe7da68.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 195/793
======================================================================
Date: 1991-10-12
Output: ERA5_chunks_fixed/ERA5_1991-10-12.grib
Submitting request...

2026-08-30 12:17:21,578 INFO Request ID is cdeeda99-91a7-449a-a453-14ebc739f095
INFO:ecmwf.datastores.legacy_client:Request ID is cdeeda99-91a7-449a-a453-14ebc739f095
2026-08-30 12:17:21,846 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:17:55,996 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:18:13,341 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e0fb6ed1669a0cfb54e4e02cbeabb83.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 196/793
======================================================================
Date: 1991-10-13
Output: ERA5_chunks_fixed/ERA5_1991-10-13.grib
Submitting request...

2026-08-30 12:18:22,534 INFO Request ID is d2c1e84b-0ba0-4e3a-b158-e4225aafe445
INFO:ecmwf.datastores.legacy_client:Request ID is d2c1e84b-0ba0-4e3a-b158-e4225aafe445
2026-08-30 12:18:22,783 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:18:47,814 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:19:16,803 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4cf344d618cdbfb7068bf5863ad7d1a7.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 197/793
======================================================================
Date: 1991-10-28
Output: ERA5_chunks_fixed/ERA5_1991-10-28.grib
Submitting request...

2026-08-30 12:19:23,065 INFO Request ID is 8fbafdfd-7451-4b3d-afcf-102f59a1b5ff
INFO:ecmwf.datastores.legacy_client:Request ID is 8fbafdfd-7451-4b3d-afcf-102f59a1b5ff
2026-08-30 12:19:23,317 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:19:58,157 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:20:41,380 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e5fa5f49ba807b8ec434e156071ee86e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 198/793
======================================================================
Date: 1991-10-29
Output: ERA5_chunks_fixed/ERA5_1991-10-29.grib
Submitting request...

2026-08-30 12:20:47,631 INFO Request ID is 628f51d8-1f3f-4aad-b019-e132e53d8a1d
INFO:ecmwf.datastores.legacy_client:Request ID is 628f51d8-1f3f-4aad-b019-e132e53d8a1d
2026-08-30 12:20:47,876 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:21:21,759 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:21:39,076 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

bef51102774b32db8c8d4827753ee002.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 199/793
======================================================================
Date: 1991-11-11
Output: ERA5_chunks_fixed/ERA5_1991-11-11.grib
Submitting request...

2026-08-30 12:21:47,031 INFO Request ID is 29108a51-a444-475c-bba1-b8b948ffc29b
INFO:ecmwf.datastores.legacy_client:Request ID is 29108a51-a444-475c-bba1-b8b948ffc29b
2026-08-30 12:21:47,296 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:22:24,069 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:22:43,749 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

89a15c964321310bab1374ab6ff8ca3b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 200/793
======================================================================
Date: 1991-11-12
Output: ERA5_chunks_fixed/ERA5_1991-11-12.grib
Submitting request...

2026-08-30 12:22:50,439 INFO Request ID is 227fca8f-5095-48ee-9e8f-90da1991f33d
INFO:ecmwf.datastores.legacy_client:Request ID is 227fca8f-5095-48ee-9e8f-90da1991f33d
2026-08-30 12:22:50,680 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:23:24,860 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a555671d0dd12696b863104cb83f857e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 201/793
======================================================================
Date: 1991-11-13
Output: ERA5_chunks_fixed/ERA5_1991-11-13.grib
Submitting request...

2026-08-30 12:23:31,348 INFO Request ID is f3aef581-1cb3-4965-8006-91161bd6774a
INFO:ecmwf.datastores.legacy_client:Request ID is f3aef581-1cb3-4965-8006-91161bd6774a
2026-08-30 12:23:31,577 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:23:54,011 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:24:23,022 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fd9600cd46202fd9d9d0d519358a6cb1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 202/793
======================================================================
Date: 1991-11-14
Output: ERA5_chunks_fixed/ERA5_1991-11-14.grib
Submitting request...

2026-08-30 12:24:29,661 INFO Request ID is 15473313-06cd-4234-a258-bc86ea113c95
INFO:ecmwf.datastores.legacy_client:Request ID is 15473313-06cd-4234-a258-bc86ea113c95
2026-08-30 12:24:30,300 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:25:05,823 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:25:23,172 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4160d73732eccab8a32206961d62e898.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 203/793
======================================================================
Date: 1992-05-16
Output: ERA5_chunks_fixed/ERA5_1992-05-16.grib
Submitting request...

2026-08-30 12:25:31,713 INFO Request ID is f6fb9709-4748-446c-9766-a3b69481c009
INFO:ecmwf.datastores.legacy_client:Request ID is f6fb9709-4748-446c-9766-a3b69481c009
2026-08-30 12:25:31,950 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:26:23,479 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5fd62ece314c635a1241ad73a5c49380.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 204/793
======================================================================
Date: 1992-05-17
Output: ERA5_chunks_fixed/ERA5_1992-05-17.grib
Submitting request...

2026-08-30 12:26:29,967 INFO Request ID is 9d2ddab6-dc7e-475a-a312-f9fadc6fa4f8
INFO:ecmwf.datastores.legacy_client:Request ID is 9d2ddab6-dc7e-475a-a312-f9fadc6fa4f8
2026-08-30 12:26:30,215 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:26:52,447 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:27:21,465 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

22bf4a1bbb57fbc101ecf053373241ff.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 205/793
======================================================================
Date: 1992-05-18
Output: ERA5_chunks_fixed/ERA5_1992-05-18.grib
Submitting request...

2026-08-30 12:27:27,995 INFO Request ID is 0a3db8ff-6827-4459-87da-982fed59f105
INFO:ecmwf.datastores.legacy_client:Request ID is 0a3db8ff-6827-4459-87da-982fed59f105
2026-08-30 12:27:28,241 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:28:02,095 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b2cb8847c1cda6be4e43375eb75f0648.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 206/793
======================================================================
Date: 1992-06-17
Output: ERA5_chunks_fixed/ERA5_1992-06-17.grib
Submitting request...

2026-08-30 12:28:08,506 INFO Request ID is 7d3f26af-d7e6-4424-ad74-4ed1cf808076
INFO:ecmwf.datastores.legacy_client:Request ID is 7d3f26af-d7e6-4424-ad74-4ed1cf808076
2026-08-30 12:28:08,734 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:28:30,919 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:28:42,558 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b68c248b85b91da5990a3a089842a296.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 207/793
======================================================================
Date: 1992-06-18
Output: ERA5_chunks_fixed/ERA5_1992-06-18.grib
Submitting request...

2026-08-30 12:28:50,039 INFO Request ID is 3e88e766-91a3-4dfd-89a9-112e9aa7df74
INFO:ecmwf.datastores.legacy_client:Request ID is 3e88e766-91a3-4dfd-89a9-112e9aa7df74
2026-08-30 12:28:50,268 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:29:25,330 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:29:43,873 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d9c77ffa844076addfd2b002d21c525.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 208/793
======================================================================
Date: 1992-06-19
Output: ERA5_chunks_fixed/ERA5_1992-06-19.grib
Submitting request...

2026-08-30 12:29:52,597 INFO Request ID is b4d544d1-01e1-4fb1-a65b-14acf71b24ac
INFO:ecmwf.datastores.legacy_client:Request ID is b4d544d1-01e1-4fb1-a65b-14acf71b24ac
2026-08-30 12:29:52,844 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:30:27,233 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:30:44,558 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

57af16f99d1693a99800100698f7fc89.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 209/793
======================================================================
Date: 1992-07-26
Output: ERA5_chunks_fixed/ERA5_1992-07-26.grib
Submitting request...

2026-08-30 12:30:51,254 INFO Request ID is 91a01458-ae15-42d3-bfbc-488bc5087dac
INFO:ecmwf.datastores.legacy_client:Request ID is 91a01458-ae15-42d3-bfbc-488bc5087dac
2026-08-30 12:30:51,500 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:31:25,549 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:31:42,875 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c4eb567fe3fe65c155c5cca1c39cae27.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 210/793
======================================================================
Date: 1992-07-27
Output: ERA5_chunks_fixed/ERA5_1992-07-27.grib
Submitting request...

2026-08-30 12:31:49,629 INFO Request ID is 8447808a-298b-4d5d-881c-5bd2617c2de7
INFO:ecmwf.datastores.legacy_client:Request ID is 8447808a-298b-4d5d-881c-5bd2617c2de7
2026-08-30 12:31:49,881 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:32:27,859 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3f2afffcc4aba3513682b082cb2b7f5b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 211/793
======================================================================
Date: 1992-07-28
Output: ERA5_chunks_fixed/ERA5_1992-07-28.grib
Submitting request...

2026-08-30 12:32:36,579 INFO Request ID is db31c08b-ba6a-4142-ba3e-e7104cc7a88f
INFO:ecmwf.datastores.legacy_client:Request ID is db31c08b-ba6a-4142-ba3e-e7104cc7a88f
2026-08-30 12:32:36,840 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:33:11,195 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c0daecd0d9f9b4df1bf26472bbc83bda.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 212/793
======================================================================
Date: 1992-07-29
Output: ERA5_chunks_fixed/ERA5_1992-07-29.grib
Submitting request...

2026-08-30 12:33:20,569 INFO Request ID is 4c360765-fc29-43ca-b756-d1ac50b947ec
INFO:ecmwf.datastores.legacy_client:Request ID is 4c360765-fc29-43ca-b756-d1ac50b947ec
2026-08-30 12:33:20,886 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:34:00,571 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:34:17,918 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a535d279bd2e604f715502e2cc4672d1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 213/793
======================================================================
Date: 1992-10-07
Output: ERA5_chunks_fixed/ERA5_1992-10-07.grib
Submitting request...

2026-08-30 12:34:24,632 INFO Request ID is 7d638ac1-52ff-4c12-912f-2b875d22d505
INFO:ecmwf.datastores.legacy_client:Request ID is 7d638ac1-52ff-4c12-912f-2b875d22d505
2026-08-30 12:34:24,888 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:34:47,469 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:35:16,457 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

808becea57b5009d0a7fab16e702e53.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 214/793
======================================================================
Date: 1992-10-08
Output: ERA5_chunks_fixed/ERA5_1992-10-08.grib
Submitting request...

2026-08-30 12:35:22,990 INFO Request ID is aab4bd62-ea05-43d0-b569-9f9cb172e284
INFO:ecmwf.datastores.legacy_client:Request ID is aab4bd62-ea05-43d0-b569-9f9cb172e284
2026-08-30 12:35:23,312 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:35:57,175 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:36:40,386 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

59f02014a801d4e268e6f9ce7caabad5.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 215/793
======================================================================
Date: 1992-10-20
Output: ERA5_chunks_fixed/ERA5_1992-10-20.grib
Submitting request...

2026-08-30 12:36:47,185 INFO Request ID is cc4f1c07-4a70-4de2-b34a-cc0568c9719d
INFO:ecmwf.datastores.legacy_client:Request ID is cc4f1c07-4a70-4de2-b34a-cc0568c9719d
2026-08-30 12:36:47,433 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:37:14,022 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:37:25,679 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e19044ca96c11869bfea458d52a01c2e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 216/793
======================================================================
Date: 1992-10-21
Output: ERA5_chunks_fixed/ERA5_1992-10-21.grib
Submitting request...

2026-08-30 12:37:35,794 INFO Request ID is f1647b65-3129-4141-8576-64ca713ef488
INFO:ecmwf.datastores.legacy_client:Request ID is f1647b65-3129-4141-8576-64ca713ef488
2026-08-30 12:37:36,031 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:38:10,246 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:38:53,474 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c638b29ba7ac6dfd1e28c82efb972a16.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 217/793
======================================================================
Date: 1992-11-03
Output: ERA5_chunks_fixed/ERA5_1992-11-03.grib
Submitting request...

2026-08-30 12:39:00,025 INFO Request ID is 9ad25a75-7366-4a4a-abd6-cba7004fe32d
INFO:ecmwf.datastores.legacy_client:Request ID is 9ad25a75-7366-4a4a-abd6-cba7004fe32d
2026-08-30 12:39:00,259 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:39:22,894 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:39:52,280 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

967035928837649c5e70056f11a8fd3d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 218/793
======================================================================
Date: 1992-11-04
Output: ERA5_chunks_fixed/ERA5_1992-11-04.grib
Submitting request...

2026-08-30 12:39:58,903 INFO Request ID is 9f3f5cf0-e3cb-48b6-b98e-50298cc301e4
INFO:ecmwf.datastores.legacy_client:Request ID is 9f3f5cf0-e3cb-48b6-b98e-50298cc301e4
2026-08-30 12:39:59,130 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:40:33,156 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:40:50,590 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

aa3c7b4929d171ab42a8edb5ffa4c698.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 219/793
======================================================================
Date: 1992-11-05
Output: ERA5_chunks_fixed/ERA5_1992-11-05.grib
Submitting request...

2026-08-30 12:40:58,612 INFO Request ID is 3d014e88-76d6-4fb3-aff0-5ad449494180
INFO:ecmwf.datastores.legacy_client:Request ID is 3d014e88-76d6-4fb3-aff0-5ad449494180
2026-08-30 12:40:58,860 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:41:33,491 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:41:50,973 INFO status has been updated to failed
INFO:ecmwf.datastores.legacy_client:status has been updated to failed

FAILED
Date: 1992-11-05
Error: 400 Client Error: Bad Request for url: https://cds.climate.copernicus.eu/api/retrieve/v1/jobs/3d014e88-76d6-4fb3-aff0-5ad449494180/results
The job has failed


======================================================================
DAY 220/793
======================================================================
Date: 1992-11-06
Output: ERA5_chunks_fixed/ERA5_1992-11-06.grib
Submitting request...

2026-08-30 12:41:54,234 INFO Request ID is 7f57fb62-4b21-476d-b552-8c818612d7b6
INFO:ecmwf.datastores.legacy_client:Request ID is 7f57fb62-4b21-476d-b552-8c818612d7b6
2026-08-30 12:41:54,482 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:42:28,400 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:43:12,729 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

15f63386820bcbdb709a9a67235cc77.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 221/793
======================================================================
Date: 1992-11-11
Output: ERA5_chunks_fixed/ERA5_1992-11-11.grib
Submitting request...

2026-08-30 12:43:19,655 INFO Request ID is 85ea420d-b923-422b-a7e6-09fc5f56b7c4
INFO:ecmwf.datastores.legacy_client:Request ID is 85ea420d-b923-422b-a7e6-09fc5f56b7c4
2026-08-30 12:43:19,899 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:43:36,301 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:43:55,766 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fe158a22532bdcb1aefe4e5e8cf09d37.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 222/793
======================================================================
Date: 1992-11-12
Output: ERA5_chunks_fixed/ERA5_1992-11-12.grib
Submitting request...

2026-08-30 12:44:02,251 INFO Request ID is 39c05224-36f1-4b9f-87be-09585dcf23c4
INFO:ecmwf.datastores.legacy_client:Request ID is 39c05224-36f1-4b9f-87be-09585dcf23c4
2026-08-30 12:44:02,491 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:44:36,485 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:44:57,436 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

71023f06d529fc131efa5d451c911c04.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 223/793
======================================================================
Date: 1992-11-13
Output: ERA5_chunks_fixed/ERA5_1992-11-13.grib
Submitting request...

2026-08-30 12:45:04,080 INFO Request ID is 7ceb0e68-618c-4bae-991c-b002ddf3b562
INFO:ecmwf.datastores.legacy_client:Request ID is 7ceb0e68-618c-4bae-991c-b002ddf3b562
2026-08-30 12:45:04,340 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:45:26,775 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:45:55,753 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ae8e094fa7fce68b9553526a139405e.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 224/793
======================================================================
Date: 1992-11-14
Output: ERA5_chunks_fixed/ERA5_1992-11-14.grib
Submitting request...

2026-08-30 12:46:02,678 INFO Request ID is 0f8707cc-d49b-4f4d-a43e-f18330ae5d7c
INFO:ecmwf.datastores.legacy_client:Request ID is 0f8707cc-d49b-4f4d-a43e-f18330ae5d7c
2026-08-30 12:46:02,924 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:46:25,237 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:46:54,310 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

49a061ad724e01a60fa79911deccfb4f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 225/793
======================================================================
Date: 1992-11-15
Output: ERA5_chunks_fixed/ERA5_1992-11-15.grib
Submitting request...

2026-08-30 12:47:01,539 INFO Request ID is c9acd614-1818-40ed-89a9-a5a029dbb305
INFO:ecmwf.datastores.legacy_client:Request ID is c9acd614-1818-40ed-89a9-a5a029dbb305
2026-08-30 12:47:01,794 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:47:39,873 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:47:57,233 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c2d0fee2a1fe6b0bd5470e168b8476e4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 226/793
======================================================================
Date: 1992-11-16
Output: ERA5_chunks_fixed/ERA5_1992-11-16.grib
Submitting request...

2026-08-30 12:48:04,181 INFO Request ID is 153d9124-00ef-4961-a174-6f0497801c5e
INFO:ecmwf.datastores.legacy_client:Request ID is 153d9124-00ef-4961-a174-6f0497801c5e
2026-08-30 12:48:05,384 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:48:23,225 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:48:42,701 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

66a826a8c8dec4d79230fee96f313e26.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 227/793
======================================================================
Date: 1992-11-17
Output: ERA5_chunks_fixed/ERA5_1992-11-17.grib
Submitting request...

2026-08-30 12:48:49,064 INFO Request ID is 53c2ab1f-2ad7-48e6-991c-bac9aa2ccc3d
INFO:ecmwf.datastores.legacy_client:Request ID is 53c2ab1f-2ad7-48e6-991c-bac9aa2ccc3d
2026-08-30 12:48:49,311 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:49:13,336 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:49:24,973 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8008bd9f20bd17537b06f363dbf318a4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 228/793
======================================================================
Date: 1992-11-18
Output: ERA5_chunks_fixed/ERA5_1992-11-18.grib
Submitting request...

2026-08-30 12:49:31,696 INFO Request ID is d8ccd5ee-cad8-4788-9a62-b208f16fe2c3
INFO:ecmwf.datastores.legacy_client:Request ID is d8ccd5ee-cad8-4788-9a62-b208f16fe2c3
2026-08-30 12:49:31,937 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:50:05,748 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:50:23,071 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5c5a9a8f5e26072bffd57976b64f6489.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 229/793
======================================================================
Date: 1992-11-19
Output: ERA5_chunks_fixed/ERA5_1992-11-19.grib
Submitting request...

2026-08-30 12:50:31,427 INFO Request ID is 3b8654db-25a8-416b-a7a0-f3e620454e64
INFO:ecmwf.datastores.legacy_client:Request ID is 3b8654db-25a8-416b-a7a0-f3e620454e64
2026-08-30 12:50:31,656 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:50:57,983 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:51:26,930 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

32a4612f37bd21f8c53baff7b0b19576.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 230/793
======================================================================
Date: 1992-11-20
Output: ERA5_chunks_fixed/ERA5_1992-11-20.grib
Submitting request...

2026-08-30 12:51:36,046 INFO Request ID is c2bf716a-7676-4182-a565-821c102ce2af
INFO:ecmwf.datastores.legacy_client:Request ID is c2bf716a-7676-4182-a565-821c102ce2af
2026-08-30 12:51:36,353 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:52:02,196 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:52:31,642 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8116189743f8fe14bc0504e01a2744c5.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 231/793
======================================================================
Date: 1993-12-01
Output: ERA5_chunks_fixed/ERA5_1993-12-01.grib
Submitting request...

2026-08-30 12:52:37,897 INFO Request ID is 982c92a0-e706-43c0-b5d6-1854ef1bedfb
INFO:ecmwf.datastores.legacy_client:Request ID is 982c92a0-e706-43c0-b5d6-1854ef1bedfb
2026-08-30 12:52:38,718 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:53:01,830 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:53:30,883 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

67aa0560e968a2c7f34e3ea5012ddfb1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 232/793
======================================================================
Date: 1993-12-02
Output: ERA5_chunks_fixed/ERA5_1993-12-02.grib
Submitting request...

2026-08-30 12:53:38,789 INFO Request ID is 5e8dcb13-e9f7-42e1-a744-d47bebc1ad32
INFO:ecmwf.datastores.legacy_client:Request ID is 5e8dcb13-e9f7-42e1-a744-d47bebc1ad32
2026-08-30 12:53:39,033 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:54:15,685 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:54:33,021 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

eb5736926d3f4c83f14f19443e88ce8b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 233/793
======================================================================
Date: 1993-12-03
Output: ERA5_chunks_fixed/ERA5_1993-12-03.grib
Submitting request...

2026-08-30 12:54:39,384 INFO Request ID is ce4af25a-a131-4ceb-ba6f-455f6d056f9d
INFO:ecmwf.datastores.legacy_client:Request ID is ce4af25a-a131-4ceb-ba6f-455f6d056f9d
2026-08-30 12:54:39,616 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:55:03,180 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:55:32,131 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3f0ac987b6cb0d3bb24bb4886cf62de1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 234/793
======================================================================
Date: 1993-12-19
Output: ERA5_chunks_fixed/ERA5_1993-12-19.grib
Submitting request...

2026-08-30 12:55:39,103 INFO Request ID is 1e0e6fc2-d7d6-41a9-87c4-622f4e30c3e2
INFO:ecmwf.datastores.legacy_client:Request ID is 1e0e6fc2-d7d6-41a9-87c4-622f4e30c3e2
2026-08-30 12:55:39,379 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:56:01,910 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:56:56,757 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

577b0c2359bf89b282d5bc4d382fe29d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 235/793
======================================================================
Date: 1994-03-21
Output: ERA5_chunks_fixed/ERA5_1994-03-21.grib
Submitting request...

2026-08-30 12:57:03,531 INFO Request ID is 052d301e-847b-44d3-b32d-5518b731b548
INFO:ecmwf.datastores.legacy_client:Request ID is 052d301e-847b-44d3-b32d-5518b731b548
2026-08-30 12:57:03,788 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:57:26,653 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:57:38,302 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

49586f4e3fc8dd08aa0be4aa57d93c79.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 236/793
======================================================================
Date: 1994-03-22
Output: ERA5_chunks_fixed/ERA5_1994-03-22.grib
Submitting request...

2026-08-30 12:57:45,374 INFO Request ID is 7ffa408b-9034-403e-9be1-34cddc448a83
INFO:ecmwf.datastores.legacy_client:Request ID is 7ffa408b-9034-403e-9be1-34cddc448a83
2026-08-30 12:57:45,612 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:58:19,573 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:58:36,944 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8d11c39a85a8eaaadc9869faca4e19bf.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 237/793
======================================================================
Date: 1994-03-23
Output: ERA5_chunks_fixed/ERA5_1994-03-23.grib
Submitting request...

2026-08-30 12:58:43,923 INFO Request ID is e0090b19-a830-4c59-a7cc-827007f7c402
INFO:ecmwf.datastores.legacy_client:Request ID is e0090b19-a830-4c59-a7cc-827007f7c402
2026-08-30 12:58:44,179 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 12:59:09,151 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 12:59:38,729 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d6a7d91d7d5b9fd73d7a9dcff207656.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 238/793
======================================================================
Date: 1994-04-29
Output: ERA5_chunks_fixed/ERA5_1994-04-29.grib
Submitting request...

2026-08-30 12:59:54,381 INFO Request ID is e6bb9ec5-f046-4dbe-8f3c-230fe39bdf34
INFO:ecmwf.datastores.legacy_client:Request ID is e6bb9ec5-f046-4dbe-8f3c-230fe39bdf34
2026-08-30 12:59:54,627 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:00:18,033 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:00:29,690 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ed6b613957fe25bee2a6d08d68671c13.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 239/793
======================================================================
Date: 1994-04-30
Output: ERA5_chunks_fixed/ERA5_1994-04-30.grib
Submitting request...

2026-08-30 13:00:40,253 INFO Request ID is a44fb3d9-4b6e-41ff-9dbd-911e6f0101bb
INFO:ecmwf.datastores.legacy_client:Request ID is a44fb3d9-4b6e-41ff-9dbd-911e6f0101bb
2026-08-30 13:00:40,518 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:01:18,515 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:03:39,210 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

173154d0287de9066a1a572d10b841db.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 240/793
======================================================================
Date: 1994-05-01
Output: ERA5_chunks_fixed/ERA5_1994-05-01.grib
Submitting request...

2026-08-30 13:03:46,531 INFO Request ID is 6abdeeea-c2f0-43b4-99ea-c847d239e528
INFO:ecmwf.datastores.legacy_client:Request ID is 6abdeeea-c2f0-43b4-99ea-c847d239e528
2026-08-30 13:03:46,808 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:04:41,407 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:05:07,316 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4f5b936aea1ffb35af357879856176ec.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 241/793
======================================================================
Date: 1994-10-29
Output: ERA5_chunks_fixed/ERA5_1994-10-29.grib
Submitting request...

2026-08-30 13:05:13,779 INFO Request ID is b7b4b9a2-3794-4f67-af71-3d5600bd75fc
INFO:ecmwf.datastores.legacy_client:Request ID is b7b4b9a2-3794-4f67-af71-3d5600bd75fc
2026-08-30 13:05:14,025 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:06:06,331 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c13c3338dd05750b94c102eba4dc5df9.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 242/793
======================================================================
Date: 1994-10-30
Output: ERA5_chunks_fixed/ERA5_1994-10-30.grib
Submitting request...

2026-08-30 13:06:13,317 INFO Request ID is 4b80c4e4-f1fd-40ea-b737-fec8a01a6b52
INFO:ecmwf.datastores.legacy_client:Request ID is 4b80c4e4-f1fd-40ea-b737-fec8a01a6b52
2026-08-30 13:06:14,916 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:06:37,128 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:06:48,757 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8a2f44c91ac66fdf9f1c1a055855ac59.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 243/793
======================================================================
Date: 1995-05-08
Output: ERA5_chunks_fixed/ERA5_1995-05-08.grib
Submitting request...

2026-08-30 13:06:54,967 INFO Request ID is d669711a-4292-4233-b923-fb4754688b9c
INFO:ecmwf.datastores.legacy_client:Request ID is d669711a-4292-4233-b923-fb4754688b9c
2026-08-30 13:06:55,247 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:07:48,446 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e296e2d5f5c22778dd3ddaa5282db30f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 244/793
======================================================================
Date: 1995-05-09
Output: ERA5_chunks_fixed/ERA5_1995-05-09.grib
Submitting request...

2026-08-30 13:07:55,961 INFO Request ID is 623afd41-dfe7-4eef-b206-8d9016eedf91
INFO:ecmwf.datastores.legacy_client:Request ID is 623afd41-dfe7-4eef-b206-8d9016eedf91
2026-08-30 13:07:57,127 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:08:50,059 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7687e06b3f3ed908d62c4c78b795853.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 245/793
======================================================================
Date: 1995-05-14
Output: ERA5_chunks_fixed/ERA5_1995-05-14.grib
Submitting request...

2026-08-30 13:08:57,421 INFO Request ID is 803ddbc9-79be-480c-847a-8a05bfdccf34
INFO:ecmwf.datastores.legacy_client:Request ID is 803ddbc9-79be-480c-847a-8a05bfdccf34
2026-08-30 13:08:57,664 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:09:49,708 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7ff75ed4df427fab68d62671440dd5b8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 246/793
======================================================================
Date: 1995-05-15
Output: ERA5_chunks_fixed/ERA5_1995-05-15.grib
Submitting request...

2026-08-30 13:09:56,484 INFO Request ID is 70e66a7d-0c7c-42c7-98ab-191944f25cc5
INFO:ecmwf.datastores.legacy_client:Request ID is 70e66a7d-0c7c-42c7-98ab-191944f25cc5
2026-08-30 13:09:56,744 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:10:33,031 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:11:16,563 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d81a91ec551bbbd8d51339d58f98abc1.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 247/793
======================================================================
Date: 1995-05-16
Output: ERA5_chunks_fixed/ERA5_1995-05-16.grib
Submitting request...

2026-08-30 13:11:23,181 INFO Request ID is d8dd6365-3062-40b3-a7b9-ed5e2b91aed1
INFO:ecmwf.datastores.legacy_client:Request ID is d8dd6365-3062-40b3-a7b9-ed5e2b91aed1
2026-08-30 13:11:24,204 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:11:58,494 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:13:20,466 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ac15605919a579a366154ec229509e68.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 248/793
======================================================================
Date: 1995-09-16
Output: ERA5_chunks_fixed/ERA5_1995-09-16.grib
Submitting request...

2026-08-30 13:13:26,990 INFO Request ID is 04d68655-1dde-4d8e-9835-e9c9e8c5dcbd
INFO:ecmwf.datastores.legacy_client:Request ID is 04d68655-1dde-4d8e-9835-e9c9e8c5dcbd
2026-08-30 13:13:27,247 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:14:19,246 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d7971a8a4de8caa9dd43bf19e3b9e48f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 249/793
======================================================================
Date: 1995-11-07
Output: ERA5_chunks_fixed/ERA5_1995-11-07.grib
Submitting request...

2026-08-30 13:14:25,796 INFO Request ID is 8a8a3dc0-870e-4449-a975-0998f04113a7
INFO:ecmwf.datastores.legacy_client:Request ID is 8a8a3dc0-870e-4449-a975-0998f04113a7
2026-08-30 13:14:26,044 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:15:01,923 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:15:45,140 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7c211b778a1ef20c7072ead484ada049.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 250/793
======================================================================
Date: 1995-11-08
Output: ERA5_chunks_fixed/ERA5_1995-11-08.grib
Submitting request...

2026-08-30 13:15:55,817 INFO Request ID is 36c1c61d-c99d-4581-8bf2-03301afbb426
INFO:ecmwf.datastores.legacy_client:Request ID is 36c1c61d-c99d-4581-8bf2-03301afbb426
2026-08-30 13:15:57,046 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:16:31,024 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:16:48,576 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

db3d19b166da8ef699a2c23fa745288a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 251/793
======================================================================
Date: 1995-11-21
Output: ERA5_chunks_fixed/ERA5_1995-11-21.grib
Submitting request...

WARNING:multiurl.retry:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:multiurl.retry:Retrying in 120 seconds
2026-08-30 13:18:58,160 INFO Request ID is d4801e3f-c409-4845-b683-9c076e4a01dd
INFO:ecmwf.datastores.legacy_client:Request ID is d4801e3f-c409-4845-b683-9c076e4a01dd
2026-08-30 13:18:58,409 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:19:33,873 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:19:51,188 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d6733243164de5727a7c3af63c2d0271.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 252/793
======================================================================
Date: 1995-11-22
Output: ERA5_chunks_fixed/ERA5_1995-11-22.grib
Submitting request...

2026-08-30 13:19:58,006 INFO Request ID is 791983a1-8a19-4c50-b2b2-a778f702edb6
INFO:ecmwf.datastores.legacy_client:Request ID is 791983a1-8a19-4c50-b2b2-a778f702edb6
2026-08-30 13:19:58,252 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:20:21,927 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:21:16,739 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

65805ee09e84bac704bf1a2a4a3d768a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 253/793
======================================================================
Date: 1995-11-23
Output: ERA5_chunks_fixed/ERA5_1995-11-23.grib
Submitting request...

2026-08-30 13:21:23,256 INFO Request ID is 4503908f-b1c5-48be-8376-a64c08e8ed23
INFO:ecmwf.datastores.legacy_client:Request ID is 4503908f-b1c5-48be-8376-a64c08e8ed23
2026-08-30 13:21:23,499 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:21:37,921 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:21:57,383 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c3a1dd170a55b2d1b52be9c7b7d7efc3.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 254/793
======================================================================
Date: 1995-11-24
Output: ERA5_chunks_fixed/ERA5_1995-11-24.grib
Submitting request...

2026-08-30 13:22:04,486 INFO Request ID is df51ecb6-4531-4dce-b25d-5d2aa7305487
INFO:ecmwf.datastores.legacy_client:Request ID is df51ecb6-4531-4dce-b25d-5d2aa7305487
2026-08-30 13:22:04,712 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:22:38,853 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:22:56,182 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2ce492d2d3d52b1f6ee39cf77a7556d0.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 255/793
======================================================================
Date: 1996-06-12
Output: ERA5_chunks_fixed/ERA5_1996-06-12.grib
Submitting request...

2026-08-30 13:23:02,924 INFO Request ID is 5c8225f7-f834-46f7-9c14-b0851cc35592
INFO:ecmwf.datastores.legacy_client:Request ID is 5c8225f7-f834-46f7-9c14-b0851cc35592
2026-08-30 13:23:03,166 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:23:25,359 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:23:36,997 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8a829835e58d0e01ef2429eb4f67e8d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 256/793
======================================================================
Date: 1996-06-13
Output: ERA5_chunks_fixed/ERA5_1996-06-13.grib
Submitting request...

2026-08-30 13:23:43,518 INFO Request ID is a4e3324b-47d3-4e72-bf1c-45553976b927
INFO:ecmwf.datastores.legacy_client:Request ID is a4e3324b-47d3-4e72-bf1c-45553976b927
2026-08-30 13:23:43,756 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:24:05,907 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:24:17,636 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

282cefe517c89511c0254e7843ec619b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 257/793
======================================================================
Date: 1996-06-14
Output: ERA5_chunks_fixed/ERA5_1996-06-14.grib
Submitting request...

2026-08-30 13:24:24,135 INFO Request ID is 64b14669-7402-4c32-8b82-178ea1e976d4
INFO:ecmwf.datastores.legacy_client:Request ID is 64b14669-7402-4c32-8b82-178ea1e976d4
2026-08-30 13:24:24,367 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:25:16,382 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:25:42,254 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f6ec044e09c52bb835ea41e2f3d54278.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 258/793
======================================================================
Date: 1996-06-15
Output: ERA5_chunks_fixed/ERA5_1996-06-15.grib
Submitting request...

2026-08-30 13:25:51,377 INFO Request ID is a6b4aee8-579b-4ba1-9140-13d7257b91eb
INFO:ecmwf.datastores.legacy_client:Request ID is a6b4aee8-579b-4ba1-9140-13d7257b91eb
2026-08-30 13:25:51,698 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:26:15,970 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:26:44,945 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b92bfe19576f02f39f8352aaef67ef53.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 259/793
======================================================================
Date: 1996-10-27
Output: ERA5_chunks_fixed/ERA5_1996-10-27.grib
Submitting request...

2026-08-30 13:26:53,375 INFO Request ID is a0de4f4b-d51a-473e-8825-72e5cf8c7227
INFO:ecmwf.datastores.legacy_client:Request ID is a0de4f4b-d51a-473e-8825-72e5cf8c7227
2026-08-30 13:26:53,622 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:27:15,881 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:27:27,497 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

34d45d6d8050ebe4a20c28deff66034c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 260/793
======================================================================
Date: 1996-11-04
Output: ERA5_chunks_fixed/ERA5_1996-11-04.grib
Submitting request...

2026-08-30 13:27:33,892 INFO Request ID is e60078cd-eebc-479f-b4e2-d4ac68026763
INFO:ecmwf.datastores.legacy_client:Request ID is e60078cd-eebc-479f-b4e2-d4ac68026763
2026-08-30 13:27:34,316 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:27:58,209 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:28:27,178 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e822a8b2447af7c1bd37de614bcc1c15.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 261/793
======================================================================
Date: 1996-11-05
Output: ERA5_chunks_fixed/ERA5_1996-11-05.grib
Submitting request...

2026-08-30 13:28:35,098 INFO Request ID is dcfa9c88-ae9e-43d0-bd26-605100a30052
INFO:ecmwf.datastores.legacy_client:Request ID is dcfa9c88-ae9e-43d0-bd26-605100a30052
2026-08-30 13:28:35,329 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:28:59,188 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:29:10,816 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b378af9ad35aa103a62c2427a50f2e1b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 262/793
======================================================================
Date: 1996-11-28
Output: ERA5_chunks_fixed/ERA5_1996-11-28.grib
Submitting request...

2026-08-30 13:29:20,071 INFO Request ID is 7a38db1f-1e1f-4b9a-b286-faf29d935513
INFO:ecmwf.datastores.legacy_client:Request ID is 7a38db1f-1e1f-4b9a-b286-faf29d935513
2026-08-30 13:29:20,309 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:29:45,473 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:29:57,119 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9d38df0836e3d3c9c197e45db495e73a.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 263/793
======================================================================
Date: 1996-11-29
Output: ERA5_chunks_fixed/ERA5_1996-11-29.grib
Submitting request...

2026-08-30 13:30:04,333 INFO Request ID is a18ed632-cada-4553-ac80-07082f62867a
INFO:ecmwf.datastores.legacy_client:Request ID is a18ed632-cada-4553-ac80-07082f62867a
2026-08-30 13:30:04,578 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:30:26,810 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:31:21,626 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f63e6cba26ba2036834a6d1680751636.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 264/793
======================================================================
Date: 1996-11-30
Output: ERA5_chunks_fixed/ERA5_1996-11-30.grib
Submitting request...

2026-08-30 13:31:27,853 INFO Request ID is 28d28704-4cf9-4bfe-aeba-d99d705713ba
INFO:ecmwf.datastores.legacy_client:Request ID is 28d28704-4cf9-4bfe-aeba-d99d705713ba
2026-08-30 13:31:28,094 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:32:02,376 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:32:19,722 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

981ecfee0e429a4efa3cbbd1ba224ce5.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 265/793
======================================================================
Date: 1996-12-01
Output: ERA5_chunks_fixed/ERA5_1996-12-01.grib
Submitting request...

2026-08-30 13:32:26,011 INFO Request ID is a4cea8cf-bd94-48a3-9544-a4e56377698a
INFO:ecmwf.datastores.legacy_client:Request ID is a4cea8cf-bd94-48a3-9544-a4e56377698a
2026-08-30 13:32:26,240 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:33:01,051 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:33:18,393 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6a6b844aae9c69db5bc6c2b5856b098d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 266/793
======================================================================
Date: 1996-12-02
Output: ERA5_chunks_fixed/ERA5_1996-12-02.grib
Submitting request...

2026-08-30 13:33:27,999 INFO Request ID is 7a966cdf-545c-48a9-964e-b6abcd31145b
INFO:ecmwf.datastores.legacy_client:Request ID is 7a966cdf-545c-48a9-964e-b6abcd31145b
2026-08-30 13:33:28,262 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:34:04,267 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:34:21,588 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b3d37d237745f2fb683a4b72d428c166.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 267/793
======================================================================
Date: 1996-12-03
Output: ERA5_chunks_fixed/ERA5_1996-12-03.grib
Submitting request...

2026-08-30 13:34:28,000 INFO Request ID is db71a8d1-2bb5-411f-b08c-a1a6ca4af3f5
INFO:ecmwf.datastores.legacy_client:Request ID is db71a8d1-2bb5-411f-b08c-a1a6ca4af3f5
2026-08-30 13:34:28,271 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:34:50,846 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:35:19,832 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cf53a71db6e801c8014d69fc37c26c7b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 268/793
======================================================================
Date: 1996-12-04
Output: ERA5_chunks_fixed/ERA5_1996-12-04.grib
Submitting request...

2026-08-30 13:35:26,446 INFO Request ID is 2cfca62f-2117-40fe-a157-c6696447a49b
INFO:ecmwf.datastores.legacy_client:Request ID is 2cfca62f-2117-40fe-a157-c6696447a49b
2026-08-30 13:35:27,154 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:35:51,933 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:36:20,925 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

487b4d655dab5b1e9816842da7e97d13.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 269/793
======================================================================
Date: 1996-12-05
Output: ERA5_chunks_fixed/ERA5_1996-12-05.grib
Submitting request...

WARNING:multiurl.retry:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:multiurl.retry:Retrying in 120 seconds
2026-08-30 13:38:29,528 INFO Request ID is ad91c9c2-cf99-4c2d-a2b9-37dc273e8cca
INFO:ecmwf.datastores.legacy_client:Request ID is ad91c9c2-cf99-4c2d-a2b9-37dc273e8cca
2026-08-30 13:38:29,787 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:39:21,782 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fefc0d8aacd9cf8fddf008b61306b7f2.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 270/793
======================================================================
Date: 1997-05-15
Output: ERA5_chunks_fixed/ERA5_1997-05-15.grib
Submitting request...

2026-08-30 13:39:28,438 INFO Request ID is d672d4a8-1ddd-497a-8e58-3f6fcf55da63
INFO:ecmwf.datastores.legacy_client:Request ID is d672d4a8-1ddd-497a-8e58-3f6fcf55da63
2026-08-30 13:39:28,672 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:39:50,859 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:40:19,827 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

25d0f02789297244ade329d6b43d5cce.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 271/793
======================================================================
Date: 1997-05-16
Output: ERA5_chunks_fixed/ERA5_1997-05-16.grib
Submitting request...

2026-08-30 13:40:26,440 INFO Request ID is ba40463f-a8a3-4747-9c4e-73e9814a8957
INFO:ecmwf.datastores.legacy_client:Request ID is ba40463f-a8a3-4747-9c4e-73e9814a8957
2026-08-30 13:40:26,689 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:41:00,985 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:41:18,367 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

282ec326bba339029170fdc3eacb8cf7.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 272/793
======================================================================
Date: 1997-05-17
Output: ERA5_chunks_fixed/ERA5_1997-05-17.grib
Submitting request...

2026-08-30 13:41:24,721 INFO Request ID is 4cf8107d-b3fe-40a6-ae83-061af6e8fcc8
INFO:ecmwf.datastores.legacy_client:Request ID is 4cf8107d-b3fe-40a6-ae83-061af6e8fcc8
2026-08-30 13:41:24,963 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:42:16,176 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

97617df1ca3c3cd4a6dff8fb3bd07529.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 273/793
======================================================================
Date: 1997-05-18
Output: ERA5_chunks_fixed/ERA5_1997-05-18.grib
Submitting request...

2026-08-30 13:42:22,770 INFO Request ID is f7418c15-07bb-4080-87c6-09ed2f34dd34
INFO:ecmwf.datastores.legacy_client:Request ID is f7418c15-07bb-4080-87c6-09ed2f34dd34
2026-08-30 13:42:23,022 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:42:57,280 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:43:15,900 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3c146f33452ad0c18fddeab6980bc565.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 274/793
======================================================================
Date: 1997-07-29
Output: ERA5_chunks_fixed/ERA5_1997-07-29.grib
Submitting request...

2026-08-30 13:43:25,035 INFO Request ID is 2de4d639-6bc4-43f6-9a39-9afd33e30e2f
INFO:ecmwf.datastores.legacy_client:Request ID is 2de4d639-6bc4-43f6-9a39-9afd33e30e2f
2026-08-30 13:43:25,275 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:43:59,450 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:44:16,781 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6107d04db8daa75ae07dd4dd113c52e4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 275/793
======================================================================
Date: 1997-09-23
Output: ERA5_chunks_fixed/ERA5_1997-09-23.grib
Submitting request...

2026-08-30 13:44:23,679 INFO Request ID is 448ebf27-dfda-46aa-8c7a-91ff403afecc
INFO:ecmwf.datastores.legacy_client:Request ID is 448ebf27-dfda-46aa-8c7a-91ff403afecc
2026-08-30 13:44:23,906 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:44:58,644 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:45:41,878 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d843443feff42d5327eb3ca752604a05.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 276/793
======================================================================
Date: 1997-09-24
Output: ERA5_chunks_fixed/ERA5_1997-09-24.grib
Submitting request...

2026-08-30 13:45:48,394 INFO Request ID is c1169b0e-ebba-4a3f-96e2-465f8c0dfb44
INFO:ecmwf.datastores.legacy_client:Request ID is c1169b0e-ebba-4a3f-96e2-465f8c0dfb44
2026-08-30 13:45:48,650 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:46:39,944 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:47:05,819 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

99375a82a887ff507d1483ab99ea543c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 277/793
======================================================================
Date: 1997-09-25
Output: ERA5_chunks_fixed/ERA5_1997-09-25.grib
Submitting request...

2026-08-30 13:47:12,258 INFO Request ID is 0bdfa354-48dc-4e5f-8334-b66d51319325
INFO:ecmwf.datastores.legacy_client:Request ID is 0bdfa354-48dc-4e5f-8334-b66d51319325
2026-08-30 13:47:12,495 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:47:27,621 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:47:47,084 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b3d88f63235bc9c7fd4540d2ee8a55ee.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 278/793
======================================================================
Date: 1997-11-04
Output: ERA5_chunks_fixed/ERA5_1997-11-04.grib
Submitting request...

2026-08-30 13:47:53,914 INFO Request ID is b65273de-53e5-47f6-a61a-38cc0f495703
INFO:ecmwf.datastores.legacy_client:Request ID is b65273de-53e5-47f6-a61a-38cc0f495703
2026-08-30 13:47:54,237 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:48:17,571 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:48:49,171 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ab5dc542922694ae52d86e2b540788d3.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 279/793
======================================================================
Date: 1997-11-05
Output: ERA5_chunks_fixed/ERA5_1997-11-05.grib
Submitting request...

2026-08-30 13:48:55,649 INFO Request ID is 7025f5b6-733f-4f0a-b9c8-95e40fbbfa93
INFO:ecmwf.datastores.legacy_client:Request ID is 7025f5b6-733f-4f0a-b9c8-95e40fbbfa93
2026-08-30 13:48:55,900 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:50:16,084 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

64956f914edda63b489040c41e52895b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 280/793
======================================================================
Date: 1997-11-06
Output: ERA5_chunks_fixed/ERA5_1997-11-06.grib
Submitting request...

2026-08-30 13:50:25,136 INFO Request ID is 78f86a1e-34b5-4506-854e-c97e6ae95211
INFO:ecmwf.datastores.legacy_client:Request ID is 78f86a1e-34b5-4506-854e-c97e6ae95211
2026-08-30 13:50:25,407 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:50:48,761 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:51:17,731 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2f54e86c4ec940a9641137c5d1ad3983.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 281/793
======================================================================
Date: 1997-11-07
Output: ERA5_chunks_fixed/ERA5_1997-11-07.grib
Submitting request...

2026-08-30 13:51:24,848 INFO Request ID is 92e24ccc-add9-4672-83d0-19a135c433ee
INFO:ecmwf.datastores.legacy_client:Request ID is 92e24ccc-add9-4672-83d0-19a135c433ee
2026-08-30 13:51:25,080 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:51:47,874 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:52:16,818 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7ff7d5a5d60d8af3f0a00476552b717f.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 282/793
======================================================================
Date: 1997-11-08
Output: ERA5_chunks_fixed/ERA5_1997-11-08.grib
Submitting request...

2026-08-30 13:52:25,421 INFO Request ID is 13c732b4-7b56-4019-9c73-0712e67a4f28
INFO:ecmwf.datastores.legacy_client:Request ID is 13c732b4-7b56-4019-9c73-0712e67a4f28
2026-08-30 13:52:25,698 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:53:00,052 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:53:17,395 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

804db851ca7dddc1dbe72b0797cb5d35.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 283/793
======================================================================
Date: 1998-05-17
Output: ERA5_chunks_fixed/ERA5_1998-05-17.grib
Submitting request...

2026-08-30 13:53:24,173 INFO Request ID is e38730d6-edcd-43d2-9e97-ada8822ecaac
INFO:ecmwf.datastores.legacy_client:Request ID is e38730d6-edcd-43d2-9e97-ada8822ecaac
2026-08-30 13:53:24,438 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:53:39,212 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:53:58,772 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

da1e7a88ecfca43d0b25927f2632f254.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 284/793
======================================================================
Date: 1998-05-18
Output: ERA5_chunks_fixed/ERA5_1998-05-18.grib
Submitting request...

2026-08-30 13:54:10,272 INFO Request ID is ccbbdb83-870e-4bc2-8f49-62e3d5bc2f41
INFO:ecmwf.datastores.legacy_client:Request ID is ccbbdb83-870e-4bc2-8f49-62e3d5bc2f41
2026-08-30 13:54:10,499 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:54:24,874 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:54:32,729 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

13e9e8cebd0063f8cbdf5ceb6806bd62.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 285/793
======================================================================
Date: 1998-05-19
Output: ERA5_chunks_fixed/ERA5_1998-05-19.grib
Submitting request...

2026-08-30 13:54:40,520 INFO Request ID is 17ca8412-4fc1-4ec9-948d-efeca3e0ec55
INFO:ecmwf.datastores.legacy_client:Request ID is 17ca8412-4fc1-4ec9-948d-efeca3e0ec55
2026-08-30 13:54:40,794 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:55:14,854 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:55:32,169 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

33e41a636293237c7ad9ec028f2c1acf.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 286/793
======================================================================
Date: 1998-10-13
Output: ERA5_chunks_fixed/ERA5_1998-10-13.grib
Submitting request...

2026-08-30 13:55:39,132 INFO Request ID is a10ca95c-4274-4bcb-a6af-b28e83989b4f
INFO:ecmwf.datastores.legacy_client:Request ID is a10ca95c-4274-4bcb-a6af-b28e83989b4f
2026-08-30 13:55:39,398 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:56:02,015 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:56:31,416 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3960393b19ad07ef9181efaed59e1460.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 287/793
======================================================================
Date: 1998-10-26
Output: ERA5_chunks_fixed/ERA5_1998-10-26.grib
Submitting request...

2026-08-30 13:56:37,804 INFO Request ID is a9792e9f-7203-4327-841e-73c1b6fcf3cf
INFO:ecmwf.datastores.legacy_client:Request ID is a9792e9f-7203-4327-841e-73c1b6fcf3cf
2026-08-30 13:56:38,087 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:57:12,061 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:57:29,383 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

85c51b98151cf5b81ff732654c4ac487.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 288/793
======================================================================
Date: 1998-10-27
Output: ERA5_chunks_fixed/ERA5_1998-10-27.grib
Submitting request...

2026-08-30 13:57:35,857 INFO Request ID is 817fc511-d5cf-42e9-a026-63c230c7e1a9
INFO:ecmwf.datastores.legacy_client:Request ID is 817fc511-d5cf-42e9-a026-63c230c7e1a9
2026-08-30 13:57:36,116 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:57:59,866 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:58:28,845 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1ccd20ceee99ec69a261449a4afb2f87.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 289/793
======================================================================
Date: 1998-10-28
Output: ERA5_chunks_fixed/ERA5_1998-10-28.grib
Submitting request...

2026-08-30 13:58:35,328 INFO Request ID is 10cc8273-f342-4fcb-a980-c24181608584
INFO:ecmwf.datastores.legacy_client:Request ID is 10cc8273-f342-4fcb-a980-c24181608584
2026-08-30 13:58:35,567 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 13:59:09,520 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 13:59:26,839 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

94e406df33c69230ca7f01d5d96723e0.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 290/793
======================================================================
Date: 1998-11-13
Output: ERA5_chunks_fixed/ERA5_1998-11-13.grib
Submitting request...

2026-08-30 13:59:33,483 INFO Request ID is 97b29ccc-d72f-4ac0-bc10-b621398cc60d
INFO:ecmwf.datastores.legacy_client:Request ID is 97b29ccc-d72f-4ac0-bc10-b621398cc60d
2026-08-30 13:59:33,749 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:00:08,432 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:00:25,751 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

30482d58ae37d4436cda0cace385b6b3.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 291/793
======================================================================
Date: 1998-11-14
Output: ERA5_chunks_fixed/ERA5_1998-11-14.grib
Submitting request...

2026-08-30 14:00:33,931 INFO Request ID is b9d85c91-8407-4dc8-a09c-27a711080994
INFO:ecmwf.datastores.legacy_client:Request ID is b9d85c91-8407-4dc8-a09c-27a711080994
2026-08-30 14:00:34,958 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:01:08,758 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:01:26,106 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

bf4c3f013d1c0e42fc4a1cd14f8d9aa9.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 292/793
======================================================================
Date: 1998-11-19
Output: ERA5_chunks_fixed/ERA5_1998-11-19.grib
Submitting request...

2026-08-30 14:01:32,483 INFO Request ID is 8cb3c5fc-4c71-4129-a56b-6a89d5fdcd9b
INFO:ecmwf.datastores.legacy_client:Request ID is 8cb3c5fc-4c71-4129-a56b-6a89d5fdcd9b
2026-08-30 14:01:32,711 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:01:56,382 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:02:08,027 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

14d06f341c70cdb3bdb77b19f6e8afe6.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 293/793
======================================================================
Date: 1998-11-20
Output: ERA5_chunks_fixed/ERA5_1998-11-20.grib
Submitting request...

2026-08-30 14:02:14,391 INFO Request ID is 9cfffd18-b589-44fa-8c23-f28ac72e7872
INFO:ecmwf.datastores.legacy_client:Request ID is 9cfffd18-b589-44fa-8c23-f28ac72e7872
2026-08-30 14:02:14,637 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:02:36,858 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:03:05,804 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7bb1c573b6e64a664e454992ae925105.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 294/793
======================================================================
Date: 1998-11-21
Output: ERA5_chunks_fixed/ERA5_1998-11-21.grib
Submitting request...

2026-08-30 14:03:12,940 INFO Request ID is 65c5fe37-95df-40b5-92e4-60fd2f70814a
INFO:ecmwf.datastores.legacy_client:Request ID is 65c5fe37-95df-40b5-92e4-60fd2f70814a
2026-08-30 14:03:13,233 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:03:28,770 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:04:05,865 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

815109c3e3aa5e15689b6ee016b0a98b.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 295/793
======================================================================
Date: 1999-02-01
Output: ERA5_chunks_fixed/ERA5_1999-02-01.grib
Submitting request...

2026-08-30 14:04:13,131 INFO Request ID is cebae1ee-f249-4bf8-ad12-3b146002d444
INFO:ecmwf.datastores.legacy_client:Request ID is cebae1ee-f249-4bf8-ad12-3b146002d444
2026-08-30 14:04:13,554 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:04:29,609 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:04:49,079 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c6c82771483effef35f226364b1621ea.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 296/793
======================================================================
Date: 1999-02-02
Output: ERA5_chunks_fixed/ERA5_1999-02-02.grib
Submitting request...

2026-08-30 14:04:55,798 INFO Request ID is 74fd96ca-1443-4983-b7c7-5e6535096b95
INFO:ecmwf.datastores.legacy_client:Request ID is 74fd96ca-1443-4983-b7c7-5e6535096b95
2026-08-30 14:04:56,027 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:05:30,326 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:06:13,540 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

27f80bc29e1e886c5a0b7ccfd364bb64.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 297/793
======================================================================
Date: 1999-08-06
Output: ERA5_chunks_fixed/ERA5_1999-08-06.grib
Submitting request...

2026-08-30 14:06:20,233 INFO Request ID is c34dba59-40e9-4e65-b1bb-c2cda69e9b4a
INFO:ecmwf.datastores.legacy_client:Request ID is c34dba59-40e9-4e65-b1bb-c2cda69e9b4a
2026-08-30 14:06:20,885 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:06:43,874 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:07:12,833 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

bbe219f5bfc431baa5a3e23fec4db3f8.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 298/793
======================================================================
Date: 1999-08-07
Output: ERA5_chunks_fixed/ERA5_1999-08-07.grib
Submitting request...

2026-08-30 14:07:19,666 INFO Request ID is 6c408db7-0acd-40de-9add-770f61d1d8a1
INFO:ecmwf.datastores.legacy_client:Request ID is 6c408db7-0acd-40de-9add-770f61d1d8a1
2026-08-30 14:07:19,910 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:07:42,493 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:07:54,115 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3bbde6d4615dbcbb2a6f92b8918be635.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 299/793
======================================================================
Date: 1999-10-15
Output: ERA5_chunks_fixed/ERA5_1999-10-15.grib
Submitting request...

2026-08-30 14:08:01,966 INFO Request ID is e6d16998-fc79-40c2-afa1-55fa80f444cc
INFO:ecmwf.datastores.legacy_client:Request ID is e6d16998-fc79-40c2-afa1-55fa80f444cc
2026-08-30 14:08:02,241 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:08:25,488 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:08:54,451 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e1587e8db84c388e172b8b3bbf15cc26.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 300/793
======================================================================
Date: 1999-10-16
Output: ERA5_chunks_fixed/ERA5_1999-10-16.grib
Submitting request...

2026-08-30 14:09:04,033 INFO Request ID is f4bf1f70-a9cd-4cfb-be51-bca3ac20f6bd
INFO:ecmwf.datastores.legacy_client:Request ID is f4bf1f70-a9cd-4cfb-be51-bca3ac20f6bd
2026-08-30 14:09:04,439 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:09:26,828 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:09:38,448 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

411a5cf9c51160d21781abea1152d2d4.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 301/793
======================================================================
Date: 1999-10-25
Output: ERA5_chunks_fixed/ERA5_1999-10-25.grib
Submitting request...

2026-08-30 14:09:45,048 INFO Request ID is 3c37a4cc-a54c-42f9-93f2-efa8fddc0730
INFO:ecmwf.datastores.legacy_client:Request ID is 3c37a4cc-a54c-42f9-93f2-efa8fddc0730
2026-08-30 14:09:45,274 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:10:20,552 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:10:37,910 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f59c7755f0f014fc80e2979b38b92373.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 302/793
======================================================================
Date: 1999-10-26
Output: ERA5_chunks_fixed/ERA5_1999-10-26.grib
Submitting request...

2026-08-30 14:10:45,817 INFO Request ID is 2c7c754b-b767-4e28-baad-b1935faa452e
INFO:ecmwf.datastores.legacy_client:Request ID is 2c7c754b-b767-4e28-baad-b1935faa452e
2026-08-30 14:10:46,059 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:11:08,847 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:11:37,816 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a447c7258775699b57af735309a2fec3.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 303/793
======================================================================
Date: 1999-10-27
Output: ERA5_chunks_fixed/ERA5_1999-10-27.grib
Submitting request...

2026-08-30 14:11:44,225 INFO Request ID is f003058a-be4e-40d7-a73b-1376deb2f6cc
INFO:ecmwf.datastores.legacy_client:Request ID is f003058a-be4e-40d7-a73b-1376deb2f6cc
2026-08-30 14:11:44,481 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:12:06,697 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:12:36,278 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5868ae7cb03730bf67714fdb266be790.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 304/793
======================================================================
Date: 1999-10-28
Output: ERA5_chunks_fixed/ERA5_1999-10-28.grib
Submitting request...

2026-08-30 14:12:42,497 INFO Request ID is be2be339-b00a-49ab-863b-87997761db7e
INFO:ecmwf.datastores.legacy_client:Request ID is be2be339-b00a-49ab-863b-87997761db7e
2026-08-30 14:12:42,740 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:13:16,789 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:13:34,118 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

78842c61c47f98ff62533c9008e45405.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 305/793
======================================================================
Date: 1999-12-08
Output: ERA5_chunks_fixed/ERA5_1999-12-08.grib
Submitting request...

2026-08-30 14:13:40,531 INFO Request ID is a8db5be4-959a-439a-a6ca-3592a1508559
INFO:ecmwf.datastores.legacy_client:Request ID is a8db5be4-959a-439a-a6ca-3592a1508559
2026-08-30 14:13:40,759 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:14:06,268 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:14:35,220 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fc6e6cd9b263dd12f9d401c5365f3c19.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 306/793
======================================================================
Date: 1999-12-09
Output: ERA5_chunks_fixed/ERA5_1999-12-09.grib
Submitting request...

2026-08-30 14:14:41,813 INFO Request ID is 920926df-2598-4099-8652-6f5bda8655dc
INFO:ecmwf.datastores.legacy_client:Request ID is 920926df-2598-4099-8652-6f5bda8655dc
2026-08-30 14:14:42,059 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:14:58,067 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:15:17,574 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3e5eaaa3acc53cda4cf2f034ac4b6a39.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 307/793
======================================================================
Date: 2000-03-27
Output: ERA5_chunks_fixed/ERA5_2000-03-27.grib
Submitting request...

2026-08-30 14:15:24,140 INFO Request ID is 4e90a55e-11dc-4d96-b021-d20c730afcf8
INFO:ecmwf.datastores.legacy_client:Request ID is 4e90a55e-11dc-4d96-b021-d20c730afcf8
2026-08-30 14:15:24,394 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:15:59,911 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:16:43,386 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a9bd3bee56a8a8677fd4c83240bbca3c.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 308/793
======================================================================
Date: 2000-03-28
Output: ERA5_chunks_fixed/ERA5_2000-03-28.grib
Submitting request...

2026-08-30 14:16:50,124 INFO Request ID is 5e28f8bf-f095-4d11-807e-8918b94d8885
INFO:ecmwf.datastores.legacy_client:Request ID is 5e28f8bf-f095-4d11-807e-8918b94d8885
2026-08-30 14:16:50,380 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:17:41,588 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7a703aa11db131c595506cc5332e1602.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 309/793
======================================================================
Date: 2000-03-29
Output: ERA5_chunks_fixed/ERA5_2000-03-29.grib
Submitting request...

2026-08-30 14:17:48,229 INFO Request ID is ffce19b4-fe10-4d2b-b3e2-8e8a180218b5
INFO:ecmwf.datastores.legacy_client:Request ID is ffce19b4-fe10-4d2b-b3e2-8e8a180218b5
2026-08-30 14:17:48,457 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:18:24,583 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-30 14:18:41,944 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ea578bedeadff2e22e97d31dce36987d.grib:   0%|          | 0.00/5.96M [00:00<?, ?B/s]

SUCCESS
Size: 5.96 MB

======================================================================
DAY 310/793
======================================================================
Date: 2000-10-15
Output: ERA5_chunks_fixed/ERA5_2000-10-15.grib
Submitting request...

2026-08-30 14:18:48,437 INFO Request ID is 43842ae9-3587-4d88-9fbc-ff45971ae91a
INFO:ecmwf.datastores.legacy_client:Request ID is 43842ae9-3587-4d88-9fbc-ff45971ae91a
2026-08-30 14:18:48,708 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-30 14:19:23,236 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running

KeyboardInterrupt:

In [151]:
import glob
import xarray as xr
import os

era5_files = sorted(glob.glob("/content/ERA5_chunks_fixed/*.grib"))

print("=" * 70)
print("ERA5 FILE CHECK")
print("=" * 70)

print("ERA5 files found:", len(era5_files))

test_file = era5_files[0]

print("\nTesting file:")
print(test_file)

# Open GRIB file
ds = xr.open_dataset(
    test_file,
    engine="cfgrib"
)

print("\n" + "=" * 70)
print("ERA5 DATASET")
print("=" * 70)

print(ds)

print("\n" + "=" * 70)
print("VARIABLES")
print("=" * 70)

print(list(ds.data_vars))

print("\n" + "=" * 70)
print("DIMENSIONS")
print("=" * 70)

print(ds.dims)

print("\n" + "=" * 70)
print("COORDINATES")
print("=" * 70)

print(list(ds.coords))

======================================================================
ERA5 FILE CHECK
======================================================================
ERA5 files found: 308

Testing file:
/content/ERA5_chunks_fixed/ERA5_1982-05-01.grib

======================================================================
ERA5 DATASET
======================================================================
<xarray.Dataset> Size: 12MB
Dimensions:        (time: 8, isobaricInhPa: 4, latitude: 121, longitude: 161)
Coordinates:
  * time           (time) datetime64[ns] 64B 1982-05-01 ... 1982-05-01T21:00:00
  * isobaricInhPa  (isobaricInhPa) float64 32B 850.0 700.0 500.0 200.0
  * latitude       (latitude) float64 968B 30.0 29.75 29.5 ... 0.5 0.25 0.0
  * longitude      (longitude) float64 1kB 65.0 65.25 65.5 ... 104.5 104.8 105.0
    number         int64 8B ...
    step           timedelta64[ns] 8B ...
    valid_time     (time) datetime64[ns] 64B ...
Data variables:
    d              (time, isobaricInhPa, latitude, longitude) float32 2MB ...
    r              (time, isobaricInhPa, latitude, longitude) float32 2MB ...
    t              (time, isobaricInhPa, latitude, longitude) float32 2MB ...
    u              (time, isobaricInhPa, latitude, longitude) float32 2MB ...
    v              (time, isobaricInhPa, latitude, longitude) float32 2MB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-08-30T14:22 GRIB to CDM+CF via cfgrib-0.9.1...

======================================================================
VARIABLES
======================================================================
['d', 'r', 't', 'u', 'v']

======================================================================
DIMENSIONS
======================================================================
FrozenMappingWarningOnValuesAccess({'time': 8, 'isobaricInhPa': 4, 'latitude': 121, 'longitude': 161})

======================================================================
COORDINATES
======================================================================
['number', 'time', 'step', 'isobaricInhPa', 'latitude', 'longitude', 'valid_time']

In [152]:
# ================================================================
# ERA5 → IMD FEATURE EXTRACTION — MVP
# ================================================================

import os
import glob
import numpy as np
import pandas as pd
import xarray as xr

print("=" * 70)
print("ERA5 → IMD FEATURE EXTRACTION")
print("=" * 70)

# ------------------------------------------------
# 1. Load IMD-ERA5 observation table
# ------------------------------------------------

imd_files = glob.glob("/content/*IMD*ERA5*.csv")

print("\nPossible IMD-ERA5 files:")
for f in imd_files:
    print(os.path.basename(f))

# Prefer the ready file if it exists
ready_files = [
    f for f in imd_files
    if "ready" in os.path.basename(f).lower()
]

if ready_files:
    imd_file = ready_files[0]
else:
    imd_file = imd_files[0]

print("\nUsing:")
print(imd_file)

df = pd.read_csv(imd_file)

print("\nIMD rows:", len(df))
print("Columns:")
print(df.columns.tolist())


# ------------------------------------------------
# 2. Identify required columns
# ------------------------------------------------

# Rename common possibilities into standard names

column_map = {}

for col in df.columns:
    c = col.lower()

    if c in ["storm_id", "stormid", "sid"]:
        column_map[col] = "storm_id"

    elif "datetime" in c and "utc" in c:
        column_map[col] = "datetime_utc"

    elif c == "datetime":
        column_map[col] = "datetime_utc"

    elif c in ["latitude", "lat"]:
        column_map[col] = "latitude"

    elif c in ["longitude", "lon", "lng"]:
        column_map[col] = "longitude"

    elif "ri_24h" in c:
        column_map[col] = "RI_24h"

df = df.rename(columns=column_map)

required = [
    "storm_id",
    "datetime_utc",
    "latitude",
    "longitude",
    "RI_24h"
]

missing = [c for c in required if c not in df.columns]

if missing:
    raise ValueError(
        f"Missing required columns: {missing}\n"
        f"Available columns: {df.columns.tolist()}"
    )

df["datetime_utc"] = pd.to_datetime(df["datetime_utc"])

print("\nRequired columns found ✓")


# ------------------------------------------------
# 3. ERA5 files
# ------------------------------------------------

era5_files = sorted(
    glob.glob("/content/ERA5_chunks_fixed/*.grib")
)

print("\nERA5 files:", len(era5_files))


# Create date → ERA5 file lookup
era5_lookup = {}

for f in era5_files:

    name = os.path.basename(f)

    # ERA5_YYYY-MM-DD.grib
    date_string = name.replace(
        "ERA5_", ""
    ).replace(
        ".grib", ""
    )

    try:
        date = pd.Timestamp(date_string).date()
        era5_lookup[date] = f
    except:
        pass

print("ERA5 dates indexed:", len(era5_lookup))


# ------------------------------------------------
# 4. Variables and pressure levels
# ------------------------------------------------

levels = [850, 700, 500, 200]

variables = ["d", "r", "t", "u", "v"]


# ------------------------------------------------
# 5. Extract
# ------------------------------------------------

results = []

successful = 0
missing_dates = 0
failed = 0

for i, row in df.iterrows():

    dt = row["datetime_utc"]

    lat = float(row["latitude"])
    lon = float(row["longitude"])

    date = dt.date()

    print(
        f"\rProcessing {i+1}/{len(df)}",
        end=""
    )

    # Find ERA5 file for this date
    era_file = era5_lookup.get(date)

    if era_file is None:
        missing_dates += 1
        continue

    try:

        # Open GRIB
        ds = xr.open_dataset(
            era_file,
            engine="cfgrib",
            backend_kwargs={
                "indexpath": ""
            }
        )

        # Find nearest ERA5 time
        time_values = pd.to_datetime(
            ds.time.values
        )

        time_diff = np.abs(
            time_values - np.datetime64(dt)
        )

        nearest_idx = int(
            np.argmin(time_diff)
        )

        nearest_time = time_values[
            nearest_idx
        ]

        delta_minutes = abs(
            (nearest_time - dt).total_seconds()
        ) / 60.0

        # Only accept reasonably close ERA5 time
        if delta_minutes > 180:
            ds.close()
            failed += 1
            continue

        # Extract nearest grid point
        point = ds.sel(
            time=nearest_time,
            latitude=lat,
            longitude=lon,
            method="nearest"
        )

        feature_row = {
            "storm_id": row["storm_id"],
            "datetime_utc": dt,
            "latitude": lat,
            "longitude": lon,
            "RI_24h": row["RI_24h"],
            "era5_datetime": nearest_time,
            "era5_delta_minutes": delta_minutes
        }

        # Extract all variables at all pressure levels
        for var in variables:

            for level in levels:

                name = f"{var}_{level}"

                value = point[var].sel(
                    isobaricInhPa=level
                ).values

                feature_row[name] = float(
                    np.asarray(value)
                )

        # ------------------------------------------------
        # Derived vertical wind shear
        # ------------------------------------------------

        u850 = feature_row["u_850"]
        v850 = feature_row["v_850"]

        u200 = feature_row["u_200"]
        v200 = feature_row["v_200"]

        feature_row["shear_850_200"] = np.sqrt(
            (u200 - u850)**2 +
            (v200 - v850)**2
        )

        results.append(feature_row)

        successful += 1

        ds.close()

    except Exception as e:

        failed += 1

        try:
            ds.close()
        except:
            pass


print("\n\n" + "=" * 70)
print("ERA5 EXTRACTION COMPLETE")
print("=" * 70)

print("IMD observations :", len(df))
print("Successful        :", successful)
print("Missing dates     :", missing_dates)
print("Failed            :", failed)


# ------------------------------------------------
# 6. Save
# ------------------------------------------------

era5_df = pd.DataFrame(results)

output_file = "/content/RI_ERA5_features_MVP.csv"

era5_df.to_csv(
    output_file,
    index=False
)

print("\nSaved:")
print(output_file)

print("\nShape:")
print(era5_df.shape)

print("\nColumns:")
print(era5_df.columns.tolist())

print("\nFirst rows:")
display(era5_df.head())

======================================================================
ERA5 → IMD FEATURE EXTRACTION
======================================================================

Possible IMD-ERA5 files:
IMD_ERA5_observations_ready.csv

Using:
/content/IMD_ERA5_observations_ready.csv

IMD rows: 3198
Columns:
['storm_id', 'year', 'basin', 'name', 'datetime_utc', 'latitude', 'longitude', 'max_wind_kt', 'central_pressure_hpa', 'pressure_drop_hpa', 'grade', 'step', 'target_time_24h', 'wind_24h_kt', 'delta_v_24h_kt', 'RI_24h', 'wind_6h_change', 'target_time_minus_6h', 'wind_minus_6h_kt', 'delta_v_minus_6h_kt', 'target_time_minus_12h', 'wind_minus_12h_kt', 'delta_v_minus_12h_kt', 'target_time_minus_24h', 'wind_minus_24h_kt', 'delta_v_minus_24h_kt', 'era5_longitude', 'date', 'hour']

Required columns found ✓

ERA5 files: 308
ERA5 dates indexed: 308
Processing 3198/3198

======================================================================
ERA5 EXTRACTION COMPLETE
======================================================================
IMD observations : 3198
Successful        : 848
Missing dates     : 2350
Failed            : 0

Saved:
/content/RI_ERA5_features_MVP.csv

Shape:
(848, 28)

Columns:
['storm_id', 'datetime_utc', 'latitude', 'longitude', 'RI_24h', 'era5_datetime', 'era5_delta_minutes', 'd_850', 'd_700', 'd_500', 'd_200', 'r_850', 'r_700', 'r_500', 'r_200', 't_850', 't_700', 't_500', 't_200', 'u_850', 'u_700', 'u_500', 'u_200', 'v_850', 'v_700', 'v_500', 'v_200', 'shear_850_200']

First rows:

,storm_id,datetime_utc,latitude,longitude,RI_24h,era5_datetime,era5_delta_minutes,d_850,d_700,d_500,...,t_200,u_850,u_700,u_500,u_200,v_850,v_700,v_500,v_200,shear_850_200
0,1982-001,1982-05-01 03:00:00,14.0,82.5,0.0,1982-05-01 03:00:00,0.0,-4.079193e-07,0.000033,-0.000024,...,221.179657,-0.333221,-0.486984,3.079453,-4.276566,2.756058,0.794022,-3.036697,8.924133,7.320869
1,1982-001,1982-05-01 06:00:00,14.5,82.5,0.0,1982-05-01 06:00:00,0.0,-1.272652e-05,-0.000044,-0.000050,...,222.098419,-1.734726,-2.451477,2.816193,-3.117004,2.606705,-0.557419,-4.790710,7.907318,5.477882
2,1982-001,1982-05-01 12:00:00,15.0,82.0,0.0,1982-05-01 12:00:00,0.0,4.061800e-05,-0.000027,-0.000027,...,221.397064,-4.161774,-6.098007,7.409637,-0.488846,-1.988754,-9.247528,-12.736938,8.184021,10.815533
3,1982-001,1982-05-01 18:00:00,15.5,82.5,0.0,1982-05-01 18:00:00,0.0,-3.664079e-05,0.000015,-0.000011,...,220.130539,-1.106979,-3.779175,-2.242905,2.326035,-3.612183,-3.239044,-7.140091,5.994690,10.201842
4,1982-001,1982-05-02 00:00:00,16.0,83.0,0.0,1982-05-02 00:00:00,0.0,-6.458722e-07,-0.000001,0.000009,...,220.519363,-2.156296,-3.857742,-1.984146,-4.064621,-6.790405,-6.913818,-9.145142,8.522324,15.431182

In [153]:
# ================================================================
# ERA5-ONLY XGBOOST — MVP
# ================================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)
from xgboost import XGBClassifier

print("=" * 70)
print("ERA5-ONLY RI MODEL")
print("=" * 70)

# ------------------------------------------------
# Load ERA5 features
# ------------------------------------------------

df = pd.read_csv("/content/RI_ERA5_features_MVP.csv")

df["datetime_utc"] = pd.to_datetime(df["datetime_utc"])

print("Rows:", len(df))
print("Storms:", df["storm_id"].nunique())

print("\nRI distribution:")
print(df["RI_24h"].value_counts())


# ------------------------------------------------
# Features
# ------------------------------------------------

feature_cols = [
    "d_850", "d_700", "d_500", "d_200",
    "r_850", "r_700", "r_500", "r_200",
    "t_850", "t_700", "t_500", "t_200",
    "u_850", "u_700", "u_500", "u_200",
    "v_850", "v_700", "v_500", "v_200",
    "shear_850_200"
]

X = df[feature_cols].copy()
y = df["RI_24h"].astype(int)
groups = df["storm_id"]


# ------------------------------------------------
# Remove bad values
# ------------------------------------------------

X = X.replace([np.inf, -np.inf], np.nan)

valid = X.notna().all(axis=1)

X = X.loc[valid]
y = y.loc[valid]
groups = groups.loc[valid]
df_model = df.loc[valid].copy()

print("\nUsable rows:", len(X))


# ------------------------------------------------
# STORM-SAFE SPLIT
# ------------------------------------------------

gss1 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss1.split(X, y, groups)
)

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]

y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

groups_train = groups.iloc[train_idx]
groups_test = groups.iloc[test_idx]

print("\n" + "=" * 70)
print("STORM-SAFE SPLIT")
print("=" * 70)

print("Train:", len(X_train))
print("Test :", len(X_test))

print("Train storms:", groups_train.nunique())
print("Test storms :", groups_test.nunique())

print("\nTrain RI:")
print(y_train.value_counts())

print("\nTest RI:")
print(y_test.value_counts())


# ------------------------------------------------
# CLASS WEIGHT
# ------------------------------------------------

n0 = (y_train == 0).sum()
n1 = (y_train == 1).sum()

scale_pos_weight = n0 / n1

print("\nscale_pos_weight:", scale_pos_weight)


# ------------------------------------------------
# XGBOOST
# ------------------------------------------------

model = XGBClassifier(
    n_estimators=300,
    max_depth=3,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    random_state=42
)

print("\n" + "=" * 70)
print("TRAINING ERA5 XGBOOST")
print("=" * 70)

model.fit(
    X_train,
    y_train
)

print("✅ TRAINING COMPLETE")


# ------------------------------------------------
# PREDICTIONS
# ------------------------------------------------

p_test = model.predict_proba(X_test)[:, 1]

# Standard threshold
pred_test = (p_test >= 0.5).astype(int)


# ------------------------------------------------
# METRICS
# ------------------------------------------------

roc = roc_auc_score(y_test, p_test)
pr = average_precision_score(y_test, p_test)

precision = precision_score(
    y_test,
    pred_test,
    zero_division=0
)

recall = recall_score(
    y_test,
    pred_test,
    zero_division=0
)

f1 = f1_score(
    y_test,
    pred_test,
    zero_division=0
)

cm = confusion_matrix(
    y_test,
    pred_test
)

print("\n" + "=" * 70)
print("ERA5-ONLY TEST RESULTS")
print("=" * 70)

print(f"ROC-AUC : {roc:.4f}")
print(f"PR-AUC  : {pr:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1       : {f1:.4f}")

print("\nConfusion Matrix:")
print(cm)


# ------------------------------------------------
# SAVE MODEL
# ------------------------------------------------

model.save_model(
    "/content/era5_only_xgboost_mvp.json"
)

print("\nModel saved:")
print("/content/era5_only_xgboost_mvp.json")


# ------------------------------------------------
# SAVE PREDICTIONS
# ------------------------------------------------

test_results = df_model.iloc[test_idx].copy()

test_results["P_RI"] = p_test
test_results["prediction"] = pred_test

test_results.to_csv(
    "/content/ERA5_only_test_predictions.csv",
    index=False
)

print("\nPredictions saved:")
print("/content/ERA5_only_test_predictions.csv")

======================================================================
ERA5-ONLY RI MODEL
======================================================================
Rows: 848
Storms: 107

RI distribution:
RI_24h
0.0    772
1.0     76
Name: count, dtype: int64

Usable rows: 848

======================================================================
STORM-SAFE SPLIT
======================================================================
Train: 660
Test : 188
Train storms: 85
Test storms : 22

Train RI:
RI_24h
0    605
1     55
Name: count, dtype: int64

Test RI:
RI_24h
0    167
1     21
Name: count, dtype: int64

scale_pos_weight: 11.0

======================================================================
TRAINING ERA5 XGBOOST
======================================================================
✅ TRAINING COMPLETE

======================================================================
ERA5-ONLY TEST RESULTS
======================================================================
ROC-AUC : 0.6618
PR-AUC  : 0.2001
Precision: 0.0909
Recall   : 0.0476
F1       : 0.0625

Confusion Matrix:
[[157  10]
 [ 20   1]]

Model saved:
/content/era5_only_xgboost_mvp.json

Predictions saved:
/content/ERA5_only_test_predictions.csv